using System.Globalization;
using System.Net;
using System.Text;
using QRCoder;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Features.Printing;
using ZXing;
using ZXing.Common;
using ZXing.Rendering;
namespace WhatsBiz.Infrastructure.Printing;
public sealed class PrintingService : IPrintingService
{
    public PrintArtifact Barcode(BarcodeInput x) { var writer = new BarcodeWriterSvg { Format = Format(x.Format), Options = new EncodingOptions { Width = x.Width, Height = x.Height, Margin = 8, PureBarcode = !x.ShowText }, Renderer = new SvgRenderer() }; var svg = writer.Write(x.Value).Content; return new(Encoding.UTF8.GetBytes(svg), "image/svg+xml", $"barcode-{Safe(x.Value)}.svg"); }
    public PrintArtifact QrCode(QRCodeInput x) { using var data = QRCodeGenerator.GenerateQrCode(x.Value, Ecc(x.ErrorCorrectionLevel)); var svg = new SvgQRCode(data).GetGraphic(x.PixelsPerModule); return new(Encoding.UTF8.GetBytes(svg), "image/svg+xml", $"qrcode-{Safe(x.Value)}.svg"); }
    public PrintArtifact Document(DocumentInput x) { var paper = PaperSizes.Normalize(x.PaperType); var cssClass = paper switch { "58MM" => "paper-58mm", "A4" => "paper-a4", _ => "paper-80mm" }; var html = $"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>{PageCss(paper)}{PaperCss}</style></head><body class='{cssClass}'><section class='document-shell'><header class='document-head'><h1>{WebUtility.HtmlEncode(x.Title)}</h1><strong>{WebUtility.HtmlEncode(x.DocumentNumber)}</strong></header>{x.BodyHtml}</section></body></html>"; if (x.Output == "html") return new(Encoding.UTF8.GetBytes(html), "text/html", $"{Safe(x.DocumentNumber)}.html"); return new(Pdf(x.Title, x.DocumentNumber, Strip(x.BodyHtml)), "application/pdf", $"{Safe(x.DocumentNumber)}.pdf"); }
    public PrintArtifact Label(LabelInput x) { var barcode = string.IsNullOrWhiteSpace(x.Barcode) ? "" : Encoding.UTF8.GetString(Barcode(new(x.Barcode, x.BarcodeFormat, 320, 80, true)).Data); var cards = string.Concat(Enumerable.Range(0, x.Quantity).Select(_ => $"<article><b>{WebUtility.HtmlEncode(x.ProductName)}</b><small>{WebUtility.HtmlEncode(x.ProductCode)}</small>{barcode}<strong>{(x.MRP is null ? "" : string.Create(CultureInfo.InvariantCulture, $"MRP ₹{x.MRP:0.00}"))}</strong><em>{(x.Price is null ? "" : string.Create(CultureInfo.InvariantCulture, $"₹{x.Price:0.00}"))}</em></article>")); var html = $"<!doctype html><style>@page{{size:{x.WidthMm}mm {x.HeightMm}mm;margin:1mm}}body{{margin:0;font-family:Arial}}article{{box-sizing:border-box;width:{x.WidthMm}mm;height:{x.HeightMm}mm;padding:1mm;display:flex;flex-direction:column;align-items:center;justify-content:center;page-break-after:always;overflow:hidden}}svg{{max-width:95%;height:35%}}small,strong,em{{display:block}}</style>{cards}"; return x.Output == "pdf" ? new(Pdf("Labels", x.ProductCode ?? x.ProductName, Strip(html)), "application/pdf", "labels.pdf") : new(Encoding.UTF8.GetBytes(html), "text/html", "labels.html"); }
    private static BarcodeFormat Format(string x) => x.ToUpperInvariant() switch { "EAN13" => BarcodeFormat.EAN_13, "EAN8" => BarcodeFormat.EAN_8, "UPC" => BarcodeFormat.UPC_A, "CODE39" => BarcodeFormat.CODE_39, _ => BarcodeFormat.CODE_128 }; private static QRCodeGenerator.ECCLevel Ecc(string x) => x.ToUpperInvariant() switch { "L" => QRCodeGenerator.ECCLevel.L, "Q" => QRCodeGenerator.ECCLevel.Q, "H" => QRCodeGenerator.ECCLevel.H, _ => QRCodeGenerator.ECCLevel.M }; private static string Safe(string x) => string.Concat(x.Take(40).Select(c => char.IsLetterOrDigit(c) ? c : '-')); private static string Strip(string x) => System.Text.RegularExpressions.Regex.Replace(x, "<[^>]+>", " ");
    private const string PaperCss = """
        *{box-sizing:border-box}html,body{padding:0;color:#111;background:#fff;font-family:Arial,sans-serif}.document-shell{margin:0 auto;overflow-wrap:anywhere}.document-head{text-align:center;margin-bottom:5mm}.document-head h1{margin:0 0 2mm}.invoice-brand{text-align:center;margin-bottom:3mm}.invoice-brand img{max-width:160px;max-height:48px;object-fit:contain}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{padding:1.5mm;border-bottom:1px solid #ccc;overflow-wrap:anywhere}.paper-58mm .document-shell{width:54mm;font-size:9px}.paper-58mm .document-head{margin-bottom:2mm}.paper-58mm .document-head h1{font-size:14px}.paper-58mm th,.paper-58mm td{padding:.7mm}.paper-80mm .document-shell{width:72mm;font-size:11px}.paper-80mm .document-head h1{font-size:18px}.paper-a4 .document-shell{width:190mm;min-height:277mm;font-size:11pt;padding:8mm}.paper-a4 .document-head{text-align:left;border-bottom:2px solid #222;padding-bottom:4mm}.paper-a4 th{background:#f2f4f7;text-align:left}.paper-a4 th,.paper-a4 td{padding:2.5mm}@media print{.no-print{display:none!important}html,body{margin:0!important}.document-shell{max-width:none}.paper-58mm .document-shell,.paper-80mm .document-shell{min-height:0}.paper-a4 .document-shell{min-height:0;padding:0}table{page-break-inside:auto}tr{page-break-inside:avoid;page-break-after:auto}}
        """;
    private static string PageCss(string paper) => paper switch { "58MM" => "@page{size:58mm auto;margin:2mm}", "A4" => "@page{size:A4 portrait;margin:10mm}", _ => "@page{size:80mm auto;margin:4mm}" };
    private static byte[] Pdf(string title, string number, string body) { var lines = new[] { title, number, body[..Math.Min(body.Length, 1200)] }; var content = new StringBuilder("BT /F1 10 Tf 40 800 Td "); foreach (var line in lines.SelectMany(x => x.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries))) content.Append(CultureInfo.InvariantCulture, $"({line.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)")}) Tj 0 -16 Td "); content.Append("ET"); var objects = new[] { "<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>", string.Create(CultureInfo.InvariantCulture, $"<< /Length {Encoding.ASCII.GetByteCount(content.ToString())} >>\nstream\n{content}\nendstream"), "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>" }; var b = new StringBuilder("%PDF-1.4\n"); var offsets = new List<int> { 0 }; for (var i = 0; i < objects.Length; i++) { offsets.Add(Encoding.ASCII.GetByteCount(b.ToString())); b.Append(CultureInfo.InvariantCulture, $"{i + 1} 0 obj\n{objects[i]}\nendobj\n"); } var xref = Encoding.ASCII.GetByteCount(b.ToString()); b.Append(CultureInfo.InvariantCulture, $"xref\n0 {objects.Length + 1}\n0000000000 65535 f \n"); foreach (var o in offsets.Skip(1)) b.Append(CultureInfo.InvariantCulture, $"{o:D10} 00000 n \n"); b.Append(CultureInfo.InvariantCulture, $"trailer << /Size {objects.Length + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF"); return Encoding.ASCII.GetBytes(b.ToString()); }
}
