using System.Globalization;
using System.Net;
using System.Text;
using QRCoder;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Features.Printing;
using ZXing;
using ZXing.Common;
using ZXing.Rendering;
namespace WhatsBiz.Infrastructure.Printing;
public sealed class PrintingService : IPrintingService
{
    public PrintArtifact Barcode(BarcodeInput x) { var writer = new BarcodeWriterSvg { Format = Format(x.Format), Options = new EncodingOptions { Width = x.Width, Height = x.Height, Margin = 8, PureBarcode = !x.ShowText }, Renderer = new SvgRenderer() }; var svg = writer.Write(x.Value).Content; return new(Encoding.UTF8.GetBytes(svg), "image/svg+xml", $"barcode-{Safe(x.Value)}.svg"); }
    public PrintArtifact QrCode(QRCodeInput x) { using var data = QRCodeGenerator.GenerateQrCode(x.Value, Ecc(x.ErrorCorrectionLevel)); var svg = new SvgQRCode(data).GetGraphic(x.PixelsPerModule); return new(Encoding.UTF8.GetBytes(svg), "image/svg+xml", $"qrcode-{Safe(x.Value)}.svg"); }
    public PrintArtifact Document(DocumentInput x) { var width = x.PaperType.ToUpperInvariant() switch { "58MM" => "58mm", "80MM" => "80mm", _ => "210mm" }; var html = $"<!doctype html><html><head><meta charset='utf-8'><style>@page{{size:{width} auto;margin:4mm}}body{{font-family:Arial,sans-serif;max-width:{width};margin:auto;color:#111}}table{{width:100%;border-collapse:collapse}}th,td{{padding:5px;border-bottom:1px solid #ccc}}.document-head{{text-align:center}}.invoice-brand{{text-align:center;margin-bottom:8px}}.invoice-brand img{{max-width:160px;max-height:48px;object-fit:contain}}@media print{{.no-print{{display:none}}}}</style></head><body><section class='document-head'><h1>{WebUtility.HtmlEncode(x.Title)}</h1><strong>{WebUtility.HtmlEncode(x.DocumentNumber)}</strong></section>{x.BodyHtml}</body></html>"; if (x.Output == "html") return new(Encoding.UTF8.GetBytes(html), "text/html", $"{Safe(x.DocumentNumber)}.html"); return new(Pdf(x.Title, x.DocumentNumber, Strip(x.BodyHtml)), "application/pdf", $"{Safe(x.DocumentNumber)}.pdf"); }
    public PrintArtifact Label(LabelInput x) { var barcode = string.IsNullOrWhiteSpace(x.Barcode) ? "" : Encoding.UTF8.GetString(Barcode(new(x.Barcode, x.BarcodeFormat, 320, 80, true)).Data); var cards = string.Concat(Enumerable.Range(0, x.Quantity).Select(_ => $"<article><b>{WebUtility.HtmlEncode(x.ProductName)}</b><small>{WebUtility.HtmlEncode(x.ProductCode)}</small>{barcode}<strong>{(x.MRP is null ? "" : string.Create(CultureInfo.InvariantCulture, $"MRP ₹{x.MRP:0.00}"))}</strong><em>{(x.Price is null ? "" : string.Create(CultureInfo.InvariantCulture, $"₹{x.Price:0.00}"))}</em></article>")); var html = $"<!doctype html><style>@page{{size:{x.WidthMm}mm {x.HeightMm}mm;margin:1mm}}body{{margin:0;font-family:Arial}}article{{box-sizing:border-box;width:{x.WidthMm}mm;height:{x.HeightMm}mm;padding:1mm;display:flex;flex-direction:column;align-items:center;justify-content:center;page-break-after:always;overflow:hidden}}svg{{max-width:95%;height:35%}}small,strong,em{{display:block}}</style>{cards}"; return x.Output == "pdf" ? new(Pdf("Labels", x.ProductCode ?? x.ProductName, Strip(html)), "application/pdf", "labels.pdf") : new(Encoding.UTF8.GetBytes(html), "text/html", "labels.html"); }
    private static BarcodeFormat Format(string x) => x.ToUpperInvariant() switch { "EAN13" => BarcodeFormat.EAN_13, "EAN8" => BarcodeFormat.EAN_8, "UPC" => BarcodeFormat.UPC_A, "CODE39" => BarcodeFormat.CODE_39, _ => BarcodeFormat.CODE_128 }; private static QRCodeGenerator.ECCLevel Ecc(string x) => x.ToUpperInvariant() switch { "L" => QRCodeGenerator.ECCLevel.L, "Q" => QRCodeGenerator.ECCLevel.Q, "H" => QRCodeGenerator.ECCLevel.H, _ => QRCodeGenerator.ECCLevel.M }; private static string Safe(string x) => string.Concat(x.Take(40).Select(c => char.IsLetterOrDigit(c) ? c : '-')); private static string Strip(string x) => System.Text.RegularExpressions.Regex.Replace(x, "<[^>]+>", " ");
    private static byte[] Pdf(string title, string number, string body) { var lines = new[] { title, number, body[..Math.Min(body.Length, 1200)] }; var content = new StringBuilder("BT /F1 10 Tf 40 800 Td "); foreach (var line in lines.SelectMany(x => x.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries))) content.Append(CultureInfo.InvariantCulture, $"({line.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)")}) Tj 0 -16 Td "); content.Append("ET"); var objects = new[] { "<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>", string.Create(CultureInfo.InvariantCulture, $"<< /Length {Encoding.ASCII.GetByteCount(content.ToString())} >>\nstream\n{content}\nendstream"), "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>" }; var b = new StringBuilder("%PDF-1.4\n"); var offsets = new List<int> { 0 }; for (var i = 0; i < objects.Length; i++) { offsets.Add(Encoding.ASCII.GetByteCount(b.ToString())); b.Append(CultureInfo.InvariantCulture, $"{i + 1} 0 obj\n{objects[i]}\nendobj\n"); } var xref = Encoding.ASCII.GetByteCount(b.ToString()); b.Append(CultureInfo.InvariantCulture, $"xref\n0 {objects.Length + 1}\n0000000000 65535 f \n"); foreach (var o in offsets.Skip(1)) b.Append(CultureInfo.InvariantCulture, $"{o:D10} 00000 n \n"); b.Append(CultureInfo.InvariantCulture, $"trailer << /Size {objects.Length + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF"); return Encoding.ASCII.GetBytes(b.ToString()); }
}
