#pragma warning disable CA1716
using WhatsBiz.Domain.Inventory;
namespace WhatsBiz.Application.Common.Interfaces;
public sealed record InventoryOperationResult(Guid OperationId, Guid TransactionId, string Number); public sealed record InventoryAdjustmentRequest(Guid ProductId, Guid WarehouseId, Guid? ZoneId, Guid? BinId, string? BatchNo, string? SerialNo, decimal Quantity, decimal UnitCost, string AdjustmentType, string ReasonCode, string? Remarks, string? User); public sealed record InventoryTransferRequest(Guid ProductId, Guid SourceWarehouseId, Guid DestinationWarehouseId, decimal Quantity, DateTimeOffset TransferDate, string? Remarks, string? User); public sealed record InventoryReservationRequest(string Action, Guid? StockReservationId, Guid? ProductId, Guid? WarehouseId, decimal Quantity, string? Reason, string? ReferenceType, Guid? ReferenceId, string? User);
public interface IInventoryService { Task<InventoryOperationResult> Adjust(InventoryAdjustmentRequest request, CancellationToken token); Task<InventoryOperationResult> Transfer(InventoryTransferRequest request, CancellationToken token); Task<InventoryOperationResult> Reserve(InventoryReservationRequest request, CancellationToken token); }
public interface IInventoryRepository { Task<(IReadOnlyCollection<InventoryBalance>, int)> Balances(string? search, Guid? warehouseId, Guid? productId, int page, int size, CancellationToken token); Task<(IReadOnlyCollection<InventoryTransaction>, int)> Transactions(string? search, Guid? warehouseId, string? type, DateTimeOffset? from, DateTimeOffset? toDate, int page, int size, CancellationToken token); Task<InventoryTransaction?> Transaction(Guid id, CancellationToken token); Task<IReadOnlyCollection<StockReservation>> Reservations(Guid? warehouseId, Guid? productId, CancellationToken token); Task<InventorySummary> Summary(Guid? warehouseId, CancellationToken token); }
public interface IInventoryOperationsRepository { Task<WhatsBiz.Application.Features.Inventory.PagedOperations> Adjustments(string? search, Guid? warehouseId, DateTimeOffset? from, DateTimeOffset? to, int page, int size, CancellationToken token); Task<WhatsBiz.Application.Features.Inventory.OperationDto> CreateAdjustment(WhatsBiz.Application.Features.Inventory.StockAdjustmentDocument input, string? user, CancellationToken token); Task<WhatsBiz.Application.Features.Inventory.PagedOperations> Transfers(string? search, Guid? warehouseId, DateTimeOffset? from, DateTimeOffset? to, int page, int size, CancellationToken token); Task<WhatsBiz.Application.Features.Inventory.OperationDto> CreateTransfer(WhatsBiz.Application.Features.Inventory.StockTransferDocument input, string? user, CancellationToken token); Task<WhatsBiz.Application.Features.Inventory.PagedOperations> Verifications(string? search, Guid? warehouseId, int page, int size, CancellationToken token); Task<WhatsBiz.Application.Features.Inventory.OperationDto> CreateVerification(WhatsBiz.Application.Features.Inventory.VerificationDocument input, string? user, CancellationToken token); Task<IReadOnlyCollection<WhatsBiz.Application.Features.Inventory.StockControlRow>> Reorder(Guid? warehouseId, Guid? categoryId, Guid? productId, string? search, CancellationToken token); Task<IReadOnlyCollection<WhatsBiz.Application.Features.Inventory.StockControlRow>> Alerts(Guid? warehouseId, Guid? categoryId, Guid? productId, string? status, string? search, CancellationToken token); Task<WhatsBiz.Application.Features.Inventory.PagedMovements> Movements(Guid? warehouseId, Guid? productId, DateTimeOffset? from, DateTimeOffset? to, string? search, int page, int size, CancellationToken token); }
public sealed record InventorySummary(decimal TotalQuantity, decimal TotalStockValue, decimal ReservedStock, int LowStockProducts, int OutOfStockProducts);
public interface IInventorySpreadsheetService { byte[] ExportBalances(IReadOnlyCollection<InventoryBalance> balances); }
