#pragma warning disable CA1716
using WhatsBiz.Domain.POS;
using WhatsBiz.Domain.Products;
using WhatsBiz.Domain.Customers;
namespace WhatsBiz.Application.Common.Interfaces;
public sealed record POSPostRequest(Guid? CounterId, Guid? ShiftId, Guid? CustomerId, Guid WarehouseId, Guid? SalesPersonId, string ItemsJson, string? PaymentsJson, decimal BillDiscount, decimal RoundOff, string? Remarks, string Status, bool InterState, string? DiscountAuthorizedBy, string? User); public sealed record POSPostResult(Guid InvoiceId, string InvoiceNumber, decimal GrandTotal, decimal PaidAmount, string Status); public sealed record POSPaymentRequest(Guid InvoiceId, string MethodCode, decimal Amount, string? ReferenceNumber, string? User); public sealed record POSReturnRequest(Guid InvoiceId, string ItemsJson, string Reason, string? User); public interface IPOSEngine { Task<POSPostResult> Post(POSPostRequest request, CancellationToken token); Task Pay(POSPaymentRequest request, CancellationToken token); Task Return(POSReturnRequest request, CancellationToken token); }
public interface IPOSRepository { Task<IReadOnlyCollection<Product>> Products(string? search, string? barcode, int size, CancellationToken token); Task<IReadOnlyCollection<Customer>> Customers(string? search, int size, CancellationToken token); Task<SalesInvoice?> Invoice(Guid id, CancellationToken token); Task<(IReadOnlyCollection<SalesInvoice>, int)> Invoices(string? search, string? status, DateTimeOffset? from, DateTimeOffset? toDate, int page, int size, CancellationToken token); Task<IReadOnlyCollection<PaymentMethod>> PaymentMethods(CancellationToken token); Task<POSTodaySummary> Today(CancellationToken token); }
public sealed record POSTodaySummary(decimal GrossSales, decimal Collections, int InvoiceCount, decimal Cash, decimal UPI, decimal Card);
public interface IPOSDocumentService { string InvoiceHtml(SalesInvoice invoice, string paper); byte[] Export(IReadOnlyCollection<SalesInvoice> invoices); }
