import { ChangeDetectionStrategy, Component, computed, inject, output } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { AuthenticationService } from '../../../core/services/authentication.service';
import { CurrentUserService } from '../../../core/services/current-user.service';
import { NotificationService } from '../../services/notification.service';
import { SearchBoxComponent } from '../../components/search-box/search-box.component';
import { NotificationPanelComponent } from '../../components/notification-panel/notification-panel.component';

@Component({ selector: 'app-topbar', imports: [MatButtonModule, MatMenuModule, SearchBoxComponent, NotificationPanelComponent], template: '<header><button class="mobile-menu" mat-icon-button type="button" aria-label="Open navigation" (click)="menuToggle.emit()"><span class="material-symbols-rounded">menu</span></button><div class="global-search"><app-search-box placeholder="Search modules, records and actions" ariaLabel="Global search" /></div><div class="topbar-actions"><button class="company-switch" mat-button type="button" [matMenuTriggerFor]="companyMenu"><span class="material-symbols-rounded">domain</span><span>KhataDhari</span><span class="material-symbols-rounded chevron">expand_more</span></button><button mat-icon-button type="button" aria-label="Dark mode coming soon" title="Dark mode coming soon"><span class="material-symbols-rounded">dark_mode</span></button><button class="notification-button" mat-icon-button type="button" aria-label="Notifications" [matMenuTriggerFor]="notificationMenu"><span class="material-symbols-rounded">notifications</span>@if (unread()) { <span class="notification-count">{{ unread() > 9 ? "9+" : unread() }}</span> }</button><button class="user-button" mat-button type="button" [matMenuTriggerFor]="userMenu"><span class="avatar">{{ initials() }}</span><span class="user-copy"><strong>{{ user()?.username ?? "User" }}</strong><small>{{ user()?.roles?.[0] ?? "Team member" }}</small></span><span class="material-symbols-rounded chevron">expand_more</span></button></div></header><mat-menu #companyMenu="matMenu"><button mat-menu-item disabled><span class="material-symbols-rounded">domain</span><span>Company switching coming soon</span></button></mat-menu><mat-menu #notificationMenu="matMenu" class="notification-menu"><app-notification-panel /></mat-menu><mat-menu #userMenu="matMenu"><button mat-menu-item type="button"><span class="material-symbols-rounded">person</span><span>My profile</span></button><button mat-menu-item type="button"><span class="material-symbols-rounded">tune</span><span>Preferences</span></button><button mat-menu-item type="button" (click)="authentication.logout()"><span class="material-symbols-rounded">logout</span><span>Sign out</span></button></mat-menu>', styleUrl: './topbar.component.scss', changeDetection: ChangeDetectionStrategy.OnPush })
export class TopbarComponent { readonly menuToggle = output<void>(); readonly authentication = inject(AuthenticationService); private readonly currentUser = inject(CurrentUserService); private readonly notifications = inject(NotificationService); readonly user = this.currentUser.user; readonly initials = computed(() => (this.user()?.username ?? 'U').slice(0, 2).toUpperCase()); readonly unread = computed(() => this.notifications.notifications().filter((item) => !item.read).length); }
