using WhatsBiz.Domain.Customers;using WhatsBiz.Domain.Products;using WhatsBiz.Domain.Warehouses;
namespace WhatsBiz.Domain.POS;
public sealed class SalesInvoice{public Guid InvoiceId{get;set;}public string InvoiceNumber{get;set;}="";public DateTimeOffset InvoiceDate{get;set;}public Guid? CounterId{get;set;}public Guid? ShiftId{get;set;}public Guid? CustomerId{get;set;}public Guid WarehouseId{get;set;}public Guid? SalesPersonId{get;set;}public decimal Subtotal{get;set;}public decimal DiscountAmount{get;set;}public decimal TaxAmount{get;set;}public decimal RoundOff{get;set;}public decimal GrandTotal{get;set;}public decimal PaidAmount{get;set;}public decimal BalanceAmount{get;private set;}public string Status{get;set;}="";public string? Remarks{get;set;}public Guid? OriginalInvoiceId{get;set;}public string? CreatedBy{get;set;}public DateTimeOffset CreatedOn{get;set;}public DateTimeOffset? ModifiedOn{get;set;}public byte[] RowVersion{get;set;}=[];public Customer? Customer{get;set;}public Warehouse Warehouse{get;set;}=null!;public ICollection<SalesInvoiceItem> Items{get;set;}=[];public ICollection<SalesPayment> Payments{get;set;}=[];public ICollection<SalesTax> Taxes{get;set;}=[];public ICollection<SalesDiscount> Discounts{get;set;}=[];}
public sealed class SalesInvoiceItem{public Guid InvoiceItemId{get;set;}public Guid InvoiceId{get;set;}public Guid ProductId{get;set;}public string? Barcode{get;set;}public decimal Quantity{get;set;}public decimal UnitPrice{get;set;}public decimal DiscountPercentage{get;set;}public decimal DiscountAmount{get;set;}public decimal TaxPercentage{get;set;}public decimal TaxAmount{get;set;}public decimal LineTotal{get;set;}public decimal ReturnedQuantity{get;set;}public Product Product{get;set;}=null!;}
public sealed class SalesPayment{public Guid PaymentId{get;set;}public Guid InvoiceId{get;set;}public Guid PaymentMethodId{get;set;}public decimal Amount{get;set;}public string? ReferenceNumber{get;set;}public DateTimeOffset PaymentDate{get;set;}public string Status{get;set;}="";public string? CreatedBy{get;set;}public PaymentMethod PaymentMethod{get;set;}=null!;}
public sealed class SalesTax{public Guid SalesTaxId{get;set;}public Guid InvoiceId{get;set;}public Guid? InvoiceItemId{get;set;}public string TaxType{get;set;}="";public decimal TaxPercentage{get;set;}public decimal TaxableAmount{get;set;}public decimal TaxAmount{get;set;}}
public sealed class SalesDiscount{public Guid SalesDiscountId{get;set;}public Guid InvoiceId{get;set;}public Guid? InvoiceItemId{get;set;}public string DiscountType{get;set;}="";public string DiscountMode{get;set;}="";public decimal DiscountValue{get;set;}public decimal DiscountAmount{get;set;}public string? AuthorizedBy{get;set;}public DateTimeOffset CreatedOn{get;set;}}
public sealed class PaymentMethod{public Guid PaymentMethodId{get;set;}public string MethodCode{get;set;}="";public string MethodName{get;set;}="";public bool RequiresReference{get;set;}public bool IsActive{get;set;}public int DisplayOrder{get;set;}public byte[] RowVersion{get;set;}=[];}
public sealed class SalesInvoiceReturn{public Guid ReturnId{get;set;}public string ReturnNumber{get;set;}="";public Guid InvoiceId{get;set;}public Guid InvoiceItemId{get;set;}public decimal Quantity{get;set;}public decimal RefundAmount{get;set;}public string Reason{get;set;}="";public DateTimeOffset ReturnDate{get;set;}public string Status{get;set;}="";public string? CreatedBy{get;set;}public DateTimeOffset CreatedOn{get;set;}}
