using WhatsBiz.Domain.POS;
using WhatsBiz.Domain.Products;
using WhatsBiz.Domain.Suppliers;
using WhatsBiz.Domain.Warehouses;
namespace WhatsBiz.Domain.Purchases;
public sealed class PurchaseInvoice { public Guid PurchaseInvoiceId { get; set; } = Guid.NewGuid(); public string InvoiceNumber { get; set; } = ""; public Guid SupplierId { get; set; } public string? SupplierInvoiceNo { get; set; } public DateTimeOffset InvoiceDate { get; set; } public DateTimeOffset? DueDate { get; set; } public Guid WarehouseId { get; set; } public decimal Subtotal { get; set; } public decimal DiscountAmount { get; set; } public decimal TaxAmount { get; set; } public decimal ExpenseAmount { get; set; } public decimal RoundOff { get; set; } public decimal GrandTotal { get; set; } public decimal PaidAmount { get; set; } public decimal BalanceAmount { get; set; } public string Status { get; set; } = ""; public string? Remarks { get; set; } public bool IsDeleted { get; set; } public DateTimeOffset CreatedOn { get; set; } public string? CreatedBy { get; set; } public DateTimeOffset? ModifiedOn { get; set; } public string? ModifiedBy { get; set; } public byte[] RowVersion { get; set; } = []; public Supplier Supplier { get; set; } = null!; public Warehouse Warehouse { get; set; } = null!; public ICollection<PurchaseInvoiceItem> Items { get; set; } = []; public ICollection<PurchasePayment> Payments { get; set; } = []; public ICollection<PurchaseExpense> Expenses { get; set; } = []; public ICollection<PurchaseAttachment> Attachments { get; set; } = []; }
public sealed class PurchaseInvoiceItem { public Guid PurchaseItemId { get; set; } = Guid.NewGuid(); public Guid PurchaseInvoiceId { get; set; } public Guid ProductId { get; set; } public string? Barcode { get; set; } public string? BatchNo { get; set; } public DateOnly? ExpiryDate { get; set; } public decimal Quantity { get; set; } public decimal FreeQuantity { get; set; } public decimal ReturnedQuantity { get; set; } public decimal PurchasePrice { get; set; } public decimal MRP { get; set; } public decimal SellingPrice { get; set; } public decimal DiscountPercentage { get; set; } public decimal DiscountAmount { get; set; } public decimal GSTPercentage { get; set; } public decimal GSTAmount { get; set; } public decimal AllocatedExpense { get; set; } public decimal LineTotal { get; set; } public Product Product { get; set; } = null!; }
public sealed class PurchasePayment { public Guid PurchasePaymentId { get; set; } = Guid.NewGuid(); public Guid PurchaseInvoiceId { get; set; } public Guid PaymentMethodId { get; set; } public decimal Amount { get; set; } public string? ReferenceNumber { get; set; } public DateTimeOffset PaymentDate { get; set; } public string Status { get; set; } = ""; public string? CreatedBy { get; set; } public PaymentMethod PaymentMethod { get; set; } = null!; }
public sealed class PurchaseExpense { public Guid PurchaseExpenseId { get; set; } = Guid.NewGuid(); public Guid PurchaseInvoiceId { get; set; } public string ExpenseType { get; set; } = ""; public string? Description { get; set; } public decimal Amount { get; set; } public bool IsTaxable { get; set; } }
public sealed class PurchaseReturn { public Guid PurchaseReturnId { get; set; } public string ReturnNumber { get; set; } = ""; public Guid PurchaseInvoiceId { get; set; } public Guid PurchaseItemId { get; set; } public decimal Quantity { get; set; } public decimal AdjustmentAmount { get; set; } public string Reason { get; set; } = ""; public DateTimeOffset ReturnDate { get; set; } }
public sealed class PurchaseAttachment { public Guid PurchaseAttachmentId { get; set; } public Guid PurchaseInvoiceId { get; set; } public string FileName { get; set; } = ""; public string ContentType { get; set; } = ""; public byte[] FileData { get; set; } = []; public DateTimeOffset UploadedOn { get; set; } public string? UploadedBy { get; set; } public bool IsDeleted { get; set; } }
