using FluentValidation;using MediatR;using WhatsBiz.Application.Common.Interfaces;
namespace WhatsBiz.Application.Features.Administration;
public sealed record CompanyDto(Guid CompanyId,string CompanyCode,string CompanyName,string?LegalName,string?GSTIN,string?PAN,string?CIN,string?AddressLine1,string?AddressLine2,string?City,string?State,string?StateCode,string Country,string?PostalCode,string?Email,string?Phone,string?BankName,string?AccountNumber,string?IFSCCode,string?TermsAndConditions,string?InvoiceFooter);
public sealed record CompanyInput(string CompanyCode,string CompanyName,string?LegalName,string?GSTIN,string?PAN,string?CIN,string?AddressLine1,string?AddressLine2,string?City,string?State,string?StateCode,string Country,string?PostalCode,string?Email,string?Phone,string?BankName,string?AccountNumber,string?IFSCCode,string?TermsAndConditions,string?InvoiceFooter);
public sealed record BranchDto(Guid BranchId,string BranchCode,string BranchName,Guid?DefaultWarehouseId,string?Email,string?Phone,string?Address,string?City,string?State,string?PostalCode,bool IsDefault,bool IsActive);public sealed record BranchInput(string BranchCode,string BranchName,Guid?DefaultWarehouseId,string?Email,string?Phone,string?Address,string?City,string?State,string?PostalCode,bool IsDefault=true,bool IsActive=true);
public sealed record SettingDto(string Key,string?Value,string DataType,string Category);public sealed record SettingInput(string Key,string?Value,string DataType,string Category);
public sealed record FinancialYearDto(Guid Id,string Code,DateOnly StartDate,DateOnly EndDate,string Status,bool IsDefault);public sealed record FinancialYearInput(Guid?Id,string Code,DateOnly StartDate,DateOnly EndDate,string Status,bool IsDefault);
public sealed record BackupDto(Guid Id,string FileName,string FilePath,string BackupType,DateTimeOffset StartedOn,DateTimeOffset?CompletedOn,long?FileSizeBytes,string Status,bool IsVerified,string?ErrorMessage);public sealed record RestoreInput(Guid BackupId,bool Confirm=false,bool ValidationOnly=true);public sealed record RestoreResultDto(Guid Id,string Status,bool ValidationOnly,string Message);
public sealed record AuditDto(long Id,string?UserName,string Action,string?EntityType,string?RequestPath,string?HttpMethod,string?IpAddress,bool Succeeded,DateTimeOffset OccurredOn);public sealed record LoginDto(long Id,string UserName,DateTimeOffset LoginOn,DateTimeOffset?LogoutOn,string?IpAddress,bool Succeeded,string?FailureReason);
public sealed record GetCompany:IRequest<CompanyDto>;public sealed record UpdateCompany(CompanyInput Input):IRequest<CompanyDto>;public sealed record GetBranches:IRequest<IReadOnlyCollection<BranchDto>>;public sealed record CreateBranch(BranchInput Input):IRequest<BranchDto>;public sealed record GetSettings:IRequest<IReadOnlyCollection<SettingDto>>;public sealed record UpdateSettings(IReadOnlyCollection<SettingInput>Input,string?User):IRequest;public sealed record GetFinancialYears:IRequest<IReadOnlyCollection<FinancialYearDto>>;public sealed record SaveFinancialYear(FinancialYearInput Input):IRequest;public sealed record GetBackups:IRequest<IReadOnlyCollection<BackupDto>>;public sealed record CreateBackup(string?User):IRequest<BackupDto>;public sealed record RestoreDatabase(RestoreInput Input,string?User):IRequest<RestoreResultDto>;public sealed record GetAudit(DateTimeOffset?From,DateTimeOffset?To,string?Action,int Take=200):IRequest<IReadOnlyCollection<AuditDto>>;public sealed record GetLoginHistory(DateTimeOffset?From,DateTimeOffset?To,int Take=200):IRequest<IReadOnlyCollection<LoginDto>>;
internal sealed class CompanyValidator:AbstractValidator<UpdateCompany>{public CompanyValidator(){RuleFor(x=>x.Input.CompanyCode).NotEmpty().MaximumLength(30);RuleFor(x=>x.Input.CompanyName).NotEmpty().MaximumLength(200);RuleFor(x=>x.Input.GSTIN).Matches("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$").When(x=>!string.IsNullOrWhiteSpace(x.Input.GSTIN));RuleFor(x=>x.Input.PAN).Matches("^[A-Z]{5}[0-9]{4}[A-Z]$").When(x=>!string.IsNullOrWhiteSpace(x.Input.PAN));RuleFor(x=>x.Input.Email).EmailAddress().When(x=>!string.IsNullOrWhiteSpace(x.Input.Email));}}
internal sealed class BranchValidator:AbstractValidator<CreateBranch>{public BranchValidator(){RuleFor(x=>x.Input.BranchCode).NotEmpty().MaximumLength(30);RuleFor(x=>x.Input.BranchName).NotEmpty().MaximumLength(150);RuleFor(x=>x.Input.Email).EmailAddress().When(x=>!string.IsNullOrWhiteSpace(x.Input.Email));}}
internal sealed class FinancialYearValidator:AbstractValidator<SaveFinancialYear>{public FinancialYearValidator(){RuleFor(x=>x.Input.Code).NotEmpty();RuleFor(x=>x.Input.EndDate).GreaterThan(x=>x.Input.StartDate);RuleFor(x=>x.Input.Status).Must(x=>x is "OPEN" or "CLOSED" or "LOCKED");}}
internal sealed class AdminHandlers(IAdminRepository repo,IDatabaseMaintenanceService maintenance):IRequestHandler<GetCompany,CompanyDto>,IRequestHandler<UpdateCompany,CompanyDto>,IRequestHandler<GetBranches,IReadOnlyCollection<BranchDto>>,IRequestHandler<CreateBranch,BranchDto>,IRequestHandler<GetSettings,IReadOnlyCollection<SettingDto>>,IRequestHandler<UpdateSettings>,IRequestHandler<GetFinancialYears,IReadOnlyCollection<FinancialYearDto>>,IRequestHandler<SaveFinancialYear>,IRequestHandler<GetBackups,IReadOnlyCollection<BackupDto>>,IRequestHandler<CreateBackup,BackupDto>,IRequestHandler<RestoreDatabase,RestoreResultDto>,IRequestHandler<GetAudit,IReadOnlyCollection<AuditDto>>,IRequestHandler<GetLoginHistory,IReadOnlyCollection<LoginDto>>{public Task<CompanyDto>Handle(GetCompany r,CancellationToken t)=>repo.Company(t);public Task<CompanyDto>Handle(UpdateCompany r,CancellationToken t)=>repo.SaveCompany(r.Input,t);public Task<IReadOnlyCollection<BranchDto>>Handle(GetBranches r,CancellationToken t)=>repo.Branches(t);public Task<BranchDto>Handle(CreateBranch r,CancellationToken t)=>repo.CreateBranch(r.Input,t);public Task<IReadOnlyCollection<SettingDto>>Handle(GetSettings r,CancellationToken t)=>repo.Settings(t);public Task Handle(UpdateSettings r,CancellationToken t)=>repo.SaveSettings(r.Input,r.User,t);public Task<IReadOnlyCollection<FinancialYearDto>>Handle(GetFinancialYears r,CancellationToken t)=>repo.FinancialYears(t);public Task Handle(SaveFinancialYear r,CancellationToken t)=>repo.SaveFinancialYear(r.Input,t);public Task<IReadOnlyCollection<BackupDto>>Handle(GetBackups r,CancellationToken t)=>repo.Backups(t);public Task<BackupDto>Handle(CreateBackup r,CancellationToken t)=>maintenance.Backup(r.User,t);public Task<RestoreResultDto>Handle(RestoreDatabase r,CancellationToken t)=>maintenance.Restore(r.Input,r.User,t);public Task<IReadOnlyCollection<AuditDto>>Handle(GetAudit r,CancellationToken t)=>repo.Audit(r.From,r.To,r.Action,r.Take,t);public Task<IReadOnlyCollection<LoginDto>>Handle(GetLoginHistory r,CancellationToken t)=>repo.LoginHistory(r.From,r.To,r.Take,t);}
