#pragma warning disable CA1725
using System.Data;using Microsoft.Data.SqlClient;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.Caching.Memory;using WhatsBiz.Application.Common.Interfaces;using WhatsBiz.Application.Features.Dashboard;
namespace WhatsBiz.Infrastructure.Persistence;
public sealed class DashboardRepository(ApplicationDbContext db,IMemoryCache cache):IDashboardRepository{private string Cs=>db.Database.GetConnectionString()??throw new InvalidOperationException("Database connection unavailable.");private readonly MemoryCacheEntryOptions options=new(){AbsoluteExpirationRelativeToNow=TimeSpan.FromSeconds(45),SlidingExpiration=TimeSpan.FromSeconds(15),Size=1};private async Task<T>Cached<T>(string key,bool refresh,Func<Task<T>>factory){if(refresh)cache.Remove(key);if(cache.TryGetValue<T>(key,out var found)&&found is not null)return found;var value=await factory();cache.Set(key,value,options);return value;}
public Task<DashboardSummaryDto>Summary(DateTimeOffset f,DateTimeOffset to,bool refresh,CancellationToken t)=>Cached($"dash:summary:{f.Ticks}:{to.Ticks}",refresh,async()=>{await using var r=await Reader("dashboard.Summary_Get",f,to,t);await r.ReadAsync(t);var dto=new DashboardSummaryDto(r.GetDecimal(0),r.GetDecimal(1),r.GetDecimal(2),r.GetDecimal(3),r.GetDecimal(4),r.GetDecimal(5),r.GetDecimal(6),r.GetDecimal(7),[],[]);await r.NextResultAsync(t);var sales=await Documents(r,t);await r.NextResultAsync(t);var purchases=await Documents(r,t);return dto with{RecentSales=sales,RecentPurchases=purchases};});
public Task<SalesAnalyticsDto>Sales(DateTimeOffset f,DateTimeOffset to,bool refresh,CancellationToken t)=>Cached($"dash:sales:{f.Ticks}:{to.Ticks}",refresh,async()=>{await using var r=await Reader("dashboard.Sales_Get",f,to,t);var sets=new List<IReadOnlyCollection<MetricPointDto>>();for(var i=0;i<10;i++){sets.Add(await Points(r,t));if(i<9)await r.NextResultAsync(t);}return new SalesAnalyticsDto(sets[0],sets[1],sets[2],sets[3],sets[4],sets[5],sets[6],sets[7],sets[8],sets[9]);});
public Task<PurchaseAnalyticsDto>Purchase(DateTimeOffset f,DateTimeOffset to,bool refresh,CancellationToken t)=>Cached($"dash:purchase:{f.Ticks}:{to.Ticks}",refresh,async()=>{await using var r=await Reader("dashboard.Purchase_Get",f,to,t);var daily=await Points(r,t);await r.NextResultAsync(t);var monthly=await Points(r,t);await r.NextResultAsync(t);return new PurchaseAnalyticsDto(daily,monthly,await Points(r,t));});
public Task<InventoryAnalyticsDto>Inventory(bool refresh,CancellationToken t)=>Cached("dash:inventory",refresh,async()=>{await using var r=await Reader("dashboard.Inventory_Get",null,null,t);await r.ReadAsync(t);var dto=new InventoryAnalyticsDto(r.GetDecimal(0),r.GetInt32(1),r.GetInt32(2),r.GetInt32(3),r.GetInt32(4),r.GetInt32(5),r.GetInt32(6),[]);await r.NextResultAsync(t);return dto with{AttentionItems=await Points(r,t)};});
public Task<CustomerAnalyticsDto>Customers(DateTimeOffset f,DateTimeOffset to,bool refresh,CancellationToken t)=>Cached($"dash:customers:{f.Ticks}:{to.Ticks}",refresh,async()=>{await using var r=await Reader("dashboard.Customers_Get",f,to,t);await r.ReadAsync(t);var dto=new CustomerAnalyticsDto(r.GetInt32(0),r.GetDecimal(1),r.GetInt32(2),[]);await r.NextResultAsync(t);return dto with{TopCustomers=await Points(r,t)};});
public Task<SupplierAnalyticsDto>Suppliers(DateTimeOffset f,DateTimeOffset to,bool refresh,CancellationToken t)=>Cached($"dash:suppliers:{f.Ticks}:{to.Ticks}",refresh,async()=>{await using var r=await Reader("dashboard.Suppliers_Get",f,to,t);await r.ReadAsync(t);var dto=new SupplierAnalyticsDto(r.GetDecimal(0),r.GetInt32(1),[]);await r.NextResultAsync(t);return dto with{TopSuppliers=await Points(r,t)};});
public Task<FinanceAnalyticsDto>Finance(DateTimeOffset f,DateTimeOffset to,bool refresh,CancellationToken t)=>Cached($"dash:finance:{f.Ticks}:{to.Ticks}",refresh,async()=>{await using var r=await Reader("dashboard.Finance_Get",f,to,t);await r.ReadAsync(t);return new FinanceAnalyticsDto(r.GetDecimal(0),r.GetDecimal(1),r.GetDecimal(2),r.GetDecimal(3),r.GetDecimal(4));});
public Task<IReadOnlyCollection<DashboardNotificationDto>>Notifications(bool refresh,CancellationToken t)=>Cached<IReadOnlyCollection<DashboardNotificationDto>>("dash:notifications",refresh,async()=>{await using var r=await Reader("dashboard.Notifications_Get",null,null,t);var rows=new List<DashboardNotificationDto>();while(await r.ReadAsync(t))rows.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetGuid(6),r.GetBoolean(7),r.GetFieldValue<DateTimeOffset>(8)));return rows;});
private async Task<SqlDataReader>Reader(string procedure,DateTimeOffset? from,DateTimeOffset? to,CancellationToken t){var c=new SqlConnection(Cs);await c.OpenAsync(t);var q=c.CreateCommand();q.CommandText=procedure;q.CommandType=CommandType.StoredProcedure;q.CommandTimeout=15;if(from.HasValue){q.Parameters.AddWithValue("@From",from.Value);q.Parameters.AddWithValue("@To",to!.Value);}return await q.ExecuteReaderAsync(CommandBehavior.CloseConnection,t);}private static async Task<IReadOnlyCollection<MetricPointDto>>Points(SqlDataReader r,CancellationToken t){var x=new List<MetricPointDto>();while(await r.ReadAsync(t))x.Add(new(r.GetString(0),r.GetDecimal(1)));return x;}private static async Task<IReadOnlyCollection<RecentDocumentDto>>Documents(SqlDataReader r,CancellationToken t){var x=new List<RecentDocumentDto>();while(await r.ReadAsync(t))x.Add(new(r.GetGuid(0),r.GetString(1),r.GetFieldValue<DateTimeOffset>(2),r.GetDecimal(3),r.GetString(4)));return x;}}
