#pragma warning disable CA1725
using System.Data;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using WhatsBiz.Application.Common.Exceptions;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Features.Inventory;
namespace WhatsBiz.Infrastructure.Persistence;
public sealed class InventoryOperationsRepository(ApplicationDbContext db, SqlIdempotencyExecutor idempotency, IHttpContextAccessor httpContext) : IInventoryOperationsRepository
{
    public Task<PagedOperations> Adjustments(string? s, Guid? w, DateTimeOffset? f, DateTimeOffset? to, int p, int z, CancellationToken t) => List("inventory.StockAdjustment_List", s, w, f, to, p, z, t); public Task<PagedOperations> Transfers(string? s, Guid? w, DateTimeOffset? f, DateTimeOffset? to, int p, int z, CancellationToken t) => List("inventory.StockTransfer_List", s, w, f, to, p, z, t); public Task<PagedOperations> Verifications(string? s, Guid? w, int p, int z, CancellationToken t) => List("inventory.PhysicalVerification_List", s, w, null, null, p, z, t);
    public Task<OperationDto> CreateAdjustment(StockAdjustmentDocument x, string? u, CancellationToken t) => Post("INVENTORY_ADJUSTMENT", x, u, "inventory.StockAdjustment_Post", [("@WarehouseId", x.WarehouseId), ("@AdjustmentType", x.AdjustmentType), ("@ReasonCode", x.ReasonCode), ("@ApprovalStatus", x.ApprovalStatus), ("@Remarks", x.Remarks), ("@ItemsJson", JsonSerializer.Serialize(x.Items)), ("@CreatedBy", u)], t);
    public Task<OperationDto> CreateTransfer(StockTransferDocument x, string? u, CancellationToken t) => Post("STOCK_TRANSFER", x, u, "inventory.StockTransfer_Post", [("@SourceWarehouseId", x.SourceWarehouseId), ("@DestinationWarehouseId", x.DestinationWarehouseId), ("@TransferDate", x.TransferDate), ("@ApprovalStatus", x.ApprovalStatus), ("@Remarks", x.Remarks), ("@ItemsJson", JsonSerializer.Serialize(x.Items)), ("@CreatedBy", u)], t);
    public Task<OperationDto> CreateVerification(VerificationDocument x, string? u, CancellationToken t) => Post("PHYSICAL_VERIFICATION", x, u, "inventory.PhysicalVerification_Post", [("@WarehouseId", x.WarehouseId), ("@VerificationDate", x.VerificationDate), ("@ApprovalStatus", x.ApprovalStatus), ("@Remarks", x.Remarks), ("@ItemsJson", JsonSerializer.Serialize(x.Items)), ("@CreatedBy", u)], t);
    public Task<IReadOnlyCollection<StockControlRow>> Reorder(Guid? w, Guid? c, Guid? p, string? s, CancellationToken t) => Control("inventory.ReorderSuggestion_List", w, c, p, null, s, t); public Task<IReadOnlyCollection<StockControlRow>> Alerts(Guid? w, Guid? c, Guid? p, string? status, string? s, CancellationToken t) => Control("inventory.InventoryAlert_List", w, c, p, status, s, t);
    public async Task<PagedMovements> Movements(Guid? w, Guid? p, DateTimeOffset? f, DateTimeOffset? to, string? s, int page, int size, CancellationToken token) { await using var c = await Open(token); await using var q = Command(c, "inventory.StockMovementHistory_List", [("@WarehouseId", w), ("@ProductId", p), ("@From", f), ("@To", to), ("@Search", s), ("@PageNumber", page), ("@PageSize", size)]); await using var r = await q.ExecuteReaderAsync(token); var rows = new List<MovementRow>(); while (await r.ReadAsync(token)) rows.Add(new(r.GetGuid(0), r.GetFieldValue<DateTimeOffset>(1), r.GetString(2), r.GetString(3), r.GetGuid(4), r.GetString(5), r.GetString(6), r.GetGuid(7), r.GetString(8), r.IsDBNull(9) ? null : r.GetGuid(9), r.IsDBNull(10) ? null : r.GetGuid(10), r.GetDecimal(11), r.GetDecimal(12), r.IsDBNull(13) ? null : r.GetString(13), r.IsDBNull(14) ? null : r.GetString(14), r.IsDBNull(15) ? null : r.GetString(15))); await r.NextResultAsync(token); var count = await r.ReadAsync(token) ? r.GetInt32(0) : rows.Count; return new(rows, count, page, size); }
    private async Task<PagedOperations> List(string proc, string? s, Guid? w, DateTimeOffset? f, DateTimeOffset? to, int page, int size, CancellationToken token) { await using var c = await Open(token); await using var q = Command(c, proc, [("@Search", s), ("@WarehouseId", w), ("@From", f), ("@To", to), ("@PageNumber", page), ("@PageSize", size)]); await using var r = await q.ExecuteReaderAsync(token); var rows = new List<OperationListItem>(); while (await r.ReadAsync(token)) rows.Add(new(r.GetGuid(0), r.GetString(1), r.GetFieldValue<DateTimeOffset>(2), r.GetString(3), r.GetString(4), r.IsDBNull(5) ? null : r.GetString(5), r.GetDecimal(6), r.GetInt32(7))); await r.NextResultAsync(token); var count = await r.ReadAsync(token) ? r.GetInt32(0) : rows.Count; return new(rows, count, page, size); }
    private async Task<IReadOnlyCollection<StockControlRow>> Control(string proc, Guid? w, Guid? cat, Guid? product, string? status, string? search, CancellationToken token) { await using var c = await Open(token); var args = new List<(string, object?)> { ("@WarehouseId", w), ("@CategoryId", cat), ("@ProductId", product), ("@Search", search) }; if (proc.Contains("Alert")) args.Add(("@Status", status)); await using var q = Command(c, proc, args); await using var r = await q.ExecuteReaderAsync(token); var rows = new List<StockControlRow>(); while (await r.ReadAsync(token)) rows.Add(new(r.GetGuid(0), r.GetGuid(1), r.GetString(2), r.GetString(3), r.GetGuid(4), r.GetString(5), r.GetString(6), r.GetDecimal(7), r.GetDecimal(8), r.GetFieldValue<DateTimeOffset>(9), r.GetString(10), r.IsDBNull(11) ? null : r.GetString(11))); return rows; }
    private async Task<OperationDto> Post(string operation, object request, string? user, string proc, IReadOnlyCollection<(string, object?)> args, CancellationToken token) { try { return await idempotency.Execute(IdempotencyKeyReader.Read(httpContext), operation, request, user, async (c, tx, ct) => { await using var q = Command(c, proc, args, tx); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new InvalidOperationException("Inventory operation returned no result."); return new OperationDto(r.GetGuid(0), r.GetGuid(1), r.GetString(2)); }, token); } catch (SqlException ex) when (ex.Number >= 51000) { throw new BusinessRuleException(ex.Message); } }
    private async Task<SqlConnection> Open(CancellationToken t) { var c = (SqlConnection)db.Database.GetDbConnection(); if (c.State != ConnectionState.Open) await c.OpenAsync(t); return c; }
    private static SqlCommand Command(SqlConnection c, string name, IEnumerable<(string Name, object? Value)> args, SqlTransaction? transaction = null) { var q = c.CreateCommand(); q.Transaction = transaction; q.CommandText = name; q.CommandType = CommandType.StoredProcedure; foreach (var (x, v) in args) q.Parameters.AddWithValue(x, v ?? DBNull.Value); return q; }
}
