#pragma warning disable CA1725,CA1861
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Domain.Customers;
using WhatsBiz.Domain.POS;
using WhatsBiz.Domain.Products;
namespace WhatsBiz.Infrastructure.Persistence;
public sealed class POSRepository(ApplicationDbContext db, ICurrentUserService currentUser) : IPOSRepository
{
    private IQueryable<Customer> TenantCustomers => currentUser.TenantId is Guid tenant ? db.Customers.Where(x => x.TenantId == tenant) : db.Customers.Where(_ => false);
    public async Task<IReadOnlyDictionary<Guid,string>> SourceChannels(IReadOnlyCollection<Guid> invoiceIds, CancellationToken token) { if (invoiceIds.Count == 0) return new Dictionary<Guid,string>(); var connection=(SqlConnection)db.Database.GetDbConnection(); var opened=connection.State!=System.Data.ConnectionState.Open; if(opened)await connection.OpenAsync(token); try { await using var command=connection.CreateCommand(); var names=invoiceIds.Select((id,index)=>{var name=$"@p{index}";command.Parameters.AddWithValue(name,id);return name;}); command.CommandText=$"SELECT InvoiceId,SourceChannel FROM integration.WhatsAppCommerceOrders WHERE InvoiceId IN ({string.Join(',',names)});"; var result=new Dictionary<Guid,string>(); await using var reader=await command.ExecuteReaderAsync(token); while(await reader.ReadAsync(token))result[reader.GetGuid(0)]=reader.GetString(1); return result; } finally { if(opened)await connection.CloseAsync(); } }
    public async Task<IReadOnlyCollection<Product>> Products(string? search, string? barcode, int size, CancellationToken token) { var q=db.Products.AsNoTracking().Where(x=>x.IsActive&&!x.IsDeleted); if(!string.IsNullOrWhiteSpace(barcode))q=q.Where(x=>x.Barcode==barcode); else if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.ProductCode.Contains(search)||x.ProductName.Contains(search)||(x.Barcode!=null&&x.Barcode.Contains(search))); return await q.OrderBy(x=>x.ProductName).Take(Math.Clamp(size,1,100)).ToArrayAsync(token); }
    public async Task<IReadOnlyCollection<Customer>> Customers(string? search, int size, CancellationToken token) { var q=TenantCustomers.AsNoTracking().Where(x=>x.IsActive&&!x.IsDeleted); if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.CustomerCode.Contains(search)||x.CustomerName.Contains(search)||(x.Mobile!=null&&x.Mobile.Contains(search))); return await q.OrderBy(x=>x.CustomerName).Take(Math.Clamp(size,1,100)).ToArrayAsync(token); }
    public Task<SalesInvoice?> Invoice(Guid id, CancellationToken token) => db.SalesInvoices.AsNoTracking().Include(x=>x.Customer).Where(x=>x.Customer == null || TenantCustomers.Any(c=>c.CustomerId==x.CustomerId)).Include(x=>x.Warehouse).Include(x=>x.Items).ThenInclude(x=>x.Product).Include(x=>x.Payments).ThenInclude(x=>x.PaymentMethod).Include(x=>x.Taxes).Include(x=>x.Discounts).SingleOrDefaultAsync(x=>x.InvoiceId==id,token);
    public async Task<(IReadOnlyCollection<SalesInvoice>,int)> Invoices(string? search,string? status,DateTimeOffset? from,DateTimeOffset? toDate,int page,int size,CancellationToken token) { var q=db.SalesInvoices.AsNoTracking().Include(x=>x.Customer).Where(x=>x.Customer==null||TenantCustomers.Any(c=>c.CustomerId==x.CustomerId)); if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.InvoiceNumber.Contains(search)||(x.Customer!=null&&x.Customer.CustomerName.Contains(search))); if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status); if(from.HasValue)q=q.Where(x=>x.InvoiceDate>=from); if(toDate.HasValue)q=q.Where(x=>x.InvoiceDate<=toDate); var count=await q.CountAsync(token); return (await q.OrderByDescending(x=>x.InvoiceDate).Skip((Math.Max(page,1)-1)*Math.Clamp(size,1,200)).Take(Math.Clamp(size,1,200)).ToArrayAsync(token),count); }
    public async Task<IReadOnlyCollection<PaymentMethod>> PaymentMethods(CancellationToken token)=>await db.PaymentMethods.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.DisplayOrder).ToArrayAsync(token);
    public async Task<POSTodaySummary> Today(CancellationToken token) { var today=DateTimeOffset.Now.Date; var tomorrow=today.AddDays(1); var invoices=db.SalesInvoices.AsNoTracking().Where(x=>x.InvoiceDate>=today&&x.InvoiceDate<tomorrow&&new[]{"COMPLETED","PARTIALLY_RETURNED","RETURNED"}.Contains(x.Status)); var gross=await invoices.SumAsync(x=>(decimal?)x.GrandTotal,token)??0; var collections=await invoices.SumAsync(x=>(decimal?)x.PaidAmount,token)??0; var count=await invoices.CountAsync(token); var payments=db.SalesPayments.AsNoTracking().Where(x=>x.PaymentDate>=today&&x.PaymentDate<tomorrow&&x.Status=="COMPLETED"); var cash=await payments.Where(x=>x.PaymentMethod.MethodCode=="CASH").SumAsync(x=>(decimal?)x.Amount,token)??0; var upi=await payments.Where(x=>x.PaymentMethod.MethodCode=="UPI").SumAsync(x=>(decimal?)x.Amount,token)??0; var card=await payments.Where(x=>x.PaymentMethod.MethodCode=="CARD").SumAsync(x=>(decimal?)x.Amount,token)??0; return new(gross,collections,count,cash,upi,card); }
}
