using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Features.Printing;
namespace WhatsBiz.Infrastructure.Persistence;
public sealed class PrintRepository(IConfiguration configuration, ICurrentUserService currentUser) : IPrintRepository
{
    private Guid Tenant => currentUser.TenantId ?? throw new UnauthorizedAccessException("Tenant context is required for printer configuration.");
    private string ConnectionString => configuration.GetConnectionString("DefaultConnection")
        ?? throw new InvalidOperationException("Connection string 'DefaultConnection' is not configured.");
    public async Task<IReadOnlyCollection<PrintTemplateDto>> Templates(string? type, CancellationToken token) { var list = new List<PrintTemplateDto>(); await using var c = new SqlConnection(ConnectionString); await c.OpenAsync(token); await using var q = c.CreateCommand(); q.CommandText = "SELECT d.DocumentTemplateId,d.TemplateCode,d.TemplateName,d.DocumentType,d.PaperType,CONVERT(bit,CASE WHEN EXISTS(SELECT 1 FROM admin.PrinterSettings configured JOIN admin.Companies company ON company.CompanyId=configured.CompanyId WHERE company.TenantId=@tenant AND configured.InvoiceTemplateId IS NOT NULL) THEN CASE WHEN EXISTS(SELECT 1 FROM admin.PrinterSettings selected JOIN admin.Companies company ON company.CompanyId=selected.CompanyId WHERE company.TenantId=@tenant AND selected.InvoiceTemplateId=d.DocumentTemplateId) THEN 1 ELSE 0 END ELSE d.IsDefault END),d.HtmlTemplate FROM printing.DocumentTemplates d WHERE d.IsActive=1 AND (@type IS NULL OR d.DocumentType=@type) ORDER BY d.DocumentType,6 DESC,d.TemplateName"; q.Parameters.AddWithValue("@tenant", Tenant); q.Parameters.AddWithValue("@type", (object?)type ?? DBNull.Value); await using var r = await q.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) list.Add(new(r.GetGuid(0), r.GetString(1), r.GetString(2), r.GetString(3), r.GetString(4), r.GetBoolean(5), r.GetString(6))); return list; }
    public async Task<IReadOnlyCollection<PrinterDto>> Printers(CancellationToken token) { var list = new List<PrinterDto>(); await using var c = new SqlConnection(ConnectionString); await c.OpenAsync(token); await using var q = c.CreateCommand(); q.CommandText = "SELECT PrinterConfigurationId,PrinterName,DisplayName,PrinterType,PaperSize,DocumentType,IsDefault,AutoCut,IsActive FROM printing.PrinterConfigurations WHERE TenantId=@tenant ORDER BY IsDefault DESC,DisplayName"; q.Parameters.AddWithValue("@tenant", Tenant); await using var r = await q.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) list.Add(new(r.GetGuid(0), r.GetString(1), r.GetString(2), r.GetString(3), r.GetString(4), r.IsDBNull(5) ? null : r.GetString(5), r.GetBoolean(6), r.GetBoolean(7), r.GetBoolean(8))); return list; }
    public async Task<string> DefaultPaperSize(CancellationToken token) { await using var c = new SqlConnection(ConnectionString); await c.OpenAsync(token); await using var q = c.CreateCommand(); q.CommandText = "SELECT TOP(1) PaperSize FROM printing.PrinterConfigurations WHERE TenantId=@tenant AND IsActive=1 AND IsDefault=1 ORDER BY CASE WHEN DocumentType='SALES_INVOICE' THEN 0 WHEN DocumentType IS NULL THEN 1 ELSE 2 END,CreatedOn DESC"; q.Parameters.AddWithValue("@tenant", Tenant); var value = await q.ExecuteScalarAsync(token); return PaperSizes.Normalize(value as string ?? configuration["Printing:PaperSize"]); }
    public async Task SavePrinter(PrinterInput x, CancellationToken token) { await using var c = new SqlConnection(ConnectionString); await c.OpenAsync(token); await using var tx = await c.BeginTransactionAsync(token); if (x.IsDefault) { await using var clear = c.CreateCommand(); clear.Transaction = (SqlTransaction)tx; clear.CommandText = "UPDATE printing.PrinterConfigurations SET IsDefault=0 WHERE TenantId=@tenant"; clear.Parameters.AddWithValue("@tenant", Tenant); await clear.ExecuteNonQueryAsync(token); } await using var q = c.CreateCommand(); q.Transaction = (SqlTransaction)tx; q.CommandText = x.Id is null ? "INSERT printing.PrinterConfigurations(PrinterName,DisplayName,PrinterType,PaperSize,DocumentType,IsDefault,AutoCut,IsActive,TenantId) VALUES(@name,@display,@type,@paper,@document,@default,@cut,@active,@tenant)" : "UPDATE printing.PrinterConfigurations SET PrinterName=@name,DisplayName=@display,PrinterType=@type,PaperSize=@paper,DocumentType=@document,IsDefault=@default,AutoCut=@cut,IsActive=@active WHERE PrinterConfigurationId=@id AND TenantId=@tenant"; q.Parameters.AddWithValue("@tenant", Tenant); q.Parameters.AddWithValue("@id", (object?)x.Id ?? DBNull.Value); q.Parameters.AddWithValue("@name", x.PrinterName.Trim()); q.Parameters.AddWithValue("@display", x.DisplayName.Trim()); q.Parameters.AddWithValue("@type", x.PrinterType.Trim().ToUpperInvariant()); q.Parameters.AddWithValue("@paper", PaperSizes.Normalize(x.PaperSize)); q.Parameters.AddWithValue("@document", (object?)x.DocumentType?.Trim().ToUpperInvariant() ?? DBNull.Value); q.Parameters.AddWithValue("@default", x.IsDefault); q.Parameters.AddWithValue("@cut", x.AutoCut); q.Parameters.AddWithValue("@active", x.IsActive); await q.ExecuteNonQueryAsync(token); await tx.CommitAsync(token); }
}
