#pragma warning disable CA1725
using Microsoft.EntityFrameworkCore;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Domain.Purchases;
namespace WhatsBiz.Infrastructure.Persistence;
public sealed class PurchaseRepository(ApplicationDbContext db):IPurchaseRepository
{
    public async Task<(IReadOnlyCollection<PurchaseInvoice>,int)> List(string? search,string? status,Guid? supplierId,DateTimeOffset? from,DateTimeOffset? to,int page,int size,CancellationToken t){var q=db.PurchaseInvoices.AsNoTracking().Include(x=>x.Supplier).Include(x=>x.Warehouse).Where(x=>!x.IsDeleted);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.InvoiceNumber.Contains(search)||(x.SupplierInvoiceNo!=null&&x.SupplierInvoiceNo.Contains(search))||x.Supplier.SupplierName.Contains(search));if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status);if(supplierId.HasValue)q=q.Where(x=>x.SupplierId==supplierId);if(from.HasValue)q=q.Where(x=>x.InvoiceDate>=from);if(to.HasValue)q=q.Where(x=>x.InvoiceDate<=to);var n=await q.CountAsync(t);var take=Math.Clamp(size,1,200);return(await q.OrderByDescending(x=>x.InvoiceDate).Skip((Math.Max(page,1)-1)*take).Take(take).ToArrayAsync(t),n);}
    public Task<PurchaseInvoice?> Get(Guid id,bool tracking,CancellationToken t){var q=db.PurchaseInvoices.Include(x=>x.Supplier).Include(x=>x.Warehouse).Include(x=>x.Items).ThenInclude(x=>x.Product).Include(x=>x.Payments).ThenInclude(x=>x.PaymentMethod).Include(x=>x.Expenses).Where(x=>!x.IsDeleted);if(!tracking)q=q.AsNoTracking();return q.SingleOrDefaultAsync(x=>x.PurchaseInvoiceId==id,t);}
    public async Task<PurchaseDashboardData> Dashboard(CancellationToken t){var now=DateTimeOffset.Now;var today=new DateTimeOffset(now.Date,now.Offset);var tomorrow=today.AddDays(1);var month=new DateTimeOffset(today.Year,today.Month,1,0,0,0,today.Offset);var q=db.PurchaseInvoices.AsNoTracking().Where(x=>!x.IsDeleted&&x.Status!="DRAFT"&&x.Status!="CANCELLED");var grossOutstanding=await q.SumAsync(x=>(decimal?)(x.GrandTotal-x.PaidAmount),t)??0;var credits=await db.PurchaseReturns.AsNoTracking().SumAsync(x=>(decimal?)x.AdjustmentAmount,t)??0;return new(await q.Where(x=>x.InvoiceDate>=today&&x.InvoiceDate<tomorrow).SumAsync(x=>(decimal?)x.GrandTotal,t)??0,await q.CountAsync(x=>x.InvoiceDate>=today&&x.InvoiceDate<tomorrow,t),Math.Max(0,grossOutstanding-credits),await q.Where(x=>x.InvoiceDate>=month).SumAsync(x=>(decimal?)x.GrandTotal,t)??0);}
    public Task Save(CancellationToken t)=>db.SaveChangesAsync(t);
}
