#pragma warning disable CA1725
using System.Data;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using WhatsBiz.Application.Common.Exceptions;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Features.Receivables;
namespace WhatsBiz.Infrastructure.Persistence;
public sealed class ReceivablesRepository(ApplicationDbContext db) : IReceivablesRepository
{
    private string Cs => db.Database.GetConnectionString() ?? throw new InvalidOperationException("Database connection unavailable.");
    public Task<DocumentResultDto> PostReceipt(ReceiptInput x, string? user, CancellationToken t) => Post("finance.Receipt_Post", [("@CustomerId", x.CustomerId), ("@ReceiptType", x.ReceiptType), ("@ReceiptDate", x.ReceiptDate), ("@ReferenceNumber", x.ReferenceNumber), ("@Remarks", x.Remarks), ("@ItemsJson", JsonSerializer.Serialize(x.Items)), ("@AllocationsJson", JsonSerializer.Serialize(x.Allocations)), ("@CreatedBy", user)], t); public Task<DocumentResultDto> PostPayment(PaymentInput x, string? user, CancellationToken t) => Post("finance.Payment_Post", [("@SupplierId", x.SupplierId), ("@PaymentType", x.PaymentType), ("@PaymentDate", x.PaymentDate), ("@ReferenceNumber", x.ReferenceNumber), ("@Remarks", x.Remarks), ("@ItemsJson", JsonSerializer.Serialize(x.Items)), ("@AllocationsJson", JsonSerializer.Serialize(x.Allocations)), ("@CreatedBy", user)], t);
    public async Task<PagedFinancialDocuments> History(string kind, string? search, Guid? partyId, DateTimeOffset? from, DateTimeOffset? toDate, int page, int size, CancellationToken token) { await using var c = new SqlConnection(Cs); await c.OpenAsync(token); await using var q = Cmd(c, "finance.ReceivablePayable_List", [("@Kind", kind), ("@Search", search), ("@PartyId", partyId), ("@From", from), ("@To", toDate), ("@PageNumber", page), ("@PageSize", size)]); await using var r = await q.ExecuteReaderAsync(token); var rows = new List<FinancialDocumentDto>(); while (await r.ReadAsync(token)) rows.Add(new(r.GetGuid(0), r.GetString(1), r.GetFieldValue<DateTimeOffset>(2), r.GetString(3), r.GetString(4), r.GetString(5), r.GetDecimal(6), r.GetDecimal(7), r.GetDecimal(8), r.GetString(9), r.IsDBNull(10) ? null : r.GetString(10), r.IsDBNull(11) ? null : r.GetString(11))); await r.NextResultAsync(token); var count = await r.ReadAsync(token) ? r.GetInt32(0) : rows.Count; return new(rows, count, page, size); }
    public async Task<IReadOnlyCollection<OutstandingDto>> Outstanding(string partyType, Guid? partyId, string? search, string? ageBucket, CancellationToken token) { await using var c = new SqlConnection(Cs); await c.OpenAsync(token); await using var q = Cmd(c, "finance.Outstanding_List", [("@PartyType", partyType), ("@PartyId", partyId), ("@Search", search), ("@AgeBucket", ageBucket), ("@OnlyOpen", true)]); await using var r = await q.ExecuteReaderAsync(token); var rows = new List<OutstandingDto>(); while (await r.ReadAsync(token)) rows.Add(new(r.GetGuid(0), r.GetGuid(1), r.GetString(2), r.GetString(3), r.GetGuid(4), r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.GetFieldValue<DateTimeOffset>(7), r.GetDecimal(8), r.GetDecimal(9), r.GetDecimal(10), r.GetInt32(11), r.GetString(12))); return rows; }
    public async Task<IReadOnlyCollection<FollowUpDto>> FollowUps(Guid? customerId, CancellationToken token) { await using var c = new SqlConnection(Cs); await c.OpenAsync(token); await using var q = Cmd(c, "", []); q.CommandType = CommandType.Text; q.CommandText = "SELECT f.CollectionFollowUpId,f.CustomerId,c.CustomerCode,c.CustomerName,f.InvoiceId,i.InvoiceNumber,f.FollowUpDate,f.NextFollowUpDate,f.PaymentCommitmentDate,f.CommunicationMode,f.Notes,f.Outcome,f.CreatedBy FROM finance.CollectionFollowUp f JOIN sales.Customers c ON c.CustomerId=f.CustomerId LEFT JOIN sales.SalesInvoices i ON i.InvoiceId=f.InvoiceId WHERE(@id IS NULL OR f.CustomerId=@id)ORDER BY f.FollowUpDate DESC"; q.Parameters.AddWithValue("@id", customerId ?? (object)DBNull.Value); await using var r = await q.ExecuteReaderAsync(token); var rows = new List<FollowUpDto>(); while (await r.ReadAsync(token)) rows.Add(new(r.GetGuid(0), r.GetGuid(1), r.GetString(2), r.GetString(3), r.IsDBNull(4) ? null : r.GetGuid(4), r.IsDBNull(5) ? null : r.GetString(5), r.GetFieldValue<DateTimeOffset>(6), r.IsDBNull(7) ? null : r.GetFieldValue<DateTimeOffset>(7), r.IsDBNull(8) ? null : r.GetFieldValue<DateTimeOffset>(8), r.GetString(9), r.IsDBNull(10) ? null : r.GetString(10), r.IsDBNull(11) ? null : r.GetString(11), r.IsDBNull(12) ? null : r.GetString(12))); return rows; }
    public async Task<Guid> SaveFollowUp(FollowUpInput x, string? user, CancellationToken token) { await using var c = new SqlConnection(Cs); await c.OpenAsync(token); await using var q = c.CreateCommand(); q.CommandText = "DECLARE @id uniqueidentifier=NEWID();INSERT finance.CollectionFollowUp(CollectionFollowUpId,CustomerId,InvoiceId,FollowUpDate,NextFollowUpDate,PaymentCommitmentDate,CommunicationMode,Notes,Outcome,CreatedBy)VALUES(@id,@customer,@invoice,@date,@next,@commitment,@mode,@notes,@outcome,@user);SELECT @id"; foreach (var p in new[] { ("@customer", (object?)x.CustomerId), ("@invoice", x.InvoiceId), ("@date", x.FollowUpDate), ("@next", x.NextFollowUpDate), ("@commitment", x.PaymentCommitmentDate), ("@mode", x.CommunicationMode), ("@notes", x.Notes), ("@outcome", x.Outcome), ("@user", user) }) q.Parameters.AddWithValue(p.Item1, p.Item2 ?? DBNull.Value); return (Guid)(await q.ExecuteScalarAsync(token) ?? throw new InvalidOperationException("Follow-up was not created.")); }
    private async Task<DocumentResultDto> Post(string proc, IEnumerable<(string, object?)> args, CancellationToken token) { await using var c = new SqlConnection(Cs); await c.OpenAsync(token); await using var q = Cmd(c, proc, args); try { await using var r = await q.ExecuteReaderAsync(token); if (!await r.ReadAsync(token)) throw new InvalidOperationException("Posting returned no result."); return new(r.GetGuid(0), r.GetString(1), r.GetDecimal(2), r.GetDecimal(3)); } catch (SqlException ex) when (ex.Number >= 51300) { throw new BusinessRuleException(ex.Message); } }
    private static SqlCommand Cmd(SqlConnection c, string proc, IEnumerable<(string Name, object? Value)> args) { var q = c.CreateCommand(); q.CommandText = proc; q.CommandType = CommandType.StoredProcedure; foreach (var (x, v) in args) q.Parameters.AddWithValue(x, v ?? DBNull.Value); return q; }
}
