using MediatR;
using Microsoft.AspNetCore.Mvc;
using WhatsBiz.Api.Authorization;
using WhatsBiz.Application.Features.Inventory;
using WhatsBiz.SharedKernel;
namespace WhatsBiz.Api.Controllers; [ApiController, Route("api/inventory")]
public sealed class InventoryOperationsController(ISender sender) : ControllerBase
{
    [HttpGet("adjustments"), HasPermission(Permissions.Inventory.Adjust)] public Task<PagedOperations> A([FromQuery] string? search, [FromQuery] Guid? warehouseId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 20, CancellationToken token = default) => sender.Send(new GetAdjustments(search, warehouseId, from, to, pageNumber, pageSize), token); [HttpPost("adjustments"), HasPermission(Permissions.Inventory.Adjust)] public Task<OperationDto> A(StockAdjustmentDocument input, CancellationToken token) => sender.Send(new CreateAdjustment(input), token);
    [HttpGet("transfers"), HasPermission(Permissions.Inventory.Transfer)] public Task<PagedOperations> T([FromQuery] string? search, [FromQuery] Guid? warehouseId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 20, CancellationToken token = default) => sender.Send(new GetTransfers(search, warehouseId, from, to, pageNumber, pageSize), token); [HttpPost("transfers"), HasPermission(Permissions.Inventory.Transfer)] public Task<OperationDto> T(StockTransferDocument input, CancellationToken token) => sender.Send(new CreateTransfer(input), token);
    [HttpGet("verification"), HasPermission(Permissions.Inventory.Verify)] public Task<PagedOperations> V([FromQuery] string? search, [FromQuery] Guid? warehouseId, [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 20, CancellationToken token = default) => sender.Send(new GetVerifications(search, warehouseId, pageNumber, pageSize), token); [HttpPost("verification"), HasPermission(Permissions.Inventory.Verify)] public Task<OperationDto> V(VerificationDocument input, CancellationToken token) => sender.Send(new CreateVerification(input), token);
    [HttpGet("reorder"), HasPermission(Permissions.Inventory.Reorder)] public Task<IReadOnlyCollection<StockControlRow>> R([FromQuery] Guid? warehouseId, [FromQuery] Guid? categoryId, [FromQuery] Guid? productId, [FromQuery] string? search, CancellationToken token) => sender.Send(new GetReorder(warehouseId, categoryId, productId, search), token); [HttpGet("alerts"), HasPermission(Permissions.Inventory.Alerts)] public Task<IReadOnlyCollection<StockControlRow>> Alerts([FromQuery] Guid? warehouseId, [FromQuery] Guid? categoryId, [FromQuery] Guid? productId, [FromQuery] string? status, [FromQuery] string? search, CancellationToken token) => sender.Send(new GetAlerts(warehouseId, categoryId, productId, status, search), token);
    [HttpGet("movement-history"), HasPermission(Permissions.Inventory.View)] public Task<PagedMovements> M([FromQuery] Guid? warehouseId, [FromQuery] Guid? productId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? search, [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 20, CancellationToken token = default) => sender.Send(new GetMovementHistory(warehouseId, productId, from, to, search, pageNumber, pageSize), token);
}
