using MediatR;
using Microsoft.AspNetCore.Mvc;
using WhatsBiz.Api.Authorization;
using WhatsBiz.Application.Features.Receivables;
using WhatsBiz.SharedKernel;
namespace WhatsBiz.Api.Controllers; [ApiController]
public sealed class ReceivablesController(ISender sender) : ControllerBase
{
    [HttpGet("api/receipts"), HasPermission(Permissions.Finance.ReceiptView)] public Task<PagedFinancialDocuments> Receipts([FromQuery] string? search, [FromQuery] Guid? customerId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 20, CancellationToken token = default) => sender.Send(new GetReceipts(search, customerId, from, to, pageNumber, pageSize), token); [HttpPost("api/receipts"), HasPermission(Permissions.Finance.ReceiptCreate)] public Task<DocumentResultDto> Receipt(ReceiptInput input, CancellationToken token) => sender.Send(new PostReceipt(input), token);
    [HttpGet("api/payments"), HasPermission(Permissions.Finance.PaymentView)] public Task<PagedFinancialDocuments> Payments([FromQuery] string? search, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 20, CancellationToken token = default) => sender.Send(new GetPayments(search, supplierId, from, to, pageNumber, pageSize), token); [HttpPost("api/payments"), HasPermission(Permissions.Finance.PaymentCreate)] public Task<DocumentResultDto> Payment(PaymentInput input, CancellationToken token) => sender.Send(new PostPayment(input), token);
    [HttpGet("api/customer-outstanding"), HasPermission(Permissions.Finance.CustomerOutstandingView)] public Task<IReadOnlyCollection<OutstandingDto>> CustomerOutstanding([FromQuery] Guid? customerId, [FromQuery] string? search, CancellationToken token) => sender.Send(new GetOutstanding("CUSTOMER", customerId, search, null), token); [HttpGet("api/supplier-outstanding"), HasPermission(Permissions.Finance.SupplierOutstandingView)] public Task<IReadOnlyCollection<OutstandingDto>> SupplierOutstanding([FromQuery] Guid? supplierId, [FromQuery] string? search, CancellationToken token) => sender.Send(new GetOutstanding("SUPPLIER", supplierId, search, null), token);
    [HttpGet("api/customer-ageing"), HasPermission(Permissions.Finance.CustomerOutstandingView)] public Task<IReadOnlyCollection<OutstandingDto>> CustomerAgeing([FromQuery] Guid? customerId, [FromQuery] string? ageBucket, [FromQuery] string? search, CancellationToken token) => sender.Send(new GetOutstanding("CUSTOMER", customerId, search, ageBucket), token); [HttpGet("api/supplier-ageing"), HasPermission(Permissions.Finance.SupplierOutstandingView)] public Task<IReadOnlyCollection<OutstandingDto>> SupplierAgeing([FromQuery] Guid? supplierId, [FromQuery] string? ageBucket, [FromQuery] string? search, CancellationToken token) => sender.Send(new GetOutstanding("SUPPLIER", supplierId, search, ageBucket), token);
    [HttpGet("api/collection-followup"), HasPermission(Permissions.Finance.CustomerOutstandingView)] public Task<IReadOnlyCollection<FollowUpDto>> FollowUps([FromQuery] Guid? customerId, CancellationToken token) => sender.Send(new GetFollowUps(customerId), token); [HttpPost("api/collection-followup"), HasPermission(Permissions.Finance.ReceiptCreate)] public Task<Guid> FollowUp(FollowUpInput input, CancellationToken token) => sender.Send(new SaveFollowUp(input), token);
}
