using AutoMapper;
using MediatR;
using WhatsBiz.Application.Common.Exceptions;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Features.Products.DTOs;
using WhatsBiz.Domain.Products;

namespace WhatsBiz.Application.Features.Products.MasterData;

public sealed class GetProductCategoriesQueryHandler(IProductRepository repository) : IRequestHandler<GetProductCategoriesQuery, IReadOnlyCollection<ProductCategoryDto>>
{
    public async Task<IReadOnlyCollection<ProductCategoryDto>> Handle(GetProductCategoriesQuery request, CancellationToken cancellationToken) { var items = await repository.GetCategoriesAsync(cancellationToken); var filtered = items.Where(x => (!request.IsActive.HasValue || x.IsActive == request.IsActive) && (string.IsNullOrWhiteSpace(request.Search) || x.CategoryCode.Contains(request.Search, StringComparison.OrdinalIgnoreCase) || x.CategoryName.Contains(request.Search, StringComparison.OrdinalIgnoreCase))).ToArray(); return BuildTree(filtered, null); }
    private static ProductCategoryDto[] BuildTree(IReadOnlyCollection<ProductCategory> categories, Guid? parentId) => categories.Where(x => x.ParentCategoryId == parentId).OrderBy(x => x.DisplayOrder).ThenBy(x => x.CategoryName).Select(x => new ProductCategoryDto(x.ProductCategoryId, x.CategoryCode, x.CategoryName, x.Description, x.DisplayOrder, x.ParentCategoryId, x.IsActive, BuildTree(categories, x.ProductCategoryId))).ToArray();
}
public sealed class CreateProductCategoryCommandHandler(IProductRepository repository, ICurrentUserService currentUser) : IRequestHandler<CreateProductCategoryCommand, ProductCategoryDto>
{
    public async Task<ProductCategoryDto> Handle(CreateProductCategoryCommand request, CancellationToken cancellationToken)
    {
        var item = new ProductCategory();
        var code = MasterDataCode.Resolve(request.Input.CategoryCode, "CAT", item.ProductCategoryId);
        if (await repository.CategoryCodeExistsAsync(code, null, cancellationToken)) throw new BusinessRuleException("Category code already exists.");
        if (request.Input.ParentCategoryId.HasValue && await repository.GetCategoryAsync(request.Input.ParentCategoryId.Value, false, cancellationToken) is null) throw new BusinessRuleException("Parent category was not found.");
        item.CategoryCode = code; item.CategoryName = request.Input.CategoryName.Trim(); item.Description = request.Input.Description?.Trim(); item.DisplayOrder = request.Input.DisplayOrder; item.ParentCategoryId = request.Input.ParentCategoryId; item.IsActive = request.Input.IsActive; item.CreatedBy = currentUser.Username;
        repository.Add(item); await repository.SaveChangesAsync(cancellationToken); return Map(item);
    }
    internal static ProductCategoryDto Map(ProductCategory x) => new(x.ProductCategoryId, x.CategoryCode, x.CategoryName, x.Description, x.DisplayOrder, x.ParentCategoryId, x.IsActive, []);
}
public sealed class UpdateProductCategoryCommandHandler(IProductRepository repository, ICurrentUserService currentUser) : IRequestHandler<UpdateProductCategoryCommand, ProductCategoryDto> { public async Task<ProductCategoryDto> Handle(UpdateProductCategoryCommand request, CancellationToken cancellationToken) { var item = await repository.GetCategoryAsync(request.Id, true, cancellationToken) ?? throw new EntityNotFoundException("Category was not found."); var code = MasterDataCode.PreserveOrUse(request.Input.CategoryCode, item.CategoryCode); if (await repository.CategoryCodeExistsAsync(code, request.Id, cancellationToken)) throw new BusinessRuleException("Category code already exists."); if (request.Input.ParentCategoryId.HasValue && await repository.GetCategoryAsync(request.Input.ParentCategoryId.Value, false, cancellationToken) is null) throw new BusinessRuleException("Parent category was not found."); item.CategoryCode = code; item.CategoryName = request.Input.CategoryName.Trim(); item.Description = request.Input.Description?.Trim(); item.DisplayOrder = request.Input.DisplayOrder; item.ParentCategoryId = request.Input.ParentCategoryId; item.IsActive = request.Input.IsActive; item.ModifiedOn = DateTimeOffset.UtcNow; item.ModifiedBy = currentUser.Username; await repository.SaveChangesAsync(cancellationToken); return CreateProductCategoryCommandHandler.Map(item); } }
public sealed class DeleteProductCategoryCommandHandler(IProductRepository repository, ICurrentUserService currentUser) : IRequestHandler<DeleteProductCategoryCommand> { public async Task Handle(DeleteProductCategoryCommand request, CancellationToken cancellationToken) { var item = await repository.GetCategoryAsync(request.Id, true, cancellationToken) ?? throw new EntityNotFoundException("Category was not found."); if (await repository.CategoryHasChildrenOrProductsAsync(request.Id, cancellationToken)) throw new BusinessRuleException("Category cannot be deleted while it has child categories or products."); SoftDelete(item, currentUser.Username); await repository.SaveChangesAsync(cancellationToken); } private static void SoftDelete(ProductMasterEntity item, string? user) { item.IsDeleted = true; item.IsActive = false; item.ModifiedOn = DateTimeOffset.UtcNow; item.ModifiedBy = user; } }

public sealed class GetBrandsQueryHandler(IProductRepository repository, IMapper mapper) : IRequestHandler<GetBrandsQuery, IReadOnlyCollection<BrandDto>> { public async Task<IReadOnlyCollection<BrandDto>> Handle(GetBrandsQuery request, CancellationToken cancellationToken) { var items = await repository.GetBrandsAsync(cancellationToken); return mapper.Map<IReadOnlyCollection<BrandDto>>(items.Where(x => (!request.IsActive.HasValue || x.IsActive == request.IsActive) && (string.IsNullOrWhiteSpace(request.Search) || x.BrandCode.Contains(request.Search, StringComparison.OrdinalIgnoreCase) || x.BrandName.Contains(request.Search, StringComparison.OrdinalIgnoreCase)))); } }
public sealed class CreateBrandCommandHandler(IProductRepository repository, ICurrentUserService currentUser, IMapper mapper) : IRequestHandler<CreateBrandCommand, BrandDto> { public async Task<BrandDto> Handle(CreateBrandCommand request, CancellationToken cancellationToken) { var item = new Brand(); var code = MasterDataCode.Resolve(request.Input.BrandCode, "BR", item.BrandId); if (await repository.BrandCodeExistsAsync(code, null, cancellationToken)) throw new BusinessRuleException("Brand code already exists."); item.BrandCode = code; item.BrandName = request.Input.BrandName.Trim(); item.Description = request.Input.Description?.Trim(); item.Logo = request.Input.Logo?.Trim(); item.IsActive = request.Input.IsActive; item.CreatedBy = currentUser.Username; repository.Add(item); await repository.SaveChangesAsync(cancellationToken); return mapper.Map<BrandDto>(item); } }
public sealed class UpdateBrandCommandHandler(IProductRepository repository, ICurrentUserService currentUser, IMapper mapper) : IRequestHandler<UpdateBrandCommand, BrandDto> { public async Task<BrandDto> Handle(UpdateBrandCommand request, CancellationToken cancellationToken) { var item = await repository.GetBrandAsync(request.Id, true, cancellationToken) ?? throw new EntityNotFoundException("Brand was not found."); var code = MasterDataCode.PreserveOrUse(request.Input.BrandCode, item.BrandCode); if (await repository.BrandCodeExistsAsync(code, request.Id, cancellationToken)) throw new BusinessRuleException("Brand code already exists."); item.BrandCode = code; item.BrandName = request.Input.BrandName.Trim(); item.Description = request.Input.Description?.Trim(); item.Logo = request.Input.Logo?.Trim(); item.IsActive = request.Input.IsActive; item.ModifiedOn = DateTimeOffset.UtcNow; item.ModifiedBy = currentUser.Username; await repository.SaveChangesAsync(cancellationToken); return mapper.Map<BrandDto>(item); } }
public sealed class DeleteBrandCommandHandler(IProductRepository repository, ICurrentUserService currentUser) : IRequestHandler<DeleteBrandCommand> { public async Task Handle(DeleteBrandCommand request, CancellationToken cancellationToken) { var item = await repository.GetBrandAsync(request.Id, true, cancellationToken) ?? throw new EntityNotFoundException("Brand was not found."); if (await repository.BrandHasProductsAsync(request.Id, cancellationToken)) throw new BusinessRuleException("Brand cannot be deleted while it is used by products."); item.IsDeleted = true; item.IsActive = false; item.ModifiedOn = DateTimeOffset.UtcNow; item.ModifiedBy = currentUser.Username; await repository.SaveChangesAsync(cancellationToken); } }

public sealed class GetUnitsOfMeasureQueryHandler(IProductRepository repository, IMapper mapper) : IRequestHandler<GetUnitsOfMeasureQuery, IReadOnlyCollection<UnitOfMeasureDto>> { public async Task<IReadOnlyCollection<UnitOfMeasureDto>> Handle(GetUnitsOfMeasureQuery request, CancellationToken cancellationToken) { var items = await repository.GetUnitsAsync(cancellationToken); return mapper.Map<IReadOnlyCollection<UnitOfMeasureDto>>(items.Where(x => (!request.IsActive.HasValue || x.IsActive == request.IsActive) && (string.IsNullOrWhiteSpace(request.Search) || x.UnitCode.Contains(request.Search, StringComparison.OrdinalIgnoreCase) || x.UnitName.Contains(request.Search, StringComparison.OrdinalIgnoreCase)))); } }
public sealed class CreateUnitOfMeasureCommandHandler(IProductRepository repository, ICurrentUserService currentUser, IMapper mapper) : IRequestHandler<CreateUnitOfMeasureCommand, UnitOfMeasureDto> { public async Task<UnitOfMeasureDto> Handle(CreateUnitOfMeasureCommand request, CancellationToken cancellationToken) { var item = new UnitOfMeasure(); var code = MasterDataCode.Resolve(request.Input.UnitCode, "UOM", item.UnitId); if (await repository.UnitCodeExistsAsync(code, null, cancellationToken)) throw new BusinessRuleException("Unit code already exists."); item.UnitCode = code; item.UnitName = request.Input.UnitName.Trim(); item.ShortName = request.Input.ShortName.Trim(); item.DecimalPlaces = request.Input.DecimalPlaces; item.IsActive = request.Input.IsActive; item.CreatedBy = currentUser.Username; repository.Add(item); await repository.SaveChangesAsync(cancellationToken); return mapper.Map<UnitOfMeasureDto>(item); } }
public sealed class UpdateUnitOfMeasureCommandHandler(IProductRepository repository, ICurrentUserService currentUser, IMapper mapper) : IRequestHandler<UpdateUnitOfMeasureCommand, UnitOfMeasureDto> { public async Task<UnitOfMeasureDto> Handle(UpdateUnitOfMeasureCommand request, CancellationToken cancellationToken) { var item = await repository.GetUnitAsync(request.Id, true, cancellationToken) ?? throw new EntityNotFoundException("Unit was not found."); var code = MasterDataCode.PreserveOrUse(request.Input.UnitCode, item.UnitCode); if (await repository.UnitCodeExistsAsync(code, request.Id, cancellationToken)) throw new BusinessRuleException("Unit code already exists."); item.UnitCode = code; item.UnitName = request.Input.UnitName.Trim(); item.ShortName = request.Input.ShortName.Trim(); item.DecimalPlaces = request.Input.DecimalPlaces; item.IsActive = request.Input.IsActive; item.ModifiedOn = DateTimeOffset.UtcNow; item.ModifiedBy = currentUser.Username; await repository.SaveChangesAsync(cancellationToken); return mapper.Map<UnitOfMeasureDto>(item); } }
public sealed class DeleteUnitOfMeasureCommandHandler(IProductRepository repository, ICurrentUserService currentUser) : IRequestHandler<DeleteUnitOfMeasureCommand> { public async Task Handle(DeleteUnitOfMeasureCommand request, CancellationToken cancellationToken) { var item = await repository.GetUnitAsync(request.Id, true, cancellationToken) ?? throw new EntityNotFoundException("Unit was not found."); if (await repository.UnitHasProductsAsync(request.Id, cancellationToken)) throw new BusinessRuleException("Unit cannot be deleted while it is used by products."); item.IsDeleted = true; item.IsActive = false; item.ModifiedOn = DateTimeOffset.UtcNow; item.ModifiedBy = currentUser.Username; await repository.SaveChangesAsync(cancellationToken); } }

internal static class MasterDataCode
{
    internal static string Resolve(string? requested, string prefix, Guid id) =>
        string.IsNullOrWhiteSpace(requested) ? $"{prefix}-{id:N}" : requested.Trim();

    internal static string PreserveOrUse(string? requested, string existing) =>
        string.IsNullOrWhiteSpace(requested) ? existing : requested.Trim();
}
