namespace WhatsBiz.SharedKernel;

public static class Permissions
{
    public static readonly IReadOnlyCollection<string> All = [Admin.View, Admin.Settings, Admin.Company, Admin.Backup, Admin.Restore, Admin.Audit, Print.View, Print.Document, Print.Barcode, Print.Settings, Product.View, Product.Create, Product.Edit, Product.Delete, Supplier.View, Supplier.Create, Supplier.Edit, Supplier.Delete, Customer.View, Customer.Create, Customer.Edit, Customer.Delete, Customer.RewardsView, Customer.RewardsManage, Warehouse.View, Warehouse.Create, Warehouse.Edit, Warehouse.Delete, Purchase.View, Purchase.Create, Purchase.Edit, Purchase.Delete, Purchase.Return, Purchase.Payment, Purchase.Approve, Inventory.View, Inventory.Adjust, Inventory.Transfer, Inventory.Reserve, Inventory.Verify, Inventory.Reorder, Inventory.Alerts, POS.View, POS.Create, POS.Edit, POS.Return, POS.Void, POS.Discount, Finance.LedgerView, Finance.ReceiptView, Finance.ReceiptCreate, Finance.PaymentView, Finance.PaymentCreate, Finance.CustomerOutstandingView, Finance.SupplierOutstandingView, Finance.CashBookView, Finance.BankBookView, Dashboard.View, Dashboard.Analytics, Gst.View, Gst.Export, Gst.Configuration, Sales.View, Sales.Create, Sales.Approve, Reports.View, Settings.Manage, Users.Manage, Roles.Manage, PermissionsManagement.Manage, Delivery.View, Delivery.Assign, Delivery.Manage, Delivery.UpdateStatus, Delivery.Confirm, Delivery.RecordCod, Delivery.OverrideOtp, Delivery.Settings, Delivery.AgentManage];
    public static class Product { public const string View = "product.view"; public const string Create = "product.create"; public const string Edit = "product.edit"; public const string Delete = "product.delete"; }
    public static class Supplier { public const string View = "supplier.view"; public const string Create = "supplier.create"; public const string Edit = "supplier.edit"; public const string Delete = "supplier.delete"; }
    public static class Customer { public const string View = "customer.view"; public const string Create = "customer.create"; public const string Edit = "customer.edit"; public const string Delete = "customer.delete"; public const string RewardsView = "customer.rewards.view"; public const string RewardsManage = "customer.rewards.manage"; }
    public static class Warehouse { public const string View = "warehouse.view"; public const string Create = "warehouse.create"; public const string Edit = "warehouse.edit"; public const string Delete = "warehouse.delete"; }
    public static class Purchase { public const string View = "purchase.view"; public const string Create = "purchase.create"; public const string Edit = "purchase.edit"; public const string Delete = "purchase.delete"; public const string Return = "purchase.return"; public const string Payment = "purchase.payment"; public const string Approve = "purchase.approve"; }
    public static class Inventory { public const string View = "inventory.view"; public const string Adjust = "inventory.adjust"; public const string Transfer = "inventory.transfer"; public const string Reserve = "inventory.reserve"; public const string Verify = "inventory.verify"; public const string Reorder = "inventory.reorder"; public const string Alerts = "inventory.alerts"; }
    public static class POS { public const string View = "pos.view"; public const string Create = "pos.create"; public const string Edit = "pos.edit"; public const string Return = "pos.return"; public const string Void = "pos.void"; public const string Discount = "pos.discount"; }
    public static class Finance { public const string LedgerView = "ledger.view"; public const string ReceiptView = "receipt.view"; public const string ReceiptCreate = "receipt.create"; public const string PaymentView = "payment.view"; public const string PaymentCreate = "payment.create"; public const string CustomerOutstandingView = "customer.outstanding.view"; public const string SupplierOutstandingView = "supplier.outstanding.view"; public const string CashBookView = "cashbook.view"; public const string BankBookView = "bankbook.view"; }
    public static class Dashboard { public const string View = "dashboard.view"; public const string Analytics = "analytics.view"; }
    public static class Gst { public const string View = "gst.view"; public const string Export = "gst.export"; public const string Configuration = "gst.configuration"; }
    public static class Print { public const string View = "print.view"; public const string Document = "print.document"; public const string Barcode = "print.barcode"; public const string Settings = "print.settings"; }
    public static class Admin { public const string View = "admin.view"; public const string Settings = "admin.settings"; public const string Company = "admin.company"; public const string Backup = "admin.backup"; public const string Restore = "admin.restore"; public const string Audit = "admin.audit"; }
    public static class Sales { public const string View = "sales.view"; public const string Create = "sales.create"; public const string Approve = "sales.approve"; }
    public static class Reports { public const string View = "reports.view"; }
    public static class Settings { public const string Manage = "settings.manage"; }
    public static class Users { public const string Manage = "user.manage"; }
    public static class Roles { public const string Manage = "role.manage"; }
    public static class PermissionsManagement { public const string Manage = "permission.manage"; }
    public static class Features { public const string Manage = "feature.manage"; }
    public static class Delivery { public const string View="delivery.view"; public const string Assign="delivery.assign"; public const string Manage="delivery.manage"; public const string UpdateStatus="delivery.update-status"; public const string Confirm="delivery.confirm"; public const string RecordCod="delivery.record-cod"; public const string OverrideOtp="delivery.override-otp"; public const string Settings="delivery.settings"; public const string AgentManage="delivery.agent-manage"; }
}
