import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, input, output, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatSelectModule } from '@angular/material/select';
import { debounceTime, distinctUntilChanged, Subject } from 'rxjs';
import { ActionToolbarComponent } from '../../components/action-toolbar/action-toolbar.component';
import { DataTableComponent, GridRowAction, GridSort } from '../../components/data-table/data-table.component';
import { FilterPanelComponent } from '../../components/filter-panel/filter-panel.component';
import { PageContainerComponent } from '../../components/page-container/page-container.component';
import { PageHeaderComponent } from '../../components/page-header/page-header.component';
import { SummaryCardComponent } from '../../components/summary-card/summary-card.component';
import { MasterDetailDrawerComponent } from '../master-detail-drawer/master-detail-drawer.component';
import { MasterAction, MasterActionEvent, MasterPageConfig, MasterPageEvent, MasterSortEvent, MasterSummary } from '../master.models';

@Component({selector:'app-master-page',imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatFormFieldModule,MatPaginatorModule,MatSelectModule,ActionToolbarComponent,DataTableComponent,FilterPanelComponent,PageContainerComponent,PageHeaderComponent,SummaryCardComponent,MasterDetailDrawerComponent],template:`
<app-page-container wide><app-page-header eyebrow="Master data" [title]="config().title" [description]="config().description"><a mat-flat-button color="primary" [routerLink]="config().newRoute"><span class="material-symbols-rounded">add</span>New {{config().singular}}</a></app-page-header>
<section class="master-summary" [attr.aria-label]="config().title+' summary'">@for(card of summaries();track card.label){<app-summary-card [label]="card.label" [value]="card.value" [icon]="card.icon" [tone]="card.tone"/>}</section>
<app-action-toolbar sticky><div toolbar-start class="selection-state"><span class="material-symbols-rounded">checklist</span>{{selected().length}} selected</div><a mat-flat-button color="primary" [routerLink]="config().newRoute"><span class="material-symbols-rounded">add</span>New</a><button mat-button [disabled]="selected().length!==1" (click)="emitAction('edit')"><span class="material-symbols-rounded">edit</span>Edit</button><button mat-button class="danger-action" [disabled]="!selected().length" (click)="emitAction('delete')"><span class="material-symbols-rounded">delete</span>Delete</button><button mat-button (click)="emitAction('refresh')"><span class="material-symbols-rounded">refresh</span>Refresh</button>@if(config().importEnabled){<button mat-button (click)="emitAction('import')"><span class="material-symbols-rounded">upload</span>Import</button>}@if(config().exportEnabled){<button mat-button (click)="emitAction('export')"><span class="material-symbols-rounded">download</span>Export</button>}@if(config().printEnabled!==false){<button mat-button (click)="emitAction('print')"><span class="material-symbols-rounded">print</span>Print</button>}<button mat-button [disabled]="!selected().length" (click)="emitAction('bulk')"><span class="material-symbols-rounded">playlist_add_check</span>Bulk actions</button></app-action-toolbar>
<app-filter-panel (apply)="applyFilters()" (reset)="resetFilters()" (save)="savedFilter.emit()" (load)="loadedFilter.emit()"><div class="master-filters"><mat-form-field appearance="outline"><mat-label>Status</mat-label><mat-select [formControl]="statusControl"><mat-option value="all">All records</mat-option><mat-option value="active">Active</mat-option><mat-option value="inactive">Inactive</mat-option></mat-select></mat-form-field><ng-content select="[master-filters]"/></div></app-filter-panel>
<app-data-table [rows]="rows()" [columns]="config().columns" [loading]="loading()" [actions]="rowActions" [emptyTitle]="'No '+config().title.toLowerCase()+' found'" [emptyDescription]="'Adjust the search or filters, or create a new '+config().singular.toLowerCase()+'.'" (selectionChange)="selected.set($event)" (searchChange)="queueSearch($event)" (sortChange)="sortChange.emit($event)" (rowAction)="row($event)" (rowOpen)="drawerRow.set($event)"><a empty-action mat-flat-button color="primary" [routerLink]="config().newRoute"><span class="material-symbols-rounded">add</span>Create New</a></app-data-table>
<mat-paginator [length]="total()" [pageIndex]="pageIndex()" [pageSize]="pageSize()" [pageSizeOptions]="[10,20,50,100]" showFirstLastButtons (page)="page($event)"/></app-page-container>
<app-master-detail-drawer [open]="!!drawerRow()" [title]="drawerTitle()" [record]="drawerRow()" [fields]="config().detailFields" (closed)="drawerRow.set(null)" (edit)="drawerEdit()"/>`,styleUrl:'./master-page.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class MasterPageComponent<T extends object>{
 readonly config=input.required<MasterPageConfig<T>>();readonly rows=input<T[]>([]);readonly total=input(0);readonly loading=input(false);readonly pageIndex=input(0);readonly pageSize=input(20);readonly summaries=input<MasterSummary[]>([]);readonly action=output<MasterActionEvent<T>>();readonly searchChange=output<string>();readonly statusChange=output<'all'|'active'|'inactive'>();readonly pageChange=output<MasterPageEvent>();readonly sortChange=output<MasterSortEvent>();readonly savedFilter=output<void>();readonly loadedFilter=output<void>();readonly selected=signal<T[]>([]);readonly drawerRow=signal<T|null>(null);readonly statusControl=new FormControl<'all'|'active'|'inactive'>('all',{nonNullable:true});readonly rowActions:Array<'view'|'edit'|'delete'|'print'|'duplicate'|'history'>=['view','edit','delete','print','duplicate','history'];readonly drawerTitle=computed(()=>{const row=this.drawerRow();return row?String(row[this.config().rowName]??this.config().singular):this.config().singular});private readonly searches=new Subject<string>();
 constructor(){const destroyRef=inject(DestroyRef);this.searches.pipe(debounceTime(250),distinctUntilChanged(),takeUntilDestroyed(destroyRef)).subscribe(value=>this.searchChange.emit(value))}queueSearch(value:string):void{this.searches.next(value.trim())}applyFilters():void{this.statusChange.emit(this.statusControl.value)}resetFilters():void{this.statusControl.setValue('all');this.statusChange.emit('all')}emitAction(action:MasterAction):void{this.action.emit({action,row:this.selected()[0],rows:this.selected()})}page(event:PageEvent):void{this.pageChange.emit({pageIndex:event.pageIndex,pageSize:event.pageSize})}row(event:GridRowAction<T>):void{if(event.action==='view')this.drawerRow.set(event.row);else this.action.emit({action:event.action,row:event.row,rows:[event.row]})}drawerEdit():void{const row=this.drawerRow();if(row)this.action.emit({action:'edit',row,rows:[row]})}
}
