CREATE PROCEDURE [inventory].[Inventory_Adjust] @ProductId UNIQUEIDENTIFIER,@WarehouseId UNIQUEIDENTIFIER,@ZoneId UNIQUEIDENTIFIER=NULL,@BinId UNIQUEIDENTIFIER=NULL,@BatchNo NVARCHAR(100)=NULL,@SerialNo NVARCHAR(100)=NULL,@Quantity DECIMAL(18,4),@UnitCost DECIMAL(18,4),@AdjustmentType NVARCHAR(10),@ReasonCode NVARCHAR(50),@Remarks NVARCHAR(1000)=NULL,@CreatedBy NVARCHAR(256)=NULL
AS
BEGIN
 SET NOCOUNT ON;SET XACT_ABORT ON;IF @Quantity<=0 THROW 51000,'Quantity must be greater than zero.',1;IF @AdjustmentType NOT IN('INCREASE','DECREASE') THROW 51000,'Invalid adjustment type.',1;
 DECLARE @AllowNegative BIT=(SELECT TOP(1) NegativeStockAllowed FROM inventory.InventorySettings),@BalanceId UNIQUEIDENTIFIER,@OnHand DECIMAL(18,4),@Average DECIMAL(18,4),@TransactionId UNIQUEIDENTIFIER=NEWID(),@AdjustmentId UNIQUEIDENTIFIER=NEWID(),@No NVARCHAR(50)=CONCAT('ADJ-',UPPER(LEFT(REPLACE(CONVERT(NVARCHAR(36),NEWID()),'-',''),20)));
 SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;BEGIN TRAN;
 SELECT @BalanceId=InventoryBalanceId,@OnHand=QuantityOnHand,@Average=AverageCost FROM inventory.InventoryBalances WITH(UPDLOCK,HOLDLOCK) WHERE ProductId=@ProductId AND WarehouseId=@WarehouseId AND ((ZoneId=@ZoneId)OR(ZoneId IS NULL AND @ZoneId IS NULL)) AND ((BinId=@BinId)OR(BinId IS NULL AND @BinId IS NULL)) AND ((BatchNo=@BatchNo)OR(BatchNo IS NULL AND @BatchNo IS NULL)) AND ((SerialNo=@SerialNo)OR(SerialNo IS NULL AND @SerialNo IS NULL));
 IF @BalanceId IS NULL BEGIN SET @BalanceId=NEWID();SET @OnHand=0;SET @Average=0;INSERT inventory.InventoryBalances(InventoryBalanceId,ProductId,WarehouseId,ZoneId,BinId,BatchNo,SerialNo,CreatedBy)VALUES(@BalanceId,@ProductId,@WarehouseId,@ZoneId,@BinId,@BatchNo,@SerialNo,@CreatedBy);END;
 IF @AdjustmentType='DECREASE' AND ISNULL(@AllowNegative,0)=0 AND @OnHand<@Quantity BEGIN ROLLBACK;THROW 51001,'Insufficient stock.',1;END;
 INSERT inventory.InventoryTransactions(TransactionId,TransactionNo,TransactionType,ReferenceType,ReferenceId,WarehouseId,Remarks,CreatedBy)VALUES(@TransactionId,@No,CASE WHEN @AdjustmentType='INCREASE'THEN'ADJUSTMENT_IN'ELSE'ADJUSTMENT_OUT'END,'STOCK_ADJUSTMENT',@AdjustmentId,@WarehouseId,@Remarks,@CreatedBy);
 INSERT inventory.InventoryTransactionDetails(TransactionId,ProductId,BatchNo,SerialNo,Quantity,UnitCost)VALUES(@TransactionId,@ProductId,@BatchNo,@SerialNo,@Quantity,@UnitCost);
 INSERT inventory.StockAdjustments(StockAdjustmentId,TransactionId,AdjustmentNo,AdjustmentType,ReasonCode,ApprovalStatus)VALUES(@AdjustmentId,@TransactionId,@No,@AdjustmentType,@ReasonCode,'PENDING');
 UPDATE inventory.InventoryBalances SET QuantityOnHand=QuantityOnHand+CASE WHEN @AdjustmentType='INCREASE'THEN @Quantity ELSE -@Quantity END,AverageCost=CASE WHEN @AdjustmentType='INCREASE' AND @OnHand+@Quantity>0 THEN ((@OnHand*@Average)+(@Quantity*@UnitCost))/(@OnHand+@Quantity) ELSE AverageCost END,LastPurchaseCost=CASE WHEN @AdjustmentType='INCREASE'THEN @UnitCost ELSE LastPurchaseCost END,LastUpdated=SYSUTCDATETIME(),ModifiedOn=SYSUTCDATETIME(),ModifiedBy=@CreatedBy WHERE InventoryBalanceId=@BalanceId;
 INSERT inventory.InventoryValuation(ProductId,WarehouseId,ValuationMethod,Quantity,UnitCost)SELECT @ProductId,@WarehouseId,ISNULL((SELECT TOP(1)ValuationMethod FROM inventory.InventorySettings),'AVERAGE'),SUM(QuantityOnHand),CASE WHEN SUM(QuantityOnHand)=0 THEN 0 ELSE SUM(QuantityOnHand*AverageCost)/SUM(QuantityOnHand) END FROM inventory.InventoryBalances WHERE ProductId=@ProductId AND WarehouseId=@WarehouseId;
 COMMIT;SELECT @TransactionId TransactionId,@AdjustmentId StockAdjustmentId,@No TransactionNo;
END;
