CREATE PROCEDURE [inventory].[Inventory_Reserve] @Action NVARCHAR(10),@StockReservationId UNIQUEIDENTIFIER=NULL,@ProductId UNIQUEIDENTIFIER=NULL,@WarehouseId UNIQUEIDENTIFIER=NULL,@Quantity DECIMAL(18,4),@ReservationReason NVARCHAR(250)=NULL,@ReferenceType NVARCHAR(50)=NULL,@ReferenceId UNIQUEIDENTIFIER=NULL,@CreatedBy NVARCHAR(256)=NULL
AS
BEGIN
 SET NOCOUNT ON;SET XACT_ABORT ON;IF @Quantity<=0 THROW 51000,'Quantity must be greater than zero.',1;IF @Action NOT IN('RESERVE','RELEASE') THROW 51000,'Invalid reservation action.',1;
 DECLARE @BalanceId UNIQUEIDENTIFIER,@Reserved DECIMAL(18,4),@Available DECIMAL(18,4),@ReservationQuantity DECIMAL(18,4),@Released DECIMAL(18,4),@TransactionId UNIQUEIDENTIFIER=NEWID(),@No NVARCHAR(50)=CONCAT('RSV-',UPPER(LEFT(REPLACE(CONVERT(NVARCHAR(36),NEWID()),'-',''),20)));
 SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;BEGIN TRAN;
 IF @Action='RELEASE' BEGIN SELECT @ProductId=ProductId,@WarehouseId=WarehouseId,@ReservationQuantity=Quantity,@Released=ReleasedQuantity FROM inventory.StockReservations WITH(UPDLOCK,HOLDLOCK) WHERE StockReservationId=@StockReservationId AND Status IN('ACTIVE','PARTIALLY_RELEASED');IF @ProductId IS NULL BEGIN ROLLBACK;THROW 51002,'Active reservation not found.',1;END;IF @Released+@Quantity>@ReservationQuantity BEGIN ROLLBACK;THROW 51002,'Release exceeds reserved quantity.',1;END;END;
 SELECT @BalanceId=InventoryBalanceId,@Reserved=QuantityReserved,@Available=QuantityAvailable FROM inventory.InventoryBalances WITH(UPDLOCK,HOLDLOCK) WHERE ProductId=@ProductId AND WarehouseId=@WarehouseId AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL;
 IF @BalanceId IS NULL OR(@Action='RESERVE' AND @Available<@Quantity)BEGIN ROLLBACK;THROW 51001,'Insufficient available stock.',1;END;IF @Action='RELEASE' AND @Reserved<@Quantity BEGIN ROLLBACK;THROW 51002,'Reserved balance is insufficient.',1;END;
 IF @Action='RESERVE' BEGIN SET @StockReservationId=NEWID();INSERT inventory.StockReservations(StockReservationId,ReservationNo,ProductId,WarehouseId,Quantity,ReservationReason,ReferenceType,ReferenceId,CreatedBy)VALUES(@StockReservationId,@No,@ProductId,@WarehouseId,@Quantity,ISNULL(@ReservationReason,'General reservation'),@ReferenceType,@ReferenceId,@CreatedBy);UPDATE inventory.InventoryBalances SET QuantityReserved=QuantityReserved+@Quantity,LastUpdated=SYSUTCDATETIME(),ModifiedOn=SYSUTCDATETIME(),ModifiedBy=@CreatedBy WHERE InventoryBalanceId=@BalanceId;END
 ELSE BEGIN UPDATE inventory.StockReservations SET ReleasedQuantity=ReleasedQuantity+@Quantity,Status=CASE WHEN ReleasedQuantity+@Quantity=Quantity THEN'RELEASED'ELSE'PARTIALLY_RELEASED'END,ModifiedOn=SYSUTCDATETIME() WHERE StockReservationId=@StockReservationId;UPDATE inventory.InventoryBalances SET QuantityReserved=QuantityReserved-@Quantity,LastUpdated=SYSUTCDATETIME(),ModifiedOn=SYSUTCDATETIME(),ModifiedBy=@CreatedBy WHERE InventoryBalanceId=@BalanceId;END;
 INSERT inventory.InventoryTransactions(TransactionId,TransactionNo,TransactionType,ReferenceType,ReferenceId,WarehouseId,Remarks,CreatedBy)VALUES(@TransactionId,@No,CASE WHEN @Action='RESERVE'THEN'RESERVATION'ELSE'RELEASE'END,'STOCK_RESERVATION',@StockReservationId,@WarehouseId,@ReservationReason,@CreatedBy);INSERT inventory.InventoryTransactionDetails(TransactionId,ProductId,Quantity,UnitCost)VALUES(@TransactionId,@ProductId,@Quantity,0);
 COMMIT;SELECT @StockReservationId StockReservationId,@TransactionId TransactionId,@No ReservationNo;
END;
