using WhatsBiz.Domain.Products;using WhatsBiz.Domain.Warehouses;
namespace WhatsBiz.Domain.Inventory;
public sealed class InventoryBalance{public Guid InventoryBalanceId{get;set;}=Guid.NewGuid();public Guid ProductId{get;set;}public Guid WarehouseId{get;set;}public Guid? ZoneId{get;set;}public Guid? BinId{get;set;}public string? BatchNo{get;set;}public string? SerialNo{get;set;}public decimal QuantityOnHand{get;set;}public decimal QuantityReserved{get;set;}public decimal QuantityAvailable{get;private set;}public decimal AverageCost{get;set;}public decimal LastPurchaseCost{get;set;}public DateTimeOffset LastUpdated{get;set;}public DateTimeOffset CreatedOn{get;set;}public string? CreatedBy{get;set;}public DateTimeOffset? ModifiedOn{get;set;}public string? ModifiedBy{get;set;}public byte[] RowVersion{get;set;}=[];public Product Product{get;set;}=null!;public Warehouse Warehouse{get;set;}=null!;public WarehouseZone? Zone{get;set;}public WarehouseBin? Bin{get;set;}}
public sealed class InventoryTransaction{public Guid TransactionId{get;set;}=Guid.NewGuid();public string TransactionNo{get;set;}="";public DateTimeOffset TransactionDate{get;set;}public string TransactionType{get;set;}="";public string? ReferenceType{get;set;}public Guid? ReferenceId{get;set;}public Guid WarehouseId{get;set;}public string? Remarks{get;set;}public string? CreatedBy{get;set;}public DateTimeOffset CreatedOn{get;set;}public Warehouse Warehouse{get;set;}=null!;public ICollection<InventoryTransactionDetail> Details{get;set;}=[];}
public sealed class InventoryTransactionDetail{public Guid TransactionDetailId{get;set;}=Guid.NewGuid();public Guid TransactionId{get;set;}public Guid ProductId{get;set;}public string? BatchNo{get;set;}public string? SerialNo{get;set;}public decimal Quantity{get;set;}public decimal UnitCost{get;set;}public decimal TotalCost{get;private set;}public Product Product{get;set;}=null!;}
public sealed class StockAdjustment{public Guid StockAdjustmentId{get;set;}public Guid TransactionId{get;set;}public string AdjustmentNo{get;set;}="";public string AdjustmentType{get;set;}="";public string ReasonCode{get;set;}="";public string ApprovalStatus{get;set;}="";public string? ApprovedBy{get;set;}public DateTimeOffset? ApprovedOn{get;set;}public DateTimeOffset CreatedOn{get;set;}}
public sealed class StockTransfer{public Guid StockTransferId{get;set;}public string TransferNo{get;set;}="";public Guid SourceTransactionId{get;set;}public Guid DestinationTransactionId{get;set;}public Guid SourceWarehouseId{get;set;}public Guid DestinationWarehouseId{get;set;}public string ApprovalStatus{get;set;}="";public DateTimeOffset TransferDate{get;set;}public string? Remarks{get;set;}public string? CreatedBy{get;set;}public DateTimeOffset CreatedOn{get;set;}}
public sealed class StockReservation{public Guid StockReservationId{get;set;}public string ReservationNo{get;set;}="";public Guid ProductId{get;set;}public Guid WarehouseId{get;set;}public Guid? ZoneId{get;set;}public Guid? BinId{get;set;}public string? BatchNo{get;set;}public string? SerialNo{get;set;}public decimal Quantity{get;set;}public decimal ReleasedQuantity{get;set;}public string ReservationReason{get;set;}="";public string? ReferenceType{get;set;}public Guid? ReferenceId{get;set;}public string Status{get;set;}="";public string? CreatedBy{get;set;}public DateTimeOffset CreatedOn{get;set;}public DateTimeOffset? ModifiedOn{get;set;}public byte[] RowVersion{get;set;}=[];}
public sealed class InventorySettings{public Guid InventorySettingsId{get;set;}public bool NegativeStockAllowed{get;set;}public bool BatchTrackingEnabled{get;set;}public bool SerialTrackingEnabled{get;set;}public string ValuationMethod{get;set;}="AVERAGE";public DateTimeOffset CreatedOn{get;set;}public DateTimeOffset? ModifiedOn{get;set;}public byte[] RowVersion{get;set;}=[];}
public sealed class InventoryValuation{public Guid InventoryValuationId{get;set;}public Guid ProductId{get;set;}public Guid WarehouseId{get;set;}public string ValuationMethod{get;set;}="";public decimal Quantity{get;set;}public decimal UnitCost{get;set;}public decimal TotalValue{get;private set;}public DateTimeOffset ValuationDate{get;set;}}
