SET NOCOUNT ON;SET XACT_ABORT ON;
DECLARE @Now DATETIMEOFFSET=SYSUTCDATETIME(),@User NVARCHAR(50)='demo-seed';
-- Product master
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-GROC')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-GROC','Grocery & Staples','Demo grocery category',1,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-BEV')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,ParentCategoryId,CreatedOn,CreatedBy,IsActive,IsDeleted)SELECT NEWID(),'DEMO-BEV','Beverages','Demo beverages category',2,ProductCategoryId,@Now,@User,1,0 FROM master.ProductCategories WHERE CategoryCode='DEMO-GROC';
IF NOT EXISTS(SELECT 1 FROM master.Brands WHERE BrandCode='DEMO-FRESH')INSERT master.Brands(BrandId,BrandCode,BrandName,Description,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-FRESH','Fresh Basket','Demo private label',@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-EA')INSERT master.UnitsOfMeasure(UnitId,UnitCode,UnitName,ShortName,DecimalPlaces,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-EA','Each','EA',0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-KG')INSERT master.UnitsOfMeasure(UnitId,UnitCode,UnitName,ShortName,DecimalPlaces,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-KG','Kilogram','KG',3,@Now,@User,1,0);
DECLARE @Grocery UNIQUEIDENTIFIER=(SELECT ProductCategoryId FROM master.ProductCategories WHERE CategoryCode='DEMO-GROC'),@Beverage UNIQUEIDENTIFIER=(SELECT ProductCategoryId FROM master.ProductCategories WHERE CategoryCode='DEMO-BEV'),@Brand UNIQUEIDENTIFIER=(SELECT BrandId FROM master.Brands WHERE BrandCode='DEMO-FRESH'),@Each UNIQUEIDENTIFIER=(SELECT UnitId FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-EA'),@Kg UNIQUEIDENTIFIER=(SELECT UnitId FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-KG');
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-RICE-5KG')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-RICE-5KG','8901000000011','Premium Rice 5 kg','Demo staple product',@Grocery,@Brand,@Each,'1006',5,280,340,360,10,200,25,5,1,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-COLA-1L')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-COLA-1L','8901000000028','Cola Drink 1 L','Demo beverage',@Beverage,@Brand,@Each,'2202',28,45,65,70,12,250,30,1,1,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-SUGAR-1KG')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-SUGAR-1KG','8901000000035','Refined Sugar 1 kg','Demo staple product',@Grocery,@Brand,@Each,'1701',5,38,48,50,15,300,40,1,0,0,@Now,@User,1,0);
DECLARE @Rice UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-RICE-5KG'),@Cola UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-COLA-1L'),@Sugar UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-SUGAR-1KG');
IF NOT EXISTS(SELECT 1 FROM master.ProductBarcodes WHERE Barcode='8901000000110')INSERT master.ProductBarcodes(ProductBarcodeId,ProductId,Barcode,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'8901000000110',0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductPrices WHERE ProductId=@Rice AND PriceType='Retail')INSERT master.ProductPrices(ProductPriceId,ProductId,PriceType,Amount,EffectiveFrom,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'Retail',340,@Now,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductTaxMappings WHERE ProductId=@Rice AND TaxCode='GST5')INSERT master.ProductTaxMappings(ProductTaxMappingId,ProductId,TaxCode,TaxPercentage,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'GST5',5,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductImages WHERE ProductId=@Rice)INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'demo-rice.svg','image/svg+xml',CONVERT(VARBINARY(MAX),N'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="160"><rect width="100%" height="100%" fill="#f5e6b3"/><text x="30" y="85" font-size="24">Premium Rice</text></svg>'),1,@Now,@User,1,0);
-- Suppliers and customers
DECLARE @Net30 UNIQUEIDENTIFIER=(SELECT TOP(1)PaymentTermId FROM purchase.SupplierPaymentTerms WHERE PaymentTermCode='NET30'),@CustNet30 UNIQUEIDENTIFIER=(SELECT TOP(1)PaymentTermId FROM sales.CustomerPaymentTerms WHERE PaymentTermCode='NET30');
IF NOT EXISTS(SELECT 1 FROM purchase.Suppliers WHERE SupplierCode='DEMO-SUP-001')INSERT purchase.Suppliers(SupplierId,SupplierCode,SupplierName,SupplierType,GSTIN,PAN,Email,Mobile,Currency,PaymentTermId,CreditLimit,OpeningBalance,IsGSTRegistered,IsTDSApplicable,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-SUP-001','Maharashtra Wholesale Traders','Distributor','27ABCDE1234F1Z5','ABCDE1234F','orders@demo-wholesale.test','9876501001','INR',@Net30,500000,2500,1,0,'Demo supplier',@User);
IF NOT EXISTS(SELECT 1 FROM purchase.Suppliers WHERE SupplierCode='DEMO-SUP-002')INSERT purchase.Suppliers(SupplierId,SupplierCode,SupplierName,SupplierType,Email,Mobile,Currency,PaymentTermId,CreditLimit,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-SUP-002','Local Beverage Distributors','Distributor','sales@demo-beverage.test','9876501002','INR',@Net30,200000,'Demo supplier',@User);
DECLARE @Supplier UNIQUEIDENTIFIER=(SELECT SupplierId FROM purchase.Suppliers WHERE SupplierCode='DEMO-SUP-001');
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierContacts WHERE SupplierId=@Supplier)INSERT purchase.SupplierContacts(SupplierId,ContactPerson,Designation,Mobile,Email,Department,IsPrimary)VALUES(@Supplier,'Amit Patil','Sales Manager','9876501101','amit@demo-wholesale.test','Sales',1);
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierAddresses WHERE SupplierId=@Supplier)INSERT purchase.SupplierAddresses(SupplierId,AddressType,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Supplier,'Business','Market Yard Road','Pune','Pune','Maharashtra','India','411037');
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierBankAccounts WHERE SupplierId=@Supplier)INSERT purchase.SupplierBankAccounts(SupplierId,BankName,Branch,AccountNumber,IFSCCode,UPIId)VALUES(@Supplier,'State Bank of India','Market Yard','12345678901','SBIN0000456','demowholesale@upi');
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierDocuments WHERE SupplierId=@Supplier)INSERT purchase.SupplierDocuments(SupplierId,DocumentType,FileName,ContentType,DocumentData,UploadedBy)VALUES(@Supplier,'GST Certificate','demo-gst.txt','text/plain',CONVERT(VARBINARY(MAX),'Demo GST certificate'),@User);
IF NOT EXISTS(SELECT 1 FROM sales.Customers WHERE CustomerCode='DEMO-CUST-001')INSERT sales.Customers(CustomerId,CustomerCode,CustomerName,CustomerType,GSTIN,PAN,Email,Mobile,Currency,PaymentTermId,CreditLimit,OpeningBalance,IsGSTRegistered,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-CUST-001','Sunrise Cafe','Business','27AAECS1234F1Z2','AAECS1234F','accounts@sunrise-demo.test','9876502001','INR',@CustNet30,100000,1200,1,'Demo GST customer',@User);
IF NOT EXISTS(SELECT 1 FROM sales.Customers WHERE CustomerCode='DEMO-CUST-002')INSERT sales.Customers(CustomerId,CustomerCode,CustomerName,CustomerType,Email,Mobile,Currency,CreditLimit,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-CUST-002','Rajesh Kumar','Retail','rajesh@customer-demo.test','9876502002','INR',10000,'Demo retail customer',@User);
DECLARE @Customer UNIQUEIDENTIFIER=(SELECT CustomerId FROM sales.Customers WHERE CustomerCode='DEMO-CUST-001');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerContacts WHERE CustomerId=@Customer)INSERT sales.CustomerContacts(CustomerId,ContactPerson,Designation,Department,Mobile,Email,IsPrimary)VALUES(@Customer,'Neha Shah','Owner','Management','9876502101','neha@sunrise-demo.test',1);
IF NOT EXISTS(SELECT 1 FROM sales.CustomerAddresses WHERE CustomerId=@Customer AND AddressType='Billing')INSERT sales.CustomerAddresses(CustomerId,AddressType,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Customer,'Billing','FC Road','Pune','Pune','Maharashtra','India','411004');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerAddresses WHERE CustomerId=@Customer AND AddressType='Shipping')INSERT sales.CustomerAddresses(CustomerId,AddressType,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Customer,'Shipping','JM Road','Pune','Pune','Maharashtra','India','411005');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerBankAccounts WHERE CustomerId=@Customer)INSERT sales.CustomerBankAccounts(CustomerId,BankName,Branch,AccountNumber,IFSCCode,UPIId)VALUES(@Customer,'HDFC Bank','Deccan','50100123456789','HDFC0000123','sunrisecafe@upi');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerDocuments WHERE CustomerId=@Customer)INSERT sales.CustomerDocuments(CustomerId,DocumentType,FileName,ContentType,DocumentData,UploadedBy)VALUES(@Customer,'GST Certificate','demo-customer-gst.txt','text/plain',CONVERT(VARBINARY(MAX),'Demo customer GST certificate'),@User);
-- Warehouses, address, contacts, zones and bins
DECLARE @RetailType UNIQUEIDENTIFIER=(SELECT TOP(1)WarehouseTypeId FROM inventory.WarehouseTypes WHERE TypeCode='RETAIL');IF @RetailType IS NULL SELECT TOP(1)@RetailType=WarehouseTypeId FROM inventory.WarehouseTypes;
IF NOT EXISTS(SELECT 1 FROM inventory.Warehouses WHERE WarehouseCode='DEMO-MAIN')INSERT inventory.Warehouses(WarehouseId,WarehouseCode,WarehouseName,WarehouseTypeId,ManagerName,Email,Mobile,Capacity,IsDefault,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-MAIN','Main Demo Warehouse',@RetailType,'Suresh Jadhav','warehouse@demo.test','9876503001',10000,1,'Primary demo warehouse',@User);
IF NOT EXISTS(SELECT 1 FROM inventory.Warehouses WHERE WarehouseCode='DEMO-STORE')INSERT inventory.Warehouses(WarehouseId,WarehouseCode,WarehouseName,WarehouseTypeId,ManagerName,Email,Mobile,Capacity,IsDefault,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-STORE','Demo Retail Store',@RetailType,'Priya Nair','store@demo.test','9876503002',2000,0,'Demo retail outlet',@User);
DECLARE @Main UNIQUEIDENTIFIER=(SELECT WarehouseId FROM inventory.Warehouses WHERE WarehouseCode='DEMO-MAIN'),@Store UNIQUEIDENTIFIER=(SELECT WarehouseId FROM inventory.Warehouses WHERE WarehouseCode='DEMO-STORE');
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseAddresses WHERE WarehouseId=@Main)BEGIN INSERT inventory.WarehouseAddresses(WarehouseId,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Main,'Warehouse Road, Hadapsar','Pune','Pune','Maharashtra','India','411028');UPDATE inventory.Warehouses SET AddressId=(SELECT AddressId FROM inventory.WarehouseAddresses WHERE WarehouseId=@Main)WHERE WarehouseId=@Main;END;
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseContacts WHERE WarehouseId=@Main)INSERT inventory.WarehouseContacts(WarehouseId,ContactPerson,Designation,Mobile,Email,IsPrimary)VALUES(@Main,'Suresh Jadhav','Warehouse Manager','9876503001','warehouse@demo.test',1);
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseZones WHERE WarehouseId=@Main AND ZoneCode='DEMO-A')INSERT inventory.WarehouseZones(WarehouseId,ZoneCode,ZoneName,Description)VALUES(@Main,'DEMO-A','Ambient Zone','General dry storage');DECLARE @Zone UNIQUEIDENTIFIER=(SELECT ZoneId FROM inventory.WarehouseZones WHERE WarehouseId=@Main AND ZoneCode='DEMO-A');
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseBins WHERE WarehouseId=@Main AND BinCode='DEMO-A-01')INSERT inventory.WarehouseBins(WarehouseId,ZoneId,BinCode,BinName,MaximumCapacity)VALUES(@Main,@Zone,'DEMO-A-01','Ambient Rack 01',500);
-- Purchase receipt creates balances, valuation, inventory ledger, expenses and payment.
DECLARE @PurchaseDue DATETIMEOFFSET=DATEADD(day,30,@Now);
IF NOT EXISTS(SELECT 1 FROM purchase.PurchaseInvoices WHERE SupplierInvoiceNo='DEMO-PUR-001')BEGIN DECLARE @PurchaseItems NVARCHAR(MAX)=CONCAT('[{"ProductId":"',@Rice,'","Barcode":"8901000000011","BatchNo":"RICE-2607","ExpiryDate":"2027-07-31","Quantity":40,"FreeQuantity":2,"PurchasePrice":280,"MRP":360,"SellingPrice":340,"DiscountPercentage":2,"GSTPercentage":5},{"ProductId":"',@Cola,'","Barcode":"8901000000028","BatchNo":"COLA-2608","ExpiryDate":"2027-02-28","Quantity":60,"FreeQuantity":5,"PurchasePrice":45,"MRP":70,"SellingPrice":65,"DiscountPercentage":0,"GSTPercentage":28},{"ProductId":"',@Sugar,'","Barcode":"8901000000035","Quantity":80,"FreeQuantity":0,"PurchasePrice":38,"MRP":50,"SellingPrice":48,"DiscountPercentage":1,"GSTPercentage":5}]');EXEC purchase.Purchase_Post @SupplierId=@Supplier,@SupplierInvoiceNo='DEMO-PUR-001',@InvoiceDate=@Now,@DueDate=@PurchaseDue,@WarehouseId=@Main,@ItemsJson=@PurchaseItems,@ExpensesJson='[{"ExpenseType":"FREIGHT","Description":"Inbound freight","Amount":450,"IsTaxable":false}]',@PaymentsJson='[{"MethodCode":"BANK","Amount":5000,"ReferenceNumber":"DEMO-NEFT-001"}]',@BillDiscount=100,@Remarks='Demo opening purchase',@CreatedBy=@User;END;
DECLARE @Purchase UNIQUEIDENTIFIER=(SELECT PurchaseInvoiceId FROM purchase.PurchaseInvoices WHERE SupplierInvoiceNo='DEMO-PUR-001');IF @Purchase IS NOT NULL AND NOT EXISTS(SELECT 1 FROM purchase.PurchaseAttachments WHERE PurchaseInvoiceId=@Purchase)INSERT purchase.PurchaseAttachments(PurchaseInvoiceId,FileName,ContentType,FileData,UploadedBy)VALUES(@Purchase,'demo-supplier-invoice.txt','text/plain',CONVERT(VARBINARY(MAX),'Demo supplier invoice attachment'),@User);
IF @Purchase IS NOT NULL AND NOT EXISTS(SELECT 1 FROM purchase.PurchaseReturns WHERE PurchaseInvoiceId=@Purchase)BEGIN DECLARE @PurchaseItem UNIQUEIDENTIFIER=(SELECT TOP(1)PurchaseItemId FROM purchase.PurchaseInvoiceItems WHERE PurchaseInvoiceId=@Purchase AND ProductId=@Cola);DECLARE @ReturnJson NVARCHAR(MAX)=CONCAT('[{"PurchaseItemId":"',@PurchaseItem,'","Quantity":2}]');EXEC purchase.Purchase_Return @PurchaseInvoiceId=@Purchase,@ItemsJson=@ReturnJson,@Reason='Two damaged bottles',@CreatedBy=@User;END;
-- Inventory adjustment, transfer and reservation demo rows.
IF NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances WHERE ProductId=@Rice AND WarehouseId=@Main AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL)INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)VALUES(@Rice,@Main,10,280,280,@User);
IF NOT EXISTS(SELECT 1 FROM inventory.StockAdjustments WHERE AdjustmentNo LIKE 'ADJ-%' AND CreatedOn>=DATEADD(year,-20,@Now))EXEC inventory.Inventory_Adjust @ProductId=@Sugar,@WarehouseId=@Main,@Quantity=5,@UnitCost=38,@AdjustmentType='INCREASE',@ReasonCode='OPENING_CORRECTION',@Remarks='Demo stock correction',@CreatedBy=@User;
IF NOT EXISTS(SELECT 1 FROM inventory.StockTransfers WHERE Remarks='Demo replenishment transfer')EXEC inventory.Inventory_Transfer @ProductId=@Rice,@SourceWarehouseId=@Main,@DestinationWarehouseId=@Store,@Quantity=5,@TransferDate=@Now,@Remarks='Demo replenishment transfer',@CreatedBy=@User;
IF NOT EXISTS(SELECT 1 FROM inventory.StockReservations WHERE ReservationReason='Demo customer order')EXEC inventory.Inventory_Reserve @Action='RESERVE',@ProductId=@Sugar,@WarehouseId=@Main,@Quantity=3,@ReservationReason='Demo customer order',@ReferenceType='SALES_ORDER',@CreatedBy=@User;
-- POS counter, shift, sale, payment/tax/discount/cash drawer and partial return.
DECLARE @Series UNIQUEIDENTIFIER=(SELECT TOP(1)InvoiceSeriesId FROM sales.InvoiceSeries WHERE IsDefault=1);IF NOT EXISTS(SELECT 1 FROM sales.POSCounters WHERE CounterCode='DEMO-POS-01')INSERT sales.POSCounters(CounterCode,CounterName,WarehouseId,InvoiceSeriesId)VALUES('DEMO-POS-01','Demo Billing Counter',@Store,@Series);DECLARE @Counter UNIQUEIDENTIFIER=(SELECT CounterId FROM sales.POSCounters WHERE CounterCode='DEMO-POS-01');
IF NOT EXISTS(SELECT 1 FROM sales.POSShift WHERE CounterId=@Counter AND Status='OPEN')INSERT sales.POSShift(CounterId,OpenedBy,OpeningCash)VALUES(@Counter,@User,2000);DECLARE @Shift UNIQUEIDENTIFIER=(SELECT TOP(1)ShiftId FROM sales.POSShift WHERE CounterId=@Counter ORDER BY OpenedOn DESC);
IF NOT EXISTS(SELECT 1 FROM sales.SalesInvoices WHERE Remarks='Demo seed sale')BEGIN DECLARE @SaleItems NVARCHAR(MAX)=CONCAT('[{"ProductId":"',@Rice,'","Barcode":"8901000000011","Quantity":1,"UnitPrice":340,"DiscountPercentage":5,"DiscountAmount":0,"TaxPercentage":5}]');EXEC sales.POS_PostInvoice @CounterId=@Counter,@ShiftId=@Shift,@CustomerId=@Customer,@WarehouseId=@Store,@ItemsJson=@SaleItems,@PaymentsJson='[{"MethodCode":"CASH","Amount":150},{"MethodCode":"UPI","Amount":150,"ReferenceNumber":"DEMO-UPI-001"}]',@BillDiscount=10,@Remarks='Demo seed sale',@DiscountAuthorizedBy='admin',@CreatedBy=@User;END;
DECLARE @Sale UNIQUEIDENTIFIER=(SELECT InvoiceId FROM sales.SalesInvoices WHERE Remarks='Demo seed sale');IF @Sale IS NOT NULL AND NOT EXISTS(SELECT 1 FROM sales.SalesInvoiceReturns WHERE InvoiceId=@Sale)BEGIN DECLARE @SaleItem UNIQUEIDENTIFIER=(SELECT TOP(1)InvoiceItemId FROM sales.SalesInvoiceItems WHERE InvoiceId=@Sale);DECLARE @SaleReturn NVARCHAR(MAX)=CONCAT('[{"InvoiceItemId":"',@SaleItem,'","Quantity":0.25}]');EXEC sales.POS_ReturnInvoice @InvoiceId=@Sale,@ItemsJson=@SaleReturn,@Reason='Demo partial return',@CreatedBy=@User;END;
PRINT 'WhatsBizERP demo data seed completed.';
