SET NOCOUNT ON;SET XACT_ABORT ON;
DECLARE @Now DATETIMEOFFSET=SYSUTCDATETIME(),@User NVARCHAR(50)='demo-seed';
-- Product master
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-GROC')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-GROC','Grocery & Staples','Demo grocery category',1,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-BEV')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,ParentCategoryId,CreatedOn,CreatedBy,IsActive,IsDeleted)SELECT NEWID(),'DEMO-BEV','Beverages','Demo beverages category',2,ProductCategoryId,@Now,@User,1,0 FROM master.ProductCategories WHERE CategoryCode='DEMO-GROC';
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-SAREE')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-SAREE','Sarees & Ethnic Wear','Demo sarees and ethnic wear',3,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-CARE')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-CARE','Personal Care','Demo personal care products',4,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Brands WHERE BrandCode='DEMO-FRESH')INSERT master.Brands(BrandId,BrandCode,BrandName,Description,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-FRESH','Fresh Basket','Demo private label',@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-EA')INSERT master.UnitsOfMeasure(UnitId,UnitCode,UnitName,ShortName,DecimalPlaces,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-EA','Each','EA',0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-KG')INSERT master.UnitsOfMeasure(UnitId,UnitCode,UnitName,ShortName,DecimalPlaces,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-KG','Kilogram','KG',3,@Now,@User,1,0);
DECLARE @Grocery UNIQUEIDENTIFIER=(SELECT ProductCategoryId FROM master.ProductCategories WHERE CategoryCode='DEMO-GROC'),@Beverage UNIQUEIDENTIFIER=(SELECT ProductCategoryId FROM master.ProductCategories WHERE CategoryCode='DEMO-BEV'),@Saree UNIQUEIDENTIFIER=(SELECT ProductCategoryId FROM master.ProductCategories WHERE CategoryCode='DEMO-SAREE'),@Care UNIQUEIDENTIFIER=(SELECT ProductCategoryId FROM master.ProductCategories WHERE CategoryCode='DEMO-CARE'),@Brand UNIQUEIDENTIFIER=(SELECT BrandId FROM master.Brands WHERE BrandCode='DEMO-FRESH'),@Each UNIQUEIDENTIFIER=(SELECT UnitId FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-EA'),@Kg UNIQUEIDENTIFIER=(SELECT UnitId FROM master.UnitsOfMeasure WHERE UnitCode='DEMO-KG');
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-RICE-5KG')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-RICE-5KG','8901000000011','Premium Rice 5 kg','Demo staple product',@Grocery,@Brand,@Each,'1006',5,280,340,360,10,200,25,5,1,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-COLA-1L')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-COLA-1L','8901000000028','Cola Drink 1 L','Demo beverage',@Beverage,@Brand,@Each,'2202',28,45,65,70,12,250,30,1,1,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-SUGAR-1KG')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-SUGAR-1KG','8901000000035','Refined Sugar 1 kg','Demo staple product',@Grocery,@Brand,@Each,'1701',5,38,48,50,15,300,40,1,0,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-SAREE-BANARASI')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-SAREE-BANARASI','8901000000042','Banarasi Silk Saree - Ruby','Handloom-inspired festive silk saree with zari border',@Saree,@Brand,@Each,'6211',5,1450,1899,2299,2,50,5,0.5,0,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-SAREE-COTTON')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-SAREE-COTTON','8901000000059','Everyday Cotton Saree - Indigo','Breathable cotton saree for everyday comfort',@Saree,@Brand,@Each,'6211',5,520,799,999,3,60,8,0.45,0,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-CARE-SOAP')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-CARE-SOAP','8901000000066','Herbal Bath Soap 100 g','Gentle everyday herbal cleansing bar',@Care,@Brand,@Each,'3401',18,28,42,50,10,200,25,0.1,1,0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.Products WHERE ProductCode='DEMO-CARE-SHAMPOO')INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-CARE-SHAMPOO','8901000000073','Daily Care Shampoo 340 ml','Moisturising shampoo for daily care',@Care,@Brand,@Each,'3305',18,125,179,220,8,100,15,0.34,1,0,@Now,@User,1,0);
DECLARE @Rice UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-RICE-5KG'),@Cola UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-COLA-1L'),@Sugar UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-SUGAR-1KG'),@Banarasi UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-SAREE-BANARASI'),@CottonSaree UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-SAREE-COTTON'),@Soap UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-CARE-SOAP'),@Shampoo UNIQUEIDENTIFIER=(SELECT ProductId FROM master.Products WHERE ProductCode='DEMO-CARE-SHAMPOO');
IF NOT EXISTS(SELECT 1 FROM master.ProductBarcodes WHERE Barcode='8901000000110')INSERT master.ProductBarcodes(ProductBarcodeId,ProductId,Barcode,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'8901000000110',0,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductPrices WHERE ProductId=@Rice AND PriceType='Retail')INSERT master.ProductPrices(ProductPriceId,ProductId,PriceType,Amount,EffectiveFrom,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'Retail',340,@Now,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductTaxMappings WHERE ProductId=@Rice AND TaxCode='GST5')INSERT master.ProductTaxMappings(ProductTaxMappingId,ProductId,TaxCode,TaxPercentage,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'GST5',5,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductImages WHERE ProductId=@Rice)INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Rice,'demo-rice.svg','image/svg+xml',CONVERT(VARBINARY(MAX),N'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="160"><rect width="100%" height="100%" fill="#f5e6b3"/><text x="30" y="85" font-size="24">Premium Rice</text></svg>'),1,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductImages WHERE ProductId=@Banarasi)INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Banarasi,'demo-banarasi.svg','image/svg+xml',CONVERT(VARBINARY(MAX),N'<svg xmlns="http://www.w3.org/2000/svg" width="600" height="420"><rect width="100%" height="100%" fill="#8b1538"/><path d="M0 330h600v90H0z" fill="#d8a83e"/><path d="M0 30h600v22H0z" fill="#e8c568"/><text x="150" y="220" fill="#fff4c2" font-size="38" font-family="serif">BANARASI</text><text x="190" y="265" fill="#fff4c2" font-size="24" font-family="serif">SILK SAREE</text></svg>'),1,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductImages WHERE ProductId=@CottonSaree)INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@CottonSaree,'demo-cotton-saree.svg','image/svg+xml',CONVERT(VARBINARY(MAX),N'<svg xmlns="http://www.w3.org/2000/svg" width="600" height="420"><rect width="100%" height="100%" fill="#315b70"/><path d="M0 350h600v70H0z" fill="#d5b15b"/><path d="M0 45h600v18H0z" fill="#d5b15b"/><text x="145" y="225" fill="#fff" font-size="34" font-family="serif">COTTON SAREE</text></svg>'),1,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductImages WHERE ProductId=@Soap)INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Soap,'demo-herbal-soap.svg','image/svg+xml',CONVERT(VARBINARY(MAX),N'<svg xmlns="http://www.w3.org/2000/svg" width="420" height="320"><rect width="100%" height="100%" rx="24" fill="#e7f2d5"/><circle cx="210" cy="135" r="72" fill="#8aa95a"/><text x="105" y="255" fill="#31512d" font-size="28">HERBAL SOAP</text></svg>'),1,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductImages WHERE ProductId=@Shampoo)INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),@Shampoo,'demo-shampoo.svg','image/svg+xml',CONVERT(VARBINARY(MAX),N'<svg xmlns="http://www.w3.org/2000/svg" width="420" height="320"><rect width="100%" height="100%" rx="24" fill="#dbeaf5"/><rect x="150" y="45" width="120" height="215" rx="28" fill="#3979a4"/><text x="175" y="160" fill="#fff" font-size="20">DAILY</text><text x="158" y="190" fill="#fff" font-size="16">CARE</text></svg>'),1,@Now,@User,1,0);
-- Expanded 50-product demo catalogue. Each row receives ERP stock and an embedded SVG image.
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-HOME')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-HOME','Home & Kitchen','Demo home and kitchen products',5,@Now,@User,1,0);
IF NOT EXISTS(SELECT 1 FROM master.ProductCategories WHERE CategoryCode='DEMO-STATIONERY')INSERT master.ProductCategories(ProductCategoryId,CategoryCode,CategoryName,Description,DisplayOrder,CreatedOn,CreatedBy,IsActive,IsDeleted)VALUES(NEWID(),'DEMO-STATIONERY','Books & Stationery','Demo stationery products',6,@Now,@User,1,0);
DECLARE @Catalog TABLE(CategoryCode NVARCHAR(50),ProductCode NVARCHAR(50),ProductName NVARCHAR(250),ShortDescription NVARCHAR(500),Barcode NVARCHAR(100),PurchasePrice DECIMAL(18,4),SellingPrice DECIMAL(18,4),MRP DECIMAL(18,4),GSTPercentage DECIMAL(5,2),ImageColor NVARCHAR(20));
INSERT @Catalog VALUES
('DEMO-GROC','DEMO-GROC-01','Toor Dal 1 kg','Premium split pigeon peas','8901000010001',110,139,155,5,'#f4d6a0'),('DEMO-GROC','DEMO-GROC-02','Moong Dal 1 kg','Clean split green gram','8901000010002',95,125,140,5,'#d9edb5'),('DEMO-GROC','DEMO-GROC-03','Wheat Flour 5 kg','Fresh chakki atta','8901000010003',185,229,260,5,'#f1dfb8'),('DEMO-GROC','DEMO-GROC-04','Basmati Rice 1 kg','Long grain aromatic rice','8901000010004',90,119,135,5,'#f7ebc7'),('DEMO-GROC','DEMO-GROC-05','Poha Thick 1 kg','Flattened rice breakfast staple','8901000010005',48,62,72,5,'#ead6a5'),('DEMO-GROC','DEMO-GROC-06','Mustard Oil 1 L','Cold-pressed cooking oil','8901000010006',130,169,190,5,'#f5c84b'),('DEMO-GROC','DEMO-GROC-07','Sunflower Oil 1 L','Light everyday cooking oil','8901000010007',118,149,170,5,'#ffe08a'),('DEMO-GROC','DEMO-GROC-08','Rock Salt 1 kg','Natural mineral salt','8901000010008',22,34,40,5,'#e8e8e8'),('DEMO-GROC','DEMO-GROC-09','Turmeric Powder 200 g','Bright ground turmeric','8901000010009',34,49,58,5,'#f6bd32'),('DEMO-GROC','DEMO-GROC-10','Mixed Pickle 500 g','Traditional mixed vegetable pickle','8901000010010',72,99,115,12,'#c97735'),
('DEMO-BEV','DEMO-BEV-01','Mango Juice 1 L','Refreshing mango fruit drink','8901000010011',65,89,100,12,'#f6a623'),('DEMO-BEV','DEMO-BEV-02','Mineral Water 1 L','Packaged drinking water','8901000010012',12,20,20,12,'#9bd7f5'),('DEMO-BEV','DEMO-BEV-03','Green Tea 25 Bags','Aromatic green tea bags','8901000010013',88,119,140,5,'#93c47d'),('DEMO-BEV','DEMO-BEV-04','Instant Coffee 100 g','Rich roasted instant coffee','8901000010014',145,189,215,5,'#9b6b43'),('DEMO-BEV','DEMO-BEV-05','Lemon Soda 750 ml','Crisp sparkling lemon drink','8901000010015',28,42,48,28,'#d9ef7a'),('DEMO-BEV','DEMO-BEV-06','Cold Coffee 250 ml','Chilled ready-to-drink coffee','8901000010016',35,55,60,12,'#8b5e3c'),('DEMO-BEV','DEMO-BEV-07','Coconut Water 1 L','Natural tender coconut water','8901000010017',75,105,120,12,'#d6f0cf'),('DEMO-BEV','DEMO-BEV-08','Masala Chai 250 g','Classic Indian tea blend','8901000010018',72,99,115,5,'#bd7a4a'),
('DEMO-SAREE','DEMO-SAREE-01','Kanjivaram Silk Saree - Teal','Festive silk saree with woven border','8901000010019',2100,2799,3299,5,'#087f8c'),('DEMO-SAREE','DEMO-SAREE-02','Chanderi Saree - Peach','Lightweight handloom drape','8901000010020',780,1099,1299,5,'#f3a68b'),('DEMO-SAREE','DEMO-SAREE-03','Printed Georgette Saree - Wine','Elegant printed party saree','8901000010021',640,899,1099,5,'#72243a'),('DEMO-SAREE','DEMO-SAREE-04','Linen Saree - Mustard','Soft textured linen saree','8901000010022',720,999,1199,5,'#d6a72c'),('DEMO-SAREE','DEMO-SAREE-05','Organza Saree - Lavender','Sheer organza festive saree','8901000010023',920,1299,1499,5,'#b9a1d8'),('DEMO-SAREE','DEMO-SAREE-06','Cotton Silk Saree - Green','Easy-care cotton silk saree','8901000010024',560,799,949,5,'#4e9465'),('DEMO-SAREE','DEMO-SAREE-07','Bandhani Saree - Red','Traditional tie-dye saree','8901000010025',680,949,1099,5,'#b52332'),('DEMO-SAREE','DEMO-SAREE-08','Tussar Saree - Beige','Natural textured tussar silk','8901000010026',1150,1599,1899,5,'#c9b28b'),('DEMO-SAREE','DEMO-SAREE-09','Ikat Saree - Blue','Handloom ikat patterned saree','8901000010027',850,1199,1399,5,'#315b83'),('DEMO-SAREE','DEMO-SAREE-10','Daily Wear Saree - Pink','Comfortable printed daily saree','8901000010028',280,449,525,5,'#e58aa8'),
('DEMO-CARE','DEMO-CARE-01','Face Wash 100 ml','Refreshing aloe face wash','8901000010029',82,119,140,18,'#a7d8d1'),('DEMO-CARE','DEMO-CARE-02','Body Lotion 200 ml','Daily moisturising lotion','8901000010030',110,159,185,18,'#f1c6a8'),('DEMO-CARE','DEMO-CARE-03','Toothpaste 150 g','Complete family dental care','8901000010031',58,85,99,18,'#8dc4e5'),('DEMO-CARE','DEMO-CARE-04','Neem Face Pack 100 g','Herbal cleansing face pack','8901000010032',72,105,125,18,'#a6c98b'),('DEMO-CARE','DEMO-CARE-05','Hair Oil 200 ml','Nourishing coconut hair oil','8901000010033',75,109,125,18,'#e0b760'),('DEMO-CARE','DEMO-CARE-06','Hand Wash 250 ml','Gentle liquid hand wash','8901000010034',65,95,110,18,'#8fb8de'),('DEMO-CARE','DEMO-CARE-07','Deodorant 150 ml','Long-lasting fresh fragrance','8901000010035',120,169,199,18,'#9c9cbe'),('DEMO-CARE','DEMO-CARE-08','Hand Cream 50 g','Softening everyday hand cream','8901000010036',48,75,89,18,'#e8b1b8'),('DEMO-CARE','DEMO-CARE-09','Face Moisturiser 50 g','Lightweight daily moisturiser','8901000010037',105,149,175,18,'#c6dfed'),('DEMO-CARE','DEMO-CARE-10','Hair Conditioner 180 ml','Smoothening hair conditioner','8901000010038',95,139,160,18,'#d9b4d8'),
('DEMO-HOME','DEMO-HOME-01','Stainless Steel Tumbler','Durable everyday steel tumbler','8901000010039',55,79,95,18,'#b8c3ca'),('DEMO-HOME','DEMO-HOME-02','Non-Stick Fry Pan','Kitchen fry pan with soft handle','8901000010040',380,499,599,18,'#343d46'),('DEMO-HOME','DEMO-HOME-03','Cotton Hand Towel','Soft absorbent cotton towel','8901000010041',65,99,120,5,'#8dc6c1'),('DEMO-HOME','DEMO-HOME-04','Food Storage Container Set','Three-piece kitchen container set','8901000010042',190,269,320,18,'#e5a66f'),('DEMO-HOME','DEMO-HOME-05','LED Bulb 9W','Energy-saving warm white LED bulb','8901000010043',65,89,105,18,'#fff1a8'),('DEMO-HOME','DEMO-HOME-06','Bamboo Serving Tray','Natural bamboo serving tray','8901000010044',220,299,349,18,'#b8895b'),
('DEMO-STATIONERY','DEMO-STATIONERY-01','A5 ruled notebook','Hardbound ruled notebook','8901000010045',45,69,80,12,'#6c8fc0'),('DEMO-STATIONERY','DEMO-STATIONERY-02','Ball Pen Blue Pack','Pack of five smooth blue pens','8901000010046',28,45,50,12,'#4775b5'),('DEMO-STATIONERY','DEMO-STATIONERY-03','Pencil Box','Compact school pencil box','8901000010047',65,95,110,12,'#ed9b4f'),('DEMO-STATIONERY','DEMO-STATIONERY-04','Marker Set','Set of six assorted markers','8901000010048',75,109,125,12,'#8d6bb3'),('DEMO-STATIONERY','DEMO-STATIONERY-05','Desk Calendar','Monthly desk calendar','8901000010049',55,79,95,12,'#75a982'),('DEMO-STATIONERY','DEMO-STATIONERY-06','Gift Wrap Paper Set','Colourful gift wrap sheets','8901000010050',42,65,75,12,'#d56b80');
INSERT master.Products(ProductId,ProductCode,Barcode,ProductName,ShortDescription,CategoryId,BrandId,UnitId,HSNCode,GSTPercentage,PurchasePrice,SellingPrice,MRP,MinimumStock,MaximumStock,ReorderLevel,Weight,IsBatchManaged,IsSerialManaged,CreatedOn,CreatedBy,IsActive,IsDeleted)
SELECT NEWID(),d.ProductCode,d.Barcode,d.ProductName,d.ShortDescription,c.ProductCategoryId,@Brand,@Each,'9999',d.GSTPercentage,d.PurchasePrice,d.SellingPrice,d.MRP,5,100,10,1,0,0,@Now,@User,1,0 FROM @Catalog d JOIN master.ProductCategories c ON c.CategoryCode=d.CategoryCode WHERE NOT EXISTS(SELECT 1 FROM master.Products p WHERE p.ProductCode=d.ProductCode);
INSERT master.ProductImages(ProductImageId,ProductId,FileName,ContentType,ImageData,IsPrimary,CreatedOn,CreatedBy,IsActive,IsDeleted)
SELECT NEWID(),p.ProductId,CONCAT(LOWER(p.ProductCode),'.svg'),'image/svg+xml',CONVERT(VARBINARY(MAX),CONCAT('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="420"><rect width="100%" height="100%" rx="28" fill="',d.ImageColor,'"/><rect x="120" y="65" width="360" height="220" rx="22" fill="#ffffff" opacity=".82"/><text x="300" y="175" text-anchor="middle" fill="#263238" font-size="24" font-family="Arial">WHATSBIZ DEMO</text><text x="300" y="220" text-anchor="middle" fill="#263238" font-size="19" font-family="Arial">',REPLACE(p.ProductName,'&','and'),'</text></svg>')),1,@Now,@User,1,0 FROM @Catalog d JOIN master.Products p ON p.ProductCode=d.ProductCode WHERE NOT EXISTS(SELECT 1 FROM master.ProductImages i WHERE i.ProductId=p.ProductId);
-- SVG is stored as single-byte XML so browsers can decode the image response correctly.
UPDATE i SET ImageData=CONVERT(VARBINARY(MAX),CONVERT(VARCHAR(MAX),CONVERT(NVARCHAR(MAX),i.ImageData))) FROM master.ProductImages i JOIN master.Products p ON p.ProductId=i.ProductId WHERE p.ProductCode LIKE 'DEMO-%' AND i.ContentType='image/svg+xml';
-- Suppliers and customers
DECLARE @Net30 UNIQUEIDENTIFIER=(SELECT TOP(1)PaymentTermId FROM purchase.SupplierPaymentTerms WHERE PaymentTermCode='NET30'),@CustNet30 UNIQUEIDENTIFIER=(SELECT TOP(1)PaymentTermId FROM sales.CustomerPaymentTerms WHERE PaymentTermCode='NET30');
IF NOT EXISTS(SELECT 1 FROM purchase.Suppliers WHERE SupplierCode='DEMO-SUP-001')INSERT purchase.Suppliers(SupplierId,SupplierCode,SupplierName,SupplierType,GSTIN,PAN,Email,Mobile,Currency,PaymentTermId,CreditLimit,OpeningBalance,IsGSTRegistered,IsTDSApplicable,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-SUP-001','Maharashtra Wholesale Traders','Distributor','27ABCDE1234F1Z5','ABCDE1234F','orders@demo-wholesale.test','9876501001','INR',@Net30,500000,2500,1,0,'Demo supplier',@User);
IF NOT EXISTS(SELECT 1 FROM purchase.Suppliers WHERE SupplierCode='DEMO-SUP-002')INSERT purchase.Suppliers(SupplierId,SupplierCode,SupplierName,SupplierType,Email,Mobile,Currency,PaymentTermId,CreditLimit,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-SUP-002','Local Beverage Distributors','Distributor','sales@demo-beverage.test','9876501002','INR',@Net30,200000,'Demo supplier',@User);
DECLARE @Supplier UNIQUEIDENTIFIER=(SELECT SupplierId FROM purchase.Suppliers WHERE SupplierCode='DEMO-SUP-001');
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierContacts WHERE SupplierId=@Supplier)INSERT purchase.SupplierContacts(SupplierId,ContactPerson,Designation,Mobile,Email,Department,IsPrimary)VALUES(@Supplier,'Amit Patil','Sales Manager','9876501101','amit@demo-wholesale.test','Sales',1);
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierAddresses WHERE SupplierId=@Supplier)INSERT purchase.SupplierAddresses(SupplierId,AddressType,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Supplier,'Business','Market Yard Road','Pune','Pune','Maharashtra','India','411037');
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierBankAccounts WHERE SupplierId=@Supplier)INSERT purchase.SupplierBankAccounts(SupplierId,BankName,Branch,AccountNumber,IFSCCode,UPIId)VALUES(@Supplier,'State Bank of India','Market Yard','12345678901','SBIN0000456','demowholesale@upi');
IF NOT EXISTS(SELECT 1 FROM purchase.SupplierDocuments WHERE SupplierId=@Supplier)INSERT purchase.SupplierDocuments(SupplierId,DocumentType,FileName,ContentType,DocumentData,UploadedBy)VALUES(@Supplier,'GST Certificate','demo-gst.txt','text/plain',CONVERT(VARBINARY(MAX),'Demo GST certificate'),@User);
IF NOT EXISTS(SELECT 1 FROM sales.Customers WHERE CustomerCode='DEMO-CUST-001')INSERT sales.Customers(CustomerId,CustomerCode,CustomerName,CustomerType,GSTIN,PAN,Email,Mobile,Currency,PaymentTermId,CreditLimit,OpeningBalance,IsGSTRegistered,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-CUST-001','Sunrise Cafe','Business','27AAECS1234F1Z2','AAECS1234F','accounts@sunrise-demo.test','9876502001','INR',@CustNet30,100000,1200,1,'Demo GST customer',@User);
IF NOT EXISTS(SELECT 1 FROM sales.Customers WHERE CustomerCode='DEMO-CUST-002')INSERT sales.Customers(CustomerId,CustomerCode,CustomerName,CustomerType,Email,Mobile,Currency,CreditLimit,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-CUST-002','Rajesh Kumar','Retail','rajesh@customer-demo.test','9876502002','INR',10000,'Demo retail customer',@User);
DECLARE @Customer UNIQUEIDENTIFIER=(SELECT CustomerId FROM sales.Customers WHERE CustomerCode='DEMO-CUST-001');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerContacts WHERE CustomerId=@Customer)INSERT sales.CustomerContacts(CustomerId,ContactPerson,Designation,Department,Mobile,Email,IsPrimary)VALUES(@Customer,'Neha Shah','Owner','Management','9876502101','neha@sunrise-demo.test',1);
IF NOT EXISTS(SELECT 1 FROM sales.CustomerAddresses WHERE CustomerId=@Customer AND AddressType='Billing')INSERT sales.CustomerAddresses(CustomerId,AddressType,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Customer,'Billing','FC Road','Pune','Pune','Maharashtra','India','411004');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerAddresses WHERE CustomerId=@Customer AND AddressType='Shipping')INSERT sales.CustomerAddresses(CustomerId,AddressType,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Customer,'Shipping','JM Road','Pune','Pune','Maharashtra','India','411005');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerBankAccounts WHERE CustomerId=@Customer)INSERT sales.CustomerBankAccounts(CustomerId,BankName,Branch,AccountNumber,IFSCCode,UPIId)VALUES(@Customer,'HDFC Bank','Deccan','50100123456789','HDFC0000123','sunrisecafe@upi');
IF NOT EXISTS(SELECT 1 FROM sales.CustomerDocuments WHERE CustomerId=@Customer)INSERT sales.CustomerDocuments(CustomerId,DocumentType,FileName,ContentType,DocumentData,UploadedBy)VALUES(@Customer,'GST Certificate','demo-customer-gst.txt','text/plain',CONVERT(VARBINARY(MAX),'Demo customer GST certificate'),@User);
-- Warehouses, address, contacts, zones and bins
DECLARE @RetailType UNIQUEIDENTIFIER=(SELECT TOP(1)WarehouseTypeId FROM inventory.WarehouseTypes WHERE TypeCode='RETAIL');IF @RetailType IS NULL SELECT TOP(1)@RetailType=WarehouseTypeId FROM inventory.WarehouseTypes;
IF NOT EXISTS(SELECT 1 FROM inventory.Warehouses WHERE WarehouseCode='DEMO-MAIN')INSERT inventory.Warehouses(WarehouseId,WarehouseCode,WarehouseName,WarehouseTypeId,ManagerName,Email,Mobile,Capacity,IsDefault,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-MAIN','Main Demo Warehouse',@RetailType,'Suresh Jadhav','warehouse@demo.test','9876503001',10000,1,'Primary demo warehouse',@User);
IF NOT EXISTS(SELECT 1 FROM inventory.Warehouses WHERE WarehouseCode='DEMO-STORE')INSERT inventory.Warehouses(WarehouseId,WarehouseCode,WarehouseName,WarehouseTypeId,ManagerName,Email,Mobile,Capacity,IsDefault,Remarks,CreatedBy)VALUES(NEWID(),'DEMO-STORE','Demo Retail Store',@RetailType,'Priya Nair','store@demo.test','9876503002',2000,0,'Demo retail outlet',@User);
DECLARE @Main UNIQUEIDENTIFIER=(SELECT WarehouseId FROM inventory.Warehouses WHERE WarehouseCode='DEMO-MAIN'),@Store UNIQUEIDENTIFIER=(SELECT WarehouseId FROM inventory.Warehouses WHERE WarehouseCode='DEMO-STORE');
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseAddresses WHERE WarehouseId=@Main)BEGIN INSERT inventory.WarehouseAddresses(WarehouseId,AddressLine1,City,District,State,Country,PostalCode)VALUES(@Main,'Warehouse Road, Hadapsar','Pune','Pune','Maharashtra','India','411028');UPDATE inventory.Warehouses SET AddressId=(SELECT AddressId FROM inventory.WarehouseAddresses WHERE WarehouseId=@Main)WHERE WarehouseId=@Main;END;
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseContacts WHERE WarehouseId=@Main)INSERT inventory.WarehouseContacts(WarehouseId,ContactPerson,Designation,Mobile,Email,IsPrimary)VALUES(@Main,'Suresh Jadhav','Warehouse Manager','9876503001','warehouse@demo.test',1);
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseZones WHERE WarehouseId=@Main AND ZoneCode='DEMO-A')INSERT inventory.WarehouseZones(WarehouseId,ZoneCode,ZoneName,Description)VALUES(@Main,'DEMO-A','Ambient Zone','General dry storage');DECLARE @Zone UNIQUEIDENTIFIER=(SELECT ZoneId FROM inventory.WarehouseZones WHERE WarehouseId=@Main AND ZoneCode='DEMO-A');
IF NOT EXISTS(SELECT 1 FROM inventory.WarehouseBins WHERE WarehouseId=@Main AND BinCode='DEMO-A-01')INSERT inventory.WarehouseBins(WarehouseId,ZoneId,BinCode,BinName,MaximumCapacity)VALUES(@Main,@Zone,'DEMO-A-01','Ambient Rack 01',500);
-- Purchase receipt creates balances, valuation, inventory ledger, expenses and payment.
DECLARE @PurchaseDue DATETIMEOFFSET=DATEADD(day,30,@Now);
IF NOT EXISTS(SELECT 1 FROM purchase.PurchaseInvoices WHERE SupplierInvoiceNo='DEMO-PUR-001')BEGIN DECLARE @PurchaseItems NVARCHAR(MAX)=CONCAT('[{"ProductId":"',@Rice,'","Barcode":"8901000000011","BatchNo":"RICE-2607","ExpiryDate":"2027-07-31","Quantity":40,"FreeQuantity":2,"PurchasePrice":280,"MRP":360,"SellingPrice":340,"DiscountPercentage":2,"GSTPercentage":5},{"ProductId":"',@Cola,'","Barcode":"8901000000028","BatchNo":"COLA-2608","ExpiryDate":"2027-02-28","Quantity":60,"FreeQuantity":5,"PurchasePrice":45,"MRP":70,"SellingPrice":65,"DiscountPercentage":0,"GSTPercentage":28},{"ProductId":"',@Sugar,'","Barcode":"8901000000035","Quantity":80,"FreeQuantity":0,"PurchasePrice":38,"MRP":50,"SellingPrice":48,"DiscountPercentage":1,"GSTPercentage":5}]');EXEC purchase.Purchase_Post @SupplierId=@Supplier,@SupplierInvoiceNo='DEMO-PUR-001',@InvoiceDate=@Now,@DueDate=@PurchaseDue,@WarehouseId=@Main,@ItemsJson=@PurchaseItems,@ExpensesJson='[{"ExpenseType":"FREIGHT","Description":"Inbound freight","Amount":450,"IsTaxable":false}]',@PaymentsJson='[{"MethodCode":"BANK","Amount":5000,"ReferenceNumber":"DEMO-NEFT-001"}]',@BillDiscount=100,@Remarks='Demo opening purchase',@CreatedBy=@User;END;
DECLARE @Purchase UNIQUEIDENTIFIER=(SELECT PurchaseInvoiceId FROM purchase.PurchaseInvoices WHERE SupplierInvoiceNo='DEMO-PUR-001');IF @Purchase IS NOT NULL AND NOT EXISTS(SELECT 1 FROM purchase.PurchaseAttachments WHERE PurchaseInvoiceId=@Purchase)INSERT purchase.PurchaseAttachments(PurchaseInvoiceId,FileName,ContentType,FileData,UploadedBy)VALUES(@Purchase,'demo-supplier-invoice.txt','text/plain',CONVERT(VARBINARY(MAX),'Demo supplier invoice attachment'),@User);
IF @Purchase IS NOT NULL AND NOT EXISTS(SELECT 1 FROM purchase.PurchaseReturns WHERE PurchaseInvoiceId=@Purchase)BEGIN DECLARE @PurchaseItem UNIQUEIDENTIFIER=(SELECT TOP(1)PurchaseItemId FROM purchase.PurchaseInvoiceItems WHERE PurchaseInvoiceId=@Purchase AND ProductId=@Cola);DECLARE @ReturnJson NVARCHAR(MAX)=CONCAT('[{"PurchaseItemId":"',@PurchaseItem,'","Quantity":2}]');EXEC purchase.Purchase_Return @PurchaseInvoiceId=@Purchase,@ItemsJson=@ReturnJson,@Reason='Two damaged bottles',@CreatedBy=@User;END;
-- Inventory adjustment, transfer and reservation demo rows.
INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)
SELECT p.ProductId,@Main,25,d.PurchasePrice,d.PurchasePrice,@User FROM @Catalog d JOIN master.Products p ON p.ProductCode=d.ProductCode WHERE NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances b WHERE b.ProductId=p.ProductId AND b.WarehouseId=@Main AND b.ZoneId IS NULL AND b.BinId IS NULL AND b.BatchNo IS NULL AND b.SerialNo IS NULL);
IF NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances WHERE ProductId=@Rice AND WarehouseId=@Main AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL)INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)VALUES(@Rice,@Main,10,280,280,@User);
IF NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances WHERE ProductId=@Banarasi AND WarehouseId=@Main AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL)INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)VALUES(@Banarasi,@Main,12,1450,1450,@User);
IF NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances WHERE ProductId=@CottonSaree AND WarehouseId=@Main AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL)INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)VALUES(@CottonSaree,@Main,18,520,520,@User);
IF NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances WHERE ProductId=@Soap AND WarehouseId=@Main AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL)INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)VALUES(@Soap,@Main,45,28,28,@User);
IF NOT EXISTS(SELECT 1 FROM inventory.InventoryBalances WHERE ProductId=@Shampoo AND WarehouseId=@Main AND ZoneId IS NULL AND BinId IS NULL AND BatchNo IS NULL AND SerialNo IS NULL)INSERT inventory.InventoryBalances(ProductId,WarehouseId,QuantityOnHand,AverageCost,LastPurchaseCost,CreatedBy)VALUES(@Shampoo,@Main,30,125,125,@User);
IF NOT EXISTS(SELECT 1 FROM inventory.StockAdjustments WHERE AdjustmentNo LIKE 'ADJ-%' AND CreatedOn>=DATEADD(year,-20,@Now))EXEC inventory.Inventory_Adjust @ProductId=@Sugar,@WarehouseId=@Main,@Quantity=5,@UnitCost=38,@AdjustmentType='INCREASE',@ReasonCode='OPENING_CORRECTION',@Remarks='Demo stock correction',@CreatedBy=@User;
IF NOT EXISTS(SELECT 1 FROM inventory.StockTransfers WHERE Remarks='Demo replenishment transfer')EXEC inventory.Inventory_Transfer @ProductId=@Rice,@SourceWarehouseId=@Main,@DestinationWarehouseId=@Store,@Quantity=5,@TransferDate=@Now,@Remarks='Demo replenishment transfer',@CreatedBy=@User;
IF NOT EXISTS(SELECT 1 FROM inventory.StockReservations WHERE ReservationReason='Demo customer order')EXEC inventory.Inventory_Reserve @Action='RESERVE',@ProductId=@Sugar,@WarehouseId=@Main,@Quantity=3,@ReservationReason='Demo customer order',@ReferenceType='SALES_ORDER',@CreatedBy=@User;
-- POS counter, shift, sale, payment/tax/discount/cash drawer and partial return.
DECLARE @Series UNIQUEIDENTIFIER=(SELECT TOP(1)InvoiceSeriesId FROM sales.InvoiceSeries WHERE IsDefault=1);IF NOT EXISTS(SELECT 1 FROM sales.POSCounters WHERE CounterCode='DEMO-POS-01')INSERT sales.POSCounters(CounterCode,CounterName,WarehouseId,InvoiceSeriesId)VALUES('DEMO-POS-01','Demo Billing Counter',@Store,@Series);DECLARE @Counter UNIQUEIDENTIFIER=(SELECT CounterId FROM sales.POSCounters WHERE CounterCode='DEMO-POS-01');
IF NOT EXISTS(SELECT 1 FROM sales.POSShift WHERE CounterId=@Counter AND Status='OPEN')INSERT sales.POSShift(CounterId,OpenedBy,OpeningCash)VALUES(@Counter,@User,2000);DECLARE @Shift UNIQUEIDENTIFIER=(SELECT TOP(1)ShiftId FROM sales.POSShift WHERE CounterId=@Counter ORDER BY OpenedOn DESC);
IF NOT EXISTS(SELECT 1 FROM sales.SalesInvoices WHERE Remarks='Demo seed sale')BEGIN DECLARE @SaleItems NVARCHAR(MAX)=CONCAT('[{"ProductId":"',@Rice,'","Barcode":"8901000000011","Quantity":1,"UnitPrice":340,"DiscountPercentage":5,"DiscountAmount":0,"TaxPercentage":5}]');EXEC sales.POS_PostInvoice @CounterId=@Counter,@ShiftId=@Shift,@CustomerId=@Customer,@WarehouseId=@Store,@ItemsJson=@SaleItems,@PaymentsJson='[{"MethodCode":"CASH","Amount":150},{"MethodCode":"UPI","Amount":150,"ReferenceNumber":"DEMO-UPI-001"}]',@BillDiscount=10,@Remarks='Demo seed sale',@DiscountAuthorizedBy='admin',@CreatedBy=@User;END;
DECLARE @Sale UNIQUEIDENTIFIER=(SELECT InvoiceId FROM sales.SalesInvoices WHERE Remarks='Demo seed sale');IF @Sale IS NOT NULL AND NOT EXISTS(SELECT 1 FROM sales.SalesInvoiceReturns WHERE InvoiceId=@Sale)BEGIN DECLARE @SaleItem UNIQUEIDENTIFIER=(SELECT TOP(1)InvoiceItemId FROM sales.SalesInvoiceItems WHERE InvoiceId=@Sale);DECLARE @SaleReturn NVARCHAR(MAX)=CONCAT('[{"InvoiceItemId":"',@SaleItem,'","Quantity":0.25}]');EXEC sales.POS_ReturnInvoice @InvoiceId=@Sale,@ItemsJson=@SaleReturn,@Reason='Demo partial return',@CreatedBy=@User;END;
PRINT 'WhatsBizERP demo data seed completed.';
