import { Component, OnInit, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CustomerAddress, CustomerAddressInput } from '../models/storefront.models';
import { StorefrontDataService } from '../data/storefront-data.service';

@Component({selector:'shop-addresses-page',standalone:true,imports:[RouterLink],template:`
<section class="account-section"><a class="account-back" [routerLink]="['/',storeKey,'account','profile']">← Account</a><header class="section-header"><div><span class="eyebrow">DELIVERY</span><h2>Addresses</h2><p>Manage addresses used for delivery.</p></div><button class="primary-button" type="button" (click)="startAdd()">+ Add Address</button></header>
@if(loading()){<div class="account-state" role="status">Loading addresses…</div>}@else if(!addresses().length&&!editing){<div class="account-state"><span class="state-icon">⌖</span><h3>No saved addresses</h3><p>Add an address to make checkout faster.</p><button class="primary-button" type="button" (click)="startAdd()">+ Add Address</button></div>}@else{<div class="address-list">@for(address of addresses();track address.addressId){<article class="address-card"><div class="address-card-head"><span class="type-badge">{{address.addressType}}</span>@if(address.isDefault){<span class="default-badge">✓ Default</span>}</div><h3>{{address.recipientName}}</h3><p>{{address.addressLine1}}@if(address.addressLine2){<br>{{address.addressLine2}}}@if(address.landmark){<br>{{address.landmark}}}<br>{{address.city}}, {{address.state}} - {{address.pincode}}<br><strong>Mobile: {{address.mobile}}</strong></p><div class="address-actions"><button type="button" class="secondary-button" (click)="edit(address)">Edit</button><button type="button" class="text-danger" (click)="remove(address)">Delete</button>@if(!address.isDefault){<button type="button" class="default-button" (click)="makeDefault(address)">Set Default</button>}</div></article>}</div>}
@if(editing||(!addresses().length&&!loading())){<section class="address-form-card"><div class="section-header"><div><span class="eyebrow">{{editing?'EDIT ADDRESS':'NEW ADDRESS'}}</span><h2>{{editing?'Edit address':'Add new address'}}</h2></div></div><form (submit)="$event.preventDefault();save()"><div class="form-grid"><label><span>Recipient Name</span><input [value]="form.recipientName" (input)="form.recipientName=$any($event.target).value" required></label><label><span>Mobile</span><input [value]="form.mobile" (input)="form.mobile=$any($event.target).value" inputmode="tel" required></label><label class="full-field"><span>Address</span><input [value]="form.addressLine1" (input)="form.addressLine1=$any($event.target).value" required></label><label class="full-field"><span>Address line 2 <small>Optional</small></span><input [value]="form.addressLine2||''" (input)="form.addressLine2=$any($event.target).value"></label><label class="full-field"><span>Landmark <small>Optional</small></span><input [value]="form.landmark||''" (input)="form.landmark=$any($event.target).value"></label><label><span>City</span><input [value]="form.city" (input)="form.city=$any($event.target).value" required></label><label><span>State</span><input [value]="form.state" (input)="form.state=$any($event.target).value" required></label><label><span>Pincode</span><input [value]="form.pincode" (input)="form.pincode=$any($event.target).value" inputmode="numeric" maxlength="6" required></label><label><span>Address Type</span><select [value]="form.addressType" (change)="form.addressType=$any($event.target).value"><option>Home</option><option>Work</option><option>Other</option></select></label></div><label class="checkbox-field"><input type="checkbox" [checked]="form.isDefault" (change)="form.isDefault=$any($event.target).checked"><span>Make default address</span></label><div class="form-actions"><button type="button" class="secondary-button" (click)="reset()">Cancel</button><button type="submit" class="primary-button" [disabled]="busy()">{{busy()?'Saving…':'Save Address'}}</button></div>@if(message()){<p class="form-message" role="status">{{message()}}</p>}</form></section>}
</section>`,styleUrl:'./account-section.css'})
export class AddressesPage implements OnInit{storeKey='';addresses=signal<CustomerAddress[]>([]);loading=signal(true);busy=signal(false);message=signal('');editing?:string;form:CustomerAddressInput=this.blank();constructor(private readonly route:ActivatedRoute,private readonly data:StorefrontDataService){}ngOnInit():void{this.storeKey=this.route.parent?.snapshot.paramMap.get('storeKey')??this.route.parent?.parent?.snapshot.paramMap.get('storeKey')??'';void this.load();}async load():Promise<void>{this.loading.set(true);try{this.addresses.set(await this.data.getAddresses(this.storeKey));}finally{this.loading.set(false);}}startAdd():void{this.editing=undefined;this.form=this.blank();this.message.set('');}edit(a:CustomerAddress):void{this.editing=a.addressId;this.form={...a};this.message.set('');}reset():void{this.editing=undefined;this.form=this.blank();this.message.set('');}async save():Promise<void>{this.busy.set(true);this.message.set('');try{await this.data.saveAddress(this.storeKey,this.form,this.editing);this.reset();await this.load();this.message.set('Address saved.');}catch{this.message.set('Address could not be saved.');}finally{this.busy.set(false);}}async remove(a:CustomerAddress):Promise<void>{if(!confirm('Delete this address?'))return;try{await this.data.deleteAddress(this.storeKey,a.addressId);await this.load();}catch{this.message.set('Address could not be deleted.');}}async makeDefault(a:CustomerAddress):Promise<void>{try{await this.data.setDefaultAddress(this.storeKey,a.addressId);await this.load();}catch{this.message.set('Default address could not be changed.');}}private blank():CustomerAddressInput{return{recipientName:'',mobile:'',addressLine1:'',addressLine2:'',landmark:'',city:'',state:'',pincode:'',addressType:'Home',isDefault:false};}}
