import { CurrencyPipe, DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CustomerSessionService } from '../customer-session.service';
import { StorefrontDataService } from '../data/storefront-data.service';
import { CustomerOrder } from '../models/storefront.models';

@Component({standalone:true,imports:[CurrencyPipe,DatePipe,RouterLink],template:`
<section class="page"><a class="back" [routerLink]="['/',storeKey,'orders']">← My orders</a>
@if(loading()){<p class="state">Loading order...</p>}@else if(!order()){<p class="state">Order not found for this account.</p>}
@else if(order();as current){<div class="heading"><div><span class="eyebrow">ORDER DETAILS</span><h1>{{current.orderNumber}}</h1><small>{{current.placedAt|date:'medium'}}</small></div><b>{{current.total|currency:'INR'}}</b></div>
<div class="grid"><article class="timeline"><h2>{{current.status}}</h2><ol>@for(step of current.timeline||[];track step.code){<li [class.complete]="step.state==='complete'" [class.current]="step.state==='current'" [class.exception]="step.state==='exception'"><span class="dot" aria-hidden="true">{{step.state==='complete'?'✓':step.state==='current'||step.state==='exception'?'●':'○'}}</span><div><strong>{{step.label}}</strong>@if(step.occurredAt){<small>{{step.occurredAt|date:'medium'}}</small>}</div></li>}</ol></article>
<article><h2>Order summary</h2><p>{{current.itemCount}} {{current.itemCount===1?'item':'items'}} · {{current.paymentMethod}} · {{current.paymentStatus}}</p>@if(current.trackingNumber){<p>Tracking: {{current.trackingNumber}}</p>}
@if(current.cancellation;as cancellation){<section class="cancellation">
@if(cancellation.requestStatus==='REQUESTED'){<strong>Cancellation requested</strong><p>Your retailer is reviewing the request. Your order and payment have not been refunded.</p>}
@else if(cancellation.requestStatus==='APPROVING'){<strong>Cancellation approval in progress</strong><p>The retailer is checking the order. No refund has been confirmed.</p>}
@else if(cancellation.requestStatus==='REJECTED'){<strong>Cancellation request declined</strong><p>{{cancellation.decisionNote||'Contact the retailer if you need help.'}}</p>}
@if(current.status==='Cancelled'){<strong>Cancellation approved</strong>@if(cancellation.refundStatus==='REFUNDED'){<p>Refund completed. {{cancellation.refundAmount|currency:'INR'}} refunded. @if(cancellation.refundedAt){Completed {{cancellation.refundedAt|date:'mediumDate'}}.}</p>}@else if(cancellation.refundNeedsReconciliation){<p>Refund of {{cancellation.refundAmount|currency:'INR'}} requires reconciliation. The retailer is checking its status.</p>}@else if(cancellation.refundStatus==='REFUND_PENDING'||cancellation.refundStatus==='REFUND_REQUIRED'){<p>Refund of {{cancellation.refundAmount|currency:'INR'}} is pending.</p>}@else if(cancellation.refundStatus==='REFUND_FAILED'){<p>Refund processing requires attention.</p>}@else{<p>No payment refund was required.</p>}}
@if(cancellation.canRequest){<label for="cancellation-reason">Cancel order</label><select id="cancellation-reason" [value]="reason" (change)="reason=selectValue($event)"><option value="">Select a reason</option><option value="Ordered by mistake">Ordered by mistake</option><option value="Changed mind">Changed mind</option><option value="Delivery taking too long">Delivery taking too long</option><option value="Other">Other</option></select><button type="button" [disabled]="saving()||!reason" (click)="requestCancellation(current.id)">{{saving()?'Sending request...':'Request cancellation'}}</button><small>The retailer must approve your request. Cancellation does not mean a payment has been refunded.</small>}
@if(cancelError()){<p class="cancel-error" role="alert">{{cancelError()}}</p>}
</section>}<div class="lines">@for(line of current.lines||[];track line.productId){<div><span>{{line.productName}} @if(line.packSize){<small>{{line.packSize}}</small>} <small>× {{line.quantity}}</small></span><b>{{line.lineTotal|currency:'INR'}}</b></div>}</div><div class="total"><span>Subtotal</span><b>{{(current.merchandiseSubtotal??((current.merchandiseAmount??current.total)-(current.merchandiseTaxAmount??0)))|currency:'INR'}}</b></div><div class="total"><span>GST</span><b>{{(current.merchandiseTaxAmount??0)|currency:'INR'}}</b></div>@if(current.promotionDiscount){<div class="total"><span>{{current.promotionName||'Storefront offer'}}</span><b>-{{current.promotionDiscount|currency:'INR'}}</b></div>}<div class="total"><span>Delivery Charges</span><b>{{current.deliveryCharge?(current.deliveryCharge|currency:'INR'):'FREE'}}</b></div><div class="total"><span>Total payable</span><b>{{current.total|currency:'INR'}}</b></div></article></div>}
</section>`,styles:[`:host{display:block}.page{max-width:920px;margin:auto;min-width:0}.back{color:var(--store-primary);font-size:11px;font-weight:800;text-decoration:none}.heading{display:flex;justify-content:space-between;gap:12px;margin:17px 0}.heading h1{margin:2px 0;font:800 22px Manrope,sans-serif;overflow-wrap:anywhere}.heading b{white-space:nowrap}.heading small,.page small,.page p{color:var(--store-muted);font-size:11px}.eyebrow{color:var(--store-primary);font-size:9px;font-weight:800;letter-spacing:1px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid article,.state{min-width:0;border:1px solid var(--store-border);border-radius:15px;padding:17px;background:#fff}.grid h2{margin:0 0 14px;font:800 15px Manrope,sans-serif}.timeline ol{list-style:none;padding:0;margin:0}.timeline li{display:flex;gap:13px;position:relative;min-height:60px;color:var(--store-muted)}.timeline li:not(:last-child):before{content:'';position:absolute;left:10px;top:25px;bottom:0;border-left:2px solid var(--store-border)}.timeline li.complete,.timeline li.current{color:var(--store-primary-dark)}.timeline li.exception{color:#b42318}.dot{z-index:1;display:grid;place-items:center;width:22px;height:22px;flex:none;border-radius:50%;background:var(--store-primary-soft);font-size:14px}.timeline li.exception .dot{background:#fff0ed}.timeline strong,.timeline small{display:block}.timeline strong{font-size:12px}.lines{display:grid;gap:9px;margin-top:18px}.lines>div,.total{display:flex;justify-content:space-between;gap:10px;font-size:11px}.lines span{overflow-wrap:anywhere}.lines small{display:inline}.total{border-top:1px solid var(--store-border);padding-top:12px;margin-top:12px;font-weight:800}.cancellation{display:grid;gap:7px;margin:15px 0;padding:12px;border-radius:10px;background:var(--store-surface-muted)}.cancellation strong{font-size:12px}.cancellation select,.cancellation button{min-height:40px;border:1px solid var(--store-border);border-radius:9px;padding:8px;font:inherit}.cancellation button{color:#fff;background:var(--store-primary);font-weight:800}.cancellation button:disabled{opacity:.5}.cancel-error{color:var(--store-danger)!important}.state{margin-top:18px}@media(max-width:620px){.grid{grid-template-columns:1fr}.heading h1{font-size:18px}.grid article{padding:13px}}`]})
export class OrderDetailsPage implements OnInit{storeKey='';readonly order=signal<CustomerOrder|null>(null);readonly loading=signal(true);readonly saving=signal(false);readonly cancelError=signal('');reason='';constructor(private readonly route:ActivatedRoute,private readonly data:StorefrontDataService,private readonly session:CustomerSessionService){}ngOnInit():void{this.storeKey=this.route.parent?.snapshot.paramMap.get('storeKey')??'';void this.load();}selectValue(event:Event):string{return(event.target as HTMLSelectElement).value;}async requestCancellation(orderId:string):Promise<void>{if(!this.reason||!confirm('Request cancellation of this entire order?'))return;this.saving.set(true);this.cancelError.set('');try{await this.data.requestCancellation(this.storeKey,orderId,this.reason);await this.load();}catch(error){const body=error instanceof HttpErrorResponse?error.error as{message?:string}|null:null;this.cancelError.set(body?.message??'Could not request cancellation. Please retry.');}finally{this.saving.set(false);}}private async load():Promise<void>{try{await this.session.refresh(this.storeKey);if(this.session.active())this.order.set(await this.data.getOrder(this.storeKey,this.route.snapshot.paramMap.get('orderId')??''));}finally{this.loading.set(false);}}}
