<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="WhatsBiz.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <ProjectReference Include="..\WhatsBiz.Contracts\WhatsBiz.Contracts.csproj" />
    <ProjectReference Include="..\WhatsBiz.Domain\WhatsBiz.Domain.csproj" />
    <ProjectReference Include="..\WhatsBiz.SharedKernel\WhatsBiz.SharedKernel.csproj" />
  </ItemGroup>
</Project>
