CREATE TABLE [sales].[Customers] ([CustomerId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Customers_Id] DEFAULT NEWSEQUENTIALID(),[CustomerCode] NVARCHAR(50) NOT NULL,[CustomerName] NVARCHAR(250) NOT NULL,[CustomerType] NVARCHAR(50) NOT NULL,[GSTIN] NVARCHAR(15) NULL,[PAN] NVARCHAR(10) NULL,[Email] NVARCHAR(256) NULL,[Mobile] NVARCHAR(15) NULL,[Telephone] NVARCHAR(20) NULL,[Website] NVARCHAR(300) NULL,[Currency] CHAR(3) NOT NULL CONSTRAINT [DF_Customers_Currency] DEFAULT 'INR',[PaymentTermId] UNIQUEIDENTIFIER NULL,[CreditLimit] DECIMAL(18,2) NOT NULL CONSTRAINT [DF_Customers_CreditLimit] DEFAULT 0,[OpeningBalance] DECIMAL(18,2) NOT NULL CONSTRAINT [DF_Customers_OpeningBalance] DEFAULT 0,[SalesPersonId] UNIQUEIDENTIFIER NULL,[CustomerGroupId] UNIQUEIDENTIFIER NULL,[PriceListId] UNIQUEIDENTIFIER NULL,[TenantId] UNIQUEIDENTIFIER NULL,[IsGSTRegistered] BIT NOT NULL CONSTRAINT [DF_Customers_GST] DEFAULT 0,[IsActive] BIT NOT NULL CONSTRAINT [DF_Customers_Active] DEFAULT 1,[IsDeleted] BIT NOT NULL CONSTRAINT [DF_Customers_Deleted] DEFAULT 0,[Remarks] NVARCHAR(1000) NULL,[CreatedOn] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Customers_Created] DEFAULT SYSUTCDATETIME(),[CreatedBy] NVARCHAR(256) NULL,[ModifiedOn] DATETIMEOFFSET NULL,[ModifiedBy] NVARCHAR(256) NULL,[RowVersion] ROWVERSION NOT NULL,CONSTRAINT [PK_Customers] PRIMARY KEY([CustomerId]),CONSTRAINT [FK_Customers_PaymentTerms] FOREIGN KEY([PaymentTermId]) REFERENCES [sales].[CustomerPaymentTerms]([PaymentTermId]),CONSTRAINT [FK_Customers_Tenant] FOREIGN KEY([TenantId]) REFERENCES [core].[Tenants]([TenantId]) ON DELETE NO ACTION,CONSTRAINT [CK_Customers_CreditLimit] CHECK([CreditLimit]>=0),CONSTRAINT [CK_Customers_GSTIN] CHECK([GSTIN] IS NULL OR LEN([GSTIN])=15),CONSTRAINT [CK_Customers_PAN] CHECK([PAN] IS NULL OR LEN([PAN])=10));
GO
CREATE UNIQUE INDEX [UX_Customers_Code] ON [sales].[Customers]([CustomerCode]) WHERE [IsDeleted]=0;
GO
CREATE UNIQUE INDEX [UX_Customers_GSTIN] ON [sales].[Customers]([GSTIN]) WHERE [GSTIN] IS NOT NULL AND [IsDeleted]=0;
GO
CREATE INDEX [IX_Customers_Search] ON [sales].[Customers]([CustomerName],[Mobile],[IsActive]);
GO
CREATE INDEX [IX_Customers_TenantCustomer] ON [sales].[Customers]([TenantId],[CustomerId]) WHERE [IsDeleted]=0;
GO
CREATE INDEX [IX_Customers_TenantMobile] ON [sales].[Customers]([TenantId],[Mobile]) WHERE [IsDeleted]=0 AND [Mobile] IS NOT NULL;
