CREATE TABLE [core].[Tenants]
(
    [TenantId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_Tenants] PRIMARY KEY,
    [TenantKey] NVARCHAR(100) NOT NULL CONSTRAINT [UQ_Tenants_TenantKey] UNIQUE,
    [Name] NVARCHAR(200) NOT NULL,
    [IsActive] BIT NOT NULL CONSTRAINT [DF_Tenants_IsActive] DEFAULT (1),
    [CreatedOn] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Tenants_CreatedOn] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(256) NULL,
    [ModifiedOn] DATETIMEOFFSET NULL,
    [ModifiedBy] NVARCHAR(256) NULL
);
