#pragma warning disable CA1725
using FluentValidation;
using MediatR;
using WhatsBiz.Application.Common.Interfaces;
namespace WhatsBiz.Application.Features.Gst;
public sealed record GstFilter(DateTimeOffset From, DateTimeOffset To, Guid? WarehouseId, Guid? PartyId, decimal? GstRate); public sealed record GstReportRowDto(Guid? Id, string? DocumentNumber, DateTimeOffset? DocumentDate, string? PartyName, string? PartyGstin, string? SourceType, string? SupplyType, string? HsnCode, decimal? GstRate, decimal Quantity, decimal TaxableAmount, decimal CgstAmount, decimal SgstAmount, decimal IgstAmount, decimal CessAmount, decimal ReverseChargeAmount, decimal TaxAdjustment, decimal RoundOff, long InvoiceCount, decimal TotalTax, decimal OutputCgst, decimal OutputSgst, decimal OutputIgst, decimal ItcCgst, decimal ItcSgst, decimal ItcIgst, decimal NetTaxPayable); public sealed record GstSettingsDto(Guid Id, string? CompanyGstin, string StateCode, string RegistrationType, bool IsCompositionScheme, DateOnly EffectiveDate, string? LegalName, string? TradeName); public sealed record GstSettingsInput(string? CompanyGstin, string StateCode, string RegistrationType, bool IsCompositionScheme, DateOnly EffectiveDate, string? LegalName, string? TradeName); public sealed record GstFileDto(byte[] Data, string ContentType, string FileName);
public sealed record GetGstReport(string Report, GstFilter Filter) : IRequest<IReadOnlyCollection<GstReportRowDto>>; public sealed record ExportGstReport(string Report, string Format, GstFilter Filter) : IRequest<GstFileDto>; public sealed record GetGstSettings : IRequest<GstSettingsDto>; public sealed record SaveGstSettings(GstSettingsInput Input) : IRequest<GstSettingsDto>;
public sealed class GstSettingsValidator : AbstractValidator<SaveGstSettings> { public GstSettingsValidator() { RuleFor(x => x.Input.CompanyGstin).Matches("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$").When(x => !string.IsNullOrWhiteSpace(x.Input.CompanyGstin)); RuleFor(x => x.Input.StateCode).Matches("^[0-9]{2}$"); RuleFor(x => x.Input.RegistrationType).Must(x => x is "REGULAR" or "COMPOSITION" or "UNREGISTERED"); RuleFor(x => x.Input).Must(x => !x.IsCompositionScheme || x.RegistrationType == "COMPOSITION").WithMessage("Composition scheme requires COMPOSITION registration type."); } }
public sealed class GstHandlers(IGstRepository repository, IGstExportService exporter, ICurrentUserService user) : IRequestHandler<GetGstReport, IReadOnlyCollection<GstReportRowDto>>, IRequestHandler<ExportGstReport, GstFileDto>, IRequestHandler<GetGstSettings, GstSettingsDto>, IRequestHandler<SaveGstSettings, GstSettingsDto> { public Task<IReadOnlyCollection<GstReportRowDto>> Handle(GetGstReport q, CancellationToken t) => repository.Report(q.Report, q.Filter, t); public async Task<GstFileDto> Handle(ExportGstReport q, CancellationToken t) { var rows = await repository.Report(q.Report, q.Filter, t); return new(exporter.Export(rows, q.Report, q.Format), exporter.ContentType(q.Format), $"{q.Report}-{q.Filter.From:yyyyMMdd}.{(q.Format.ToLowerInvariant() is "excel" or "xlsx" ? "xlsx" : q.Format.ToLowerInvariant())}"); } public Task<GstSettingsDto> Handle(GetGstSettings q, CancellationToken t) => repository.Settings(t); public async Task<GstSettingsDto> Handle(SaveGstSettings q, CancellationToken t) { await repository.SaveSettings(q.Input, user.Username, t); return await repository.Settings(t); } }
