import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { firstValueFrom } from 'rxjs';

interface Banner { slot:'PRIMARY'|'SECONDARY';isEnabled:boolean;startsAt?:string;endsAt?:string;title?:string;subtitle?:string;targetUrl?:string;displayOrder:number;imageUrl?:string; }
interface Settings { storeName:string;logoUrl?:string;banners:Banner[]; }

@Component({standalone:true,imports:[CommonModule,FormsModule,MatButtonModule],changeDetection:ChangeDetectionStrategy.OnPush,
template:`<section class="page"><header><p>Storefront / Ecommerce Settings</p><h1>Store branding</h1><span>Manage customer-facing identity and scheduled banners for your tenant.</span></header>
@if(settings();as current){<article><h2>Store logo</h2><p class="hint">Displayed beside {{current.storeName}}. JPEG, PNG or WebP, up to 5 MB.</p><div class="media-row">@if(current.logoUrl){<img class="logo" [src]="version(current.logoUrl)" alt="Current store logo"/>}@else{<div class="logo fallback">{{current.storeName.slice(0,1)}}</div>}<label class="upload">{{current.logoUrl?'Change':'Upload'}} logo<input type="file" accept="image/jpeg,image/png,image/webp" (change)="upload('logo',undefined,$event)"/></label>@if(current.logoUrl){<button mat-stroked-button type="button" (click)="remove('logo')">Remove</button>}</div></article>
<h2 class="banner-heading">Banners</h2>@for(banner of current.banners;track banner.slot){<article class="banner-card"><div class="banner-title"><h3>{{banner.slot}}</h3><label><input type="checkbox" [(ngModel)]="banner.isEnabled"/> Enabled</label></div>@if(banner.imageUrl){<div class="mobile-preview"><img class="preview" [src]="version(banner.imageUrl)" [alt]="banner.slot+' banner preview'"/></div>}<div class="media-row"><label class="upload">{{banner.imageUrl?'Change':'Upload'}} image<input type="file" accept="image/jpeg,image/png,image/webp" (change)="upload('banner',banner,$event)"/></label>@if(banner.imageUrl){<button mat-stroked-button type="button" (click)="remove('banner',banner)">Remove image</button>}</div><div class="grid"><label>Title<input [(ngModel)]="banner.title" maxlength="150"/></label><label>Subtitle<input [(ngModel)]="banner.subtitle" maxlength="300"/></label><label>Start (optional)<input type="datetime-local" [(ngModel)]="banner.startsAt"/></label><label>End (optional)<input type="datetime-local" [(ngModel)]="banner.endsAt"/></label><label>Safe target (optional)<input [(ngModel)]="banner.targetUrl" placeholder="/products or https://…"/></label><label>Display order<input type="number" min="0" max="100" [(ngModel)]="banner.displayOrder"/></label></div><button mat-flat-button type="button" (click)="save(banner)">Save {{banner.slot.toLowerCase()}}</button></article>}<p class="message">{{message()}}</p>}</section>`,
styles:[`.page{max-width:980px;padding:24px}header p{color:#16734a;font-weight:700}header h1{margin:.2rem 0}header span,.hint{color:#667085}.page article{margin-top:20px;border:1px solid #dce3df;border-radius:16px;padding:20px;background:#fff}.media-row,.banner-title{display:flex;align-items:center;gap:12px}.banner-title{justify-content:space-between}.logo{width:88px;height:88px;border-radius:16px;object-fit:cover}.fallback{display:grid;place-items:center;background:#e7f5ed;color:#145c43;font-size:30px;font-weight:800}.upload{display:inline-flex;border-radius:9px;padding:10px 14px;color:#fff;background:#146c43;font-weight:700;cursor:pointer}.upload input{display:none}.mobile-preview{width:min(100%,390px);margin:12px auto 18px;border:1px solid #dce3df;border-radius:20px;padding:13px 14px;background:#f7f9f6}.preview{display:block;width:100%;height:auto;aspect-ratio:5/2;object-fit:contain;border-radius:13px;background:#f2f4f3}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.grid label{display:grid;gap:5px;color:#475467;font-size:13px}.grid input{min-height:42px;border:1px solid #cfd8d3;border-radius:9px;padding:0 10px}.banner-heading{margin-top:30px}.message{color:#146c43}@media(max-width:650px){.page{padding:14px}.grid{grid-template-columns:1fr}.media-row{flex-wrap:wrap}}`]})
export class StorefrontSettingsComponent implements OnInit{readonly settings=signal<Settings|null>(null);readonly message=signal('');private cache=Date.now();constructor(private readonly http:HttpClient){}ngOnInit(){void this.load();}version(url:string){return `${url}?v=${this.cache}`;}async load(){const result=await firstValueFrom(this.http.get<Settings>('/api/storefront-administration'));result.banners=result.banners.map(b=>({...b,startsAt:this.localDate(b.startsAt),endsAt:this.localDate(b.endsAt)}));this.settings.set(result);}async save(b:Banner){await firstValueFrom(this.http.put(`/api/storefront-administration/banners/${b.slot}`,{...b,startsAt:this.toOffset(b.startsAt),endsAt:this.toOffset(b.endsAt)}));this.message.set(`${b.slot} banner saved.`);}async upload(kind:'logo'|'banner',b:Banner|undefined,event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const body=new FormData();body.append('file',file);const url=kind==='logo'?'/api/storefront-administration/logo':`/api/storefront-administration/banners/${b!.slot}/image`;await firstValueFrom(this.http.post(url,body));this.cache=Date.now();input.value='';await this.load();}async remove(kind:'logo'|'banner',b?:Banner){const url=kind==='logo'?'/api/storefront-administration/logo':`/api/storefront-administration/banners/${b!.slot}/image`;await firstValueFrom(this.http.delete(url));this.cache=Date.now();await this.load();}private localDate(value?:string):string|undefined{if(!value)return undefined;const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}private toOffset(value?:string):string|null{if(!value)return null;return new Date(value).toISOString();}}
