#pragma warning disable CA1725
using FluentValidation;
using MediatR;
using WhatsBiz.Application.Common.Interfaces;
using WhatsBiz.Application.Common.Exceptions;
namespace WhatsBiz.Application.Features.Finance;
public sealed record LedgerRowDto(DateTimeOffset EntryDate, string EntryType, string? ReferenceNumber, decimal Debit, decimal Credit, decimal Balance, string? Narration); public sealed record BookRowDto(DateTimeOffset EntryDate, string EntryType, string? ReferenceNumber, string? Mode, decimal AmountIn, decimal AmountOut, decimal Balance, string? Narration); public sealed record DayBookRowDto(DateTimeOffset EntryDate, string TransactionType, string? ReferenceNumber, decimal DebitTotal, decimal CreditTotal, string? Narration); public sealed record PartyTransactionInput(string PartyType, Guid PartyId, string PaymentMode, decimal Amount, DateTimeOffset EntryDate, string? ReferenceNumber, string? Narration); public sealed record PostedFinanceDto(Guid JournalEntryId, string JournalNumber);
public sealed record GetCustomerLedger(Guid Id, DateTimeOffset? From, DateTimeOffset? To) : IRequest<IReadOnlyCollection<LedgerRowDto>>; public sealed record GetSupplierLedger(Guid Id, DateTimeOffset? From, DateTimeOffset? To) : IRequest<IReadOnlyCollection<LedgerRowDto>>; public sealed record GetCashBook(DateTimeOffset? From, DateTimeOffset? To) : IRequest<IReadOnlyCollection<BookRowDto>>; public sealed record GetBankBook(DateTimeOffset? From, DateTimeOffset? To) : IRequest<IReadOnlyCollection<BookRowDto>>; public sealed record GetDayBook(DateTimeOffset? From, DateTimeOffset? To) : IRequest<IReadOnlyCollection<DayBookRowDto>>; public sealed record CreateReceipt(PartyTransactionInput Input) : IRequest<PostedFinanceDto>; public sealed record CreatePayment(PartyTransactionInput Input) : IRequest<PostedFinanceDto>;
public sealed class PartyTransactionValidator : AbstractValidator<PartyTransactionInput> { public PartyTransactionValidator() { RuleFor(x => x.PartyType).Must(x => x is "CUSTOMER" or "SUPPLIER"); RuleFor(x => x.PartyId).NotEmpty(); RuleFor(x => x.PaymentMode).NotEmpty(); RuleFor(x => x.Amount).GreaterThan(0); RuleFor(x => x.EntryDate).NotEmpty(); } }
public sealed class FinanceHandlers(IFinanceRepository repository, ICustomerRepository customers, ICurrentUserService user) : IRequestHandler<GetCustomerLedger, IReadOnlyCollection<LedgerRowDto>>, IRequestHandler<GetSupplierLedger, IReadOnlyCollection<LedgerRowDto>>, IRequestHandler<GetCashBook, IReadOnlyCollection<BookRowDto>>, IRequestHandler<GetBankBook, IReadOnlyCollection<BookRowDto>>, IRequestHandler<GetDayBook, IReadOnlyCollection<DayBookRowDto>>, IRequestHandler<CreateReceipt, PostedFinanceDto>, IRequestHandler<CreatePayment, PostedFinanceDto> { public async Task<IReadOnlyCollection<LedgerRowDto>> Handle(GetCustomerLedger q, CancellationToken t) { await EnsureCustomer(q.Id,t); return (await repository.CustomerLedger(q.Id,q.From,q.To,t)).Select(Map).ToArray(); } public async Task<IReadOnlyCollection<LedgerRowDto>> Handle(GetSupplierLedger q,CancellationToken t)=>(await repository.SupplierLedger(q.Id,q.From,q.To,t)).Select(Map).ToArray(); public async Task<IReadOnlyCollection<BookRowDto>> Handle(GetCashBook q,CancellationToken t)=>(await repository.CashBook(q.From,q.To,t)).Select(Map).ToArray(); public async Task<IReadOnlyCollection<BookRowDto>> Handle(GetBankBook q,CancellationToken t)=>(await repository.BankBook(q.From,q.To,t)).Select(Map).ToArray(); public async Task<IReadOnlyCollection<DayBookRowDto>> Handle(GetDayBook q,CancellationToken t)=>(await repository.DayBook(q.From,q.To,t)).Select(x=>new DayBookRowDto(x.EntryDate,x.TransactionType,x.ReferenceNumber,x.DebitTotal,x.CreditTotal,x.Narration)).ToArray(); public async Task<PostedFinanceDto> Handle(CreateReceipt q,CancellationToken t){if(q.Input.PartyType=="CUSTOMER")await EnsureCustomer(q.Input.PartyId,t);var x=await repository.Post("RECEIPT",q.Input.PartyType,q.Input.PartyId,q.Input.PaymentMode,q.Input.Amount,q.Input.EntryDate,q.Input.ReferenceNumber,q.Input.Narration,user.Username,t);return new(x.Id,x.Number);} public async Task<PostedFinanceDto> Handle(CreatePayment q,CancellationToken t)=>(await repository.Post("PAYMENT",q.Input.PartyType,q.Input.PartyId,q.Input.PaymentMode,q.Input.Amount,q.Input.EntryDate,q.Input.ReferenceNumber,q.Input.Narration,user.Username,t)) is var x?new(x.Id,x.Number):throw new InvalidOperationException(); private async Task EnsureCustomer(Guid id,CancellationToken t){if(!await customers.BelongsToCurrentTenant(id,t))throw new EntityNotFoundException("Customer not found.");} private static LedgerRowDto Map(PartyLedgerRow x)=>new(x.EntryDate,x.EntryType,x.ReferenceNumber,x.Debit,x.Credit,x.Balance,x.Narration); private static BookRowDto Map(BookRow x)=>new(x.EntryDate,x.EntryType,x.ReferenceNumber,x.Mode,x.AmountIn,x.AmountOut,x.Balance,x.Narration); }
