using System.Data;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using MediatR;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using WhatsBiz.Application.Common.Exceptions;
using WhatsBiz.Application.Features.Delivery;
using WhatsBiz.Application.Features.WhatsAppCommerce;
using WhatsBiz.Infrastructure.WhatsAppCommerce;
#pragma warning disable CA1725,CA1822

namespace WhatsBiz.Infrastructure.Delivery;

public sealed class DeliveryService(IConfiguration configuration,IDataProtectionProvider protection,IWhatsAppCommerceProviderResolver providers,IPublisher publisher) : IDeliveryService
{
    private string Cs=>configuration.GetConnectionString("DefaultConnection")??throw new InvalidOperationException("Database connection unavailable.");
    private static object Db(object? value)=>value??DBNull.Value;
    private static void P(SqlCommand q,string name,object? value)=>q.Parameters.AddWithValue(name,Db(value));
    private async Task<SqlConnection> Open(CancellationToken token){var c=new SqlConnection(Cs);await c.OpenAsync(token);return c;}

    public async Task<IReadOnlyCollection<DeliveryAgentDto>> Agents(Guid tenantId,CancellationToken token)
    { await using var c=await Open(token);await using var q=new SqlCommand(@"SELECT a.DeliveryAgentId,a.UserId,a.DisplayName,a.Mobile,a.IsActive,a.IsAvailable,CONVERT(bit,CASE WHEN s.DefaultDeliveryAgentId=a.DeliveryAgentId THEN 1 ELSE 0 END),SUM(CASE WHEN d.DeliveryStatus NOT IN('DELIVERED','CANCELLED','RETURNED') THEN 1 ELSE 0 END),SUM(CASE WHEN d.DeliveryStatus='DELIVERED' AND CONVERT(date,d.DeliveredAt)=CONVERT(date,SYSUTCDATETIME()) THEN 1 ELSE 0 END) FROM commerce.DeliveryAgents a LEFT JOIN commerce.TenantDeliverySettings s ON s.TenantId=a.TenantId LEFT JOIN commerce.OrderDeliveries d ON d.TenantId=a.TenantId AND d.DeliveryAgentId=a.DeliveryAgentId WHERE a.TenantId=@tenant GROUP BY a.DeliveryAgentId,a.UserId,a.DisplayName,a.Mobile,a.IsActive,a.IsAvailable,s.DefaultDeliveryAgentId ORDER BY a.IsActive DESC,a.DisplayName",c);P(q,"@tenant",tenantId);var rows=new List<DeliveryAgentDto>();await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))rows.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetBoolean(4),r.GetBoolean(5),r.GetBoolean(6),r.GetInt32(7),r.GetInt32(8)));return rows; }
    public async Task<IReadOnlyCollection<DeliveryUserDto>> EligibleUsers(Guid tenantId,CancellationToken token){await using var c=await Open(token);await using var q=new SqlCommand("SELECT u.Id,COALESCE(u.UserName,u.Email),u.Email,u.PhoneNumber FROM core.Users u WHERE u.TenantId=@tenant AND u.IsActive=1 AND u.IsDeleted=0 ORDER BY COALESCE(u.UserName,u.Email)",c);P(q,"@tenant",tenantId);var rows=new List<DeliveryUserDto>();await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))rows.Add(new(r.GetGuid(0),r.GetString(1),S(r,2),S(r,3)));return rows;}

    public async Task<DeliveryAgentDto> SaveAgent(Guid tenantId,Guid? id,SaveDeliveryAgentInput input,string actor,CancellationToken token)
    {
        if(string.IsNullOrWhiteSpace(input.DisplayName)||string.IsNullOrWhiteSpace(input.Mobile))throw new BusinessRuleException("Delivery agent name and mobile are required.");
        await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);
        await using(var valid=new SqlCommand("SELECT COUNT(1) FROM core.Users WHERE Id=@user AND TenantId=@tenant AND IsActive=1 AND IsDeleted=0",c,tx)){P(valid,"@user",input.UserId);P(valid,"@tenant",tenantId);if(Convert.ToInt32(await valid.ExecuteScalarAsync(token),CultureInfo.InvariantCulture)!=1)throw new BusinessRuleException("The selected active user does not belong to this tenant.");}
        await using(var role=new SqlCommand("INSERT core.UserRoles(UserId,RoleId) SELECT @user,r.Id FROM core.Roles r WHERE r.NormalizedName='DELIVERYAGENT' AND NOT EXISTS(SELECT 1 FROM core.UserRoles ur WHERE ur.UserId=@user AND ur.RoleId=r.Id)",c,tx)){P(role,"@user",input.UserId);await role.ExecuteNonQueryAsync(token);}
        var agentId=id??Guid.NewGuid();await using(var q=new SqlCommand(id is null?"INSERT commerce.DeliveryAgents(DeliveryAgentId,TenantId,UserId,DisplayName,Mobile,IsActive,IsAvailable,CreatedBy) VALUES(@id,@tenant,@user,@name,@mobile,@active,@available,@actor)":"UPDATE commerce.DeliveryAgents SET UserId=@user,DisplayName=@name,Mobile=@mobile,IsActive=@active,IsAvailable=@available,UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@actor WHERE DeliveryAgentId=@id AND TenantId=@tenant",c,tx)){P(q,"@id",agentId);P(q,"@tenant",tenantId);P(q,"@user",input.UserId);P(q,"@name",input.DisplayName.Trim());P(q,"@mobile",input.Mobile.Trim());P(q,"@active",input.IsActive);P(q,"@available",input.IsAvailable);P(q,"@actor",actor);if(await q.ExecuteNonQueryAsync(token)!=1)throw new EntityNotFoundException("Delivery agent was not found.");}
        if(!input.IsActive)await using(var warning=new SqlCommand("UPDATE commerce.TenantDeliverySettings SET UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@actor WHERE TenantId=@tenant AND DefaultDeliveryAgentId=@id",c,tx)){P(warning,"@actor",actor);P(warning,"@tenant",tenantId);P(warning,"@id",agentId);await warning.ExecuteNonQueryAsync(token);}
        await tx.CommitAsync(token);return (await Agents(tenantId,token)).Single(x=>x.DeliveryAgentId==agentId);
    }

    public async Task SetDefault(Guid tenantId,Guid? agentId,string actor,CancellationToken token)
    { await using var c=await Open(token);if(agentId is not null){await using var v=new SqlCommand("SELECT COUNT(1) FROM commerce.DeliveryAgents WHERE TenantId=@tenant AND DeliveryAgentId=@id AND IsActive=1",c);P(v,"@tenant",tenantId);P(v,"@id",agentId);if(Convert.ToInt32(await v.ExecuteScalarAsync(token),CultureInfo.InvariantCulture)!=1)throw new BusinessRuleException("Only an active delivery agent from this tenant can be the default.");}await using var q=new SqlCommand("UPDATE commerce.TenantDeliverySettings SET DefaultDeliveryAgentId=@id,UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@actor WHERE TenantId=@tenant",c);P(q,"@id",agentId);P(q,"@actor",actor);P(q,"@tenant",tenantId);if(await q.ExecuteNonQueryAsync(token)!=1)throw new EntityNotFoundException("Delivery settings were not found."); }

    public async Task<DeliverySettingsDto> Settings(Guid tenantId,CancellationToken token)
    { await using var c=await Open(token);await using var q=new SqlCommand(@"SELECT s.DeliveryEnabled,s.AutomaticAssignmentEnabled,s.DefaultDeliveryAgentId,CONVERT(bit,CASE WHEN a.IsActive=1 AND a.IsAvailable=1 THEN 1 ELSE 0 END),s.RequireDeliveryOtp,s.DeliveryOtpExpiryMinutes,s.MaxOtpAttempts,s.OtpResendCooldownSeconds,s.MaxOtpResends,s.NotifyOnAssigned,s.NotifyOnOutForDelivery,s.NotifyOnDelivered,s.NotifyOnDeliveryFailed,s.RequireCodConfirmation,s.AssignedTemplateName,s.OutForDeliveryTemplateName,s.OtpTemplateName,s.DeliveredTemplateName,s.FailedTemplateName,s.RescheduledTemplateName FROM commerce.TenantDeliverySettings s LEFT JOIN commerce.DeliveryAgents a ON a.DeliveryAgentId=s.DefaultDeliveryAgentId AND a.TenantId=s.TenantId WHERE s.TenantId=@tenant",c);P(q,"@tenant",tenantId);await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))throw new EntityNotFoundException("Delivery settings were not found.");var valid=r.GetBoolean(3);return new(r.GetBoolean(0),r.GetBoolean(1),r.IsDBNull(2)?null:r.GetGuid(2),valid,r.IsDBNull(2)||valid?null:"Default Delivery Agent is inactive or unavailable. Select another agent.",r.GetBoolean(4),r.GetInt32(5),r.GetInt32(6),r.GetInt32(7),r.GetInt32(8),r.GetBoolean(9),r.GetBoolean(10),r.GetBoolean(11),r.GetBoolean(12),r.GetBoolean(13),S(r,14),S(r,15),S(r,16),S(r,17),S(r,18),S(r,19)); }

    public async Task<DeliverySettingsDto> SaveSettings(Guid tenantId,SaveDeliverySettingsInput x,string actor,CancellationToken token)
    { if(x.DeliveryOtpExpiryMinutes is <1 or >60||x.MaxOtpAttempts is <1 or >10||x.OtpResendCooldownSeconds is <30 or >600||x.MaxOtpResends is <1 or >10)throw new BusinessRuleException("OTP settings are outside the permitted security limits.");if(x.DefaultDeliveryAgentId is not null){await using var c0=await Open(token);await using var v=new SqlCommand("SELECT COUNT(1) FROM commerce.DeliveryAgents WHERE TenantId=@tenant AND DeliveryAgentId=@id AND IsActive=1",c0);P(v,"@tenant",tenantId);P(v,"@id",x.DefaultDeliveryAgentId);if(Convert.ToInt32(await v.ExecuteScalarAsync(token),CultureInfo.InvariantCulture)!=1)throw new BusinessRuleException("The default agent must be active and belong to this tenant.");}await using var c=await Open(token);await using var q=new SqlCommand(@"UPDATE commerce.TenantDeliverySettings SET DeliveryEnabled=@enabled,AutomaticAssignmentEnabled=@auto,DefaultDeliveryAgentId=@default,RequireDeliveryOtp=@otp,DeliveryOtpExpiryMinutes=@expiry,MaxOtpAttempts=@attempts,OtpResendCooldownSeconds=@cooldown,MaxOtpResends=@resends,NotifyOnAssigned=@assigned,NotifyOnOutForDelivery=@out,NotifyOnDelivered=@delivered,NotifyOnDeliveryFailed=@failed,RequireCodConfirmation=@cod,AssignedTemplateName=@ta,OutForDeliveryTemplateName=@to,OtpTemplateName=@tp,DeliveredTemplateName=@td,FailedTemplateName=@tf,RescheduledTemplateName=@tr,UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@actor WHERE TenantId=@tenant",c);foreach(var p in new[]{("@enabled",(object)x.DeliveryEnabled),("@auto",x.AutomaticAssignmentEnabled),("@default",Db(x.DefaultDeliveryAgentId)),("@otp",x.RequireDeliveryOtp),("@expiry",x.DeliveryOtpExpiryMinutes),("@attempts",x.MaxOtpAttempts),("@cooldown",x.OtpResendCooldownSeconds),("@resends",x.MaxOtpResends),("@assigned",x.NotifyOnAssigned),("@out",x.NotifyOnOutForDelivery),("@delivered",x.NotifyOnDelivered),("@failed",x.NotifyOnDeliveryFailed),("@cod",x.RequireCodConfirmation),("@ta",Db(x.AssignedTemplateName)),("@to",Db(x.OutForDeliveryTemplateName)),("@tp",Db(x.OtpTemplateName)),("@td",Db(x.DeliveredTemplateName)),("@tf",Db(x.FailedTemplateName)),("@tr",Db(x.RescheduledTemplateName)),("@actor",actor),("@tenant",tenantId)})q.Parameters.AddWithValue(p.Item1,p.Item2);await q.ExecuteNonQueryAsync(token);return await Settings(tenantId,token); }

    public async Task<DeliveryDashboardDto> Deliveries(Guid tenantId,DeliveryQuery query,CancellationToken token)
    { await using var c=await Open(token);var rows=await QueryDeliveries(c,tenantId,null,true,query,token);return new(rows.Count(x=>x.Status==DeliveryStatuses.Unassigned),rows.Count(x=>x.Status==DeliveryStatuses.Assigned),rows.Count(x=>x.Status==DeliveryStatuses.Ready),rows.Count(x=>x.Status==DeliveryStatuses.OutForDelivery),rows.Count(x=>x.Status==DeliveryStatuses.Delivered&&x.UpdatedAt.UtcDateTime.Date==DateTime.UtcNow.Date),rows.Count(x=>x.Status==DeliveryStatuses.Failed),rows.Count(x=>x.CodRequired&&!x.CodCollected&&x.Status!=DeliveryStatuses.Cancelled),rows.Count(x=>x.Status==DeliveryStatuses.Rescheduled),rows); }
    public async Task<IReadOnlyCollection<DeliveryDto>> MyDeliveries(Guid tenantId,Guid userId,string? status,CancellationToken token){await using var c=await Open(token);return await QueryDeliveries(c,tenantId,userId,false,new(status),token);}
    public async Task<DeliveryDto> Get(Guid tenantId,Guid deliveryId,Guid? actingUser,bool manage,CancellationToken token){await using var c=await Open(token);var rows=await QueryDeliveries(c,tenantId,manage?null:actingUser,manage,new(Search:deliveryId.ToString()),token);var row=rows.SingleOrDefault(x=>x.DeliveryId==deliveryId)??throw new EntityNotFoundException("Delivery was not found.");var history=await Events(c,tenantId,deliveryId,token);return row with{History=history};}
    Task<DeliveryDto> IDeliveryService.GetDelivery(Guid tenantId,Guid deliveryId,Guid? actingUser,bool manage,CancellationToken token)=>Get(tenantId,deliveryId,actingUser,manage,token);

    public async Task<DeliveryDto> Ready(Guid tenantId,Guid orderId,ReadyDeliveryInput input,Guid actorId,string actor,CancellationToken token)
    {
        await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);Guid deliveryId;Guid? agent;string? source;string current;
        await using(var existing=new SqlCommand("SELECT OrderDeliveryId,DeliveryAgentId,AssignmentSource,DeliveryStatus FROM commerce.OrderDeliveries WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@tenant AND OrderId=@order",c,tx)){P(existing,"@tenant",tenantId);P(existing,"@order",orderId);await using var r=await existing.ExecuteReaderAsync(token);if(await r.ReadAsync(token)){deliveryId=r.GetGuid(0);agent=r.IsDBNull(1)?null:r.GetGuid(1);source=S(r,2);current=r.GetString(3);}else{deliveryId=Guid.Empty;agent=null;source=null;current=DeliveryStatuses.Unassigned;}}
        if(deliveryId!=Guid.Empty&&source=="MANUAL"&&input.DeliveryAgentId is null){await tx.CommitAsync(token);return await Get(tenantId,deliveryId,null,true,token);}
        var previousAgent=agent;var previousSource=source;(agent,source)=await ResolveAssignment(c,tx,tenantId,input.DeliveryAgentId,token);var status=agent is null?DeliveryStatuses.Unassigned:DeliveryStatuses.Ready;
        if(deliveryId!=Guid.Empty&&previousAgent==agent&&string.Equals(previousSource,source,StringComparison.OrdinalIgnoreCase)&&current==status){await tx.CommitAsync(token);return await Get(tenantId,deliveryId,null,true,token);}
        if(deliveryId==Guid.Empty){deliveryId=Guid.NewGuid();await using var q=new SqlCommand(@"INSERT commerce.OrderDeliveries(OrderDeliveryId,TenantId,OrderId,DeliveryAgentId,DeliveryStatus,AssignmentSource,AssignedAt,AssignedBy,ReadyAt,CustomerNameSnapshot,CustomerMobileSnapshot,DeliveryAddressSnapshot,DeliveryNotes,CodRequired,CodAmount,SourceChannel) SELECT @id,@tenant,i.InvoiceId,@agent,@status,@source,CASE WHEN @agent IS NULL THEN NULL ELSE SYSUTCDATETIME() END,CASE WHEN @agent IS NULL THEN NULL ELSE @actor END,SYSUTCDATETIME(),cu.CustomerName,cu.Mobile,COALESCE(NULLIF(@address,''),NULLIF(w.DeliveryAddress,''),CONCAT_WS(', ',a.AddressLine1,a.AddressLine2,a.City,a.State,a.PostalCode),N'Address not provided'),@notes,COALESCE(@cod,CASE WHEN w.PaymentType='COD' THEN 1 ELSE 0 END),CASE WHEN COALESCE(@cod,CASE WHEN w.PaymentType='COD' THEN 1 ELSE 0 END)=1 THEN i.BalanceAmount ELSE 0 END,CASE WHEN w.InvoiceId IS NULL THEN N'ERP' ELSE N'WHATSAPP' END FROM sales.SalesInvoices i JOIN sales.Customers cu ON cu.CustomerId=i.CustomerId AND cu.TenantId=@tenant LEFT JOIN integration.WhatsAppCommerceOrders w ON w.InvoiceId=i.InvoiceId OUTER APPLY(SELECT TOP(1) ca.AddressLine1,ca.AddressLine2,ca.City,ca.State,ca.PostalCode FROM sales.CustomerAddresses ca WHERE ca.CustomerId=cu.CustomerId AND ca.AddressType='Shipping') a WHERE i.InvoiceId=@order AND i.Status NOT IN('CANCELLED','VOID','RETURNED')",c,tx);P(q,"@id",deliveryId);P(q,"@tenant",tenantId);P(q,"@order",orderId);P(q,"@agent",agent);P(q,"@status",status);P(q,"@source",source);P(q,"@actor",actorId);P(q,"@address",input.DeliveryAddress);P(q,"@notes",input.DeliveryNotes);P(q,"@cod",input.CodRequired);if(await q.ExecuteNonQueryAsync(token)!=1)throw new EntityNotFoundException("The active order was not found for this tenant or has no customer.");await Event(c,tx,tenantId,deliveryId,"CREATED",null,status,null,agent,actorId,"Order became ready for delivery",token);}
        else {await using var q=new SqlCommand("UPDATE commerce.OrderDeliveries SET DeliveryAgentId=@agent,DeliveryStatus=@status,AssignmentSource=@source,AssignedAt=CASE WHEN @agent IS NULL THEN NULL ELSE SYSUTCDATETIME() END,AssignedBy=CASE WHEN @agent IS NULL THEN NULL ELSE @actor END,ReadyAt=COALESCE(ReadyAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE TenantId=@tenant AND OrderDeliveryId=@id AND DeliveryStatus NOT IN('DELIVERED','CANCELLED','RETURNED')",c,tx);P(q,"@agent",agent);P(q,"@status",status);P(q,"@source",source);P(q,"@actor",actorId);P(q,"@tenant",tenantId);P(q,"@id",deliveryId);if(await q.ExecuteNonQueryAsync(token)==0)throw new BusinessRuleException("A completed delivery cannot be made ready again.");await Event(c,tx,tenantId,deliveryId,"READY",current,status,null,agent,actorId,null,token);}
        await tx.CommitAsync(token);if(agent is not null&&(await Settings(tenantId,token)).NotifyOnAssigned)await Notify(tenantId,deliveryId,DeliveryTemplateKeys.Assigned,null,token);return await Get(tenantId,deliveryId,null,true,token);
    }

    public async Task<DeliveryDto> Assign(Guid tenantId,Guid deliveryId,AssignDeliveryInput input,Guid actorId,string actor,CancellationToken token)
    { await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);Guid? old;string prior;await using(var read=new SqlCommand("SELECT DeliveryAgentId,DeliveryStatus FROM commerce.OrderDeliveries WITH(UPDLOCK) WHERE TenantId=@tenant AND OrderDeliveryId=@id",c,tx)){P(read,"@tenant",tenantId);P(read,"@id",deliveryId);await using var r=await read.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))throw new EntityNotFoundException("Delivery was not found.");old=r.IsDBNull(0)?null:r.GetGuid(0);prior=r.GetString(1);}if(prior is DeliveryStatuses.Delivered or DeliveryStatuses.Cancelled or DeliveryStatuses.Returned)throw new BusinessRuleException("A completed delivery cannot be reassigned.");Guid? next=input.DeliveryAgentId;if(next is not null)await ValidateAgent(c,tx,tenantId,next.Value,true,token);var status=next is null?DeliveryStatuses.Unassigned:(prior==DeliveryStatuses.Unassigned?DeliveryStatuses.Ready:prior);await using(var q=new SqlCommand("UPDATE commerce.OrderDeliveries SET DeliveryAgentId=@agent,AssignmentSource=CASE WHEN @agent IS NULL THEN NULL ELSE 'MANUAL' END,AssignedAt=CASE WHEN @agent IS NULL THEN NULL ELSE SYSUTCDATETIME() END,AssignedBy=CASE WHEN @agent IS NULL THEN NULL ELSE @actor END,DeliveryStatus=@status,UpdatedAt=SYSUTCDATETIME() WHERE TenantId=@tenant AND OrderDeliveryId=@id",c,tx)){P(q,"@agent",next);P(q,"@actor",actorId);P(q,"@status",status);P(q,"@tenant",tenantId);P(q,"@id",deliveryId);await q.ExecuteNonQueryAsync(token);}await Event(c,tx,tenantId,deliveryId,next is null?"UNASSIGNED":old is null?"ASSIGNED":"REASSIGNED",prior,status,old,next,actorId,input.Reason,token);await tx.CommitAsync(token);if(next is not null&&(await Settings(tenantId,token)).NotifyOnAssigned)await Notify(tenantId,deliveryId,DeliveryTemplateKeys.Assigned,null,token);return await Get(tenantId,deliveryId,null,true,token); }

    public Task<DeliveryDto> PickedUp(Guid t,Guid d,Guid u,string a,bool m,CancellationToken ct)=>Transition(t,d,u,a,m,DeliveryStatuses.PickedUp,[DeliveryStatuses.Ready,DeliveryStatuses.Assigned,DeliveryStatuses.Rescheduled],"PICKED_UP",null,ct);
    public async Task<DeliveryDto> OutForDelivery(Guid t,Guid d,Guid u,string a,bool m,CancellationToken ct){var result=await Transition(t,d,u,a,m,DeliveryStatuses.OutForDelivery,[DeliveryStatuses.PickedUp],"OUT_FOR_DELIVERY",null,ct);if((await Settings(t,ct)).NotifyOnOutForDelivery)await Notify(t,d,DeliveryTemplateKeys.OutForDelivery,null,ct);return result;}

    public async Task RequestOtp(Guid tenantId,Guid deliveryId,Guid userId,string actor,bool manage,CancellationToken token)
    { var settings=await Settings(tenantId,token);if(!settings.RequireDeliveryOtp)throw new BusinessRuleException("OTP proof of delivery is disabled for this tenant.");await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);await AssertAccess(c,tx,tenantId,deliveryId,userId,manage,[DeliveryStatuses.OutForDelivery],token);var now=DateTimeOffset.UtcNow;int resend=0;await using(var old=new SqlCommand("SELECT ResendCount,LastSentAt FROM commerce.OrderDeliveryOtps WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@tenant AND OrderDeliveryId=@id",c,tx)){P(old,"@tenant",tenantId);P(old,"@id",deliveryId);await using var r=await old.ExecuteReaderAsync(token);if(await r.ReadAsync(token)){resend=r.GetInt32(0)+1;if(resend>settings.MaxOtpResends)throw new BusinessRuleException("Maximum OTP resend count has been reached.");if(now-r.GetDateTimeOffset(1)<TimeSpan.FromSeconds(settings.OtpResendCooldownSeconds))throw new BusinessRuleException("Please wait before requesting another OTP.");}}
        var otp=RandomNumberGenerator.GetInt32(1000,10000).ToString(CultureInfo.InvariantCulture);var salt=RandomNumberGenerator.GetBytes(32);var hash=OtpHash(tenantId,deliveryId,otp,salt);await using(var q=new SqlCommand(@"MERGE commerce.OrderDeliveryOtps AS target USING(SELECT @id OrderDeliveryId) source ON target.OrderDeliveryId=source.OrderDeliveryId WHEN MATCHED THEN UPDATE SET TenantId=@tenant,OtpHash=@hash,OtpSalt=@salt,ExpiresAt=@expires,AttemptCount=0,ResendCount=@resend,LastSentAt=@now,VerifiedAt=NULL,InvalidatedAt=NULL WHEN NOT MATCHED THEN INSERT(OrderDeliveryId,TenantId,OtpHash,OtpSalt,ExpiresAt,ResendCount,LastSentAt) VALUES(@id,@tenant,@hash,@salt,@expires,@resend,@now);",c,tx)){P(q,"@id",deliveryId);P(q,"@tenant",tenantId);P(q,"@hash",hash);P(q,"@salt",salt);P(q,"@expires",now.AddMinutes(settings.DeliveryOtpExpiryMinutes));P(q,"@resend",resend);P(q,"@now",now);await q.ExecuteNonQueryAsync(token);}await Event(c,tx,tenantId,deliveryId,"OTP_REQUESTED",DeliveryStatuses.OutForDelivery,DeliveryStatuses.OutForDelivery,null,null,userId,null,token);await tx.CommitAsync(token);await Notify(tenantId,deliveryId,DeliveryTemplateKeys.Otp,otp,token); }

    public async Task<DeliveryDto> ConfirmOtp(Guid tenantId,Guid deliveryId,Guid userId,ConfirmOtpInput input,string actor,bool manage,CancellationToken token)
    { if(input.Otp?.Length!=4||!input.Otp.All(char.IsDigit))throw new BusinessRuleException("A valid four-digit OTP is required.");var settings=await Settings(tenantId,token);await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);var access=await AssertAccess(c,tx,tenantId,deliveryId,userId,manage,[DeliveryStatuses.OutForDelivery],token);if(settings.RequireCodConfirmation&&access.CodRequired&&!access.CodCollected&&access.Balance>0)throw new BusinessRuleException("COD collection must be confirmed before delivery.");byte[] hash,salt;DateTimeOffset expiry;int attempts;DateTimeOffset? verified,invalidated;await using(var q=new SqlCommand("SELECT OtpHash,OtpSalt,ExpiresAt,AttemptCount,VerifiedAt,InvalidatedAt FROM commerce.OrderDeliveryOtps WITH(UPDLOCK) WHERE TenantId=@tenant AND OrderDeliveryId=@id",c,tx)){P(q,"@tenant",tenantId);P(q,"@id",deliveryId);await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))throw new BusinessRuleException("Request a delivery OTP first.");hash=(byte[])r[0];salt=(byte[])r[1];expiry=r.GetDateTimeOffset(2);attempts=r.GetInt32(3);verified=r.IsDBNull(4)?null:r.GetDateTimeOffset(4);invalidated=r.IsDBNull(5)?null:r.GetDateTimeOffset(5);}if(verified is not null)return await CommitAndGet(tx,tenantId,deliveryId,token);if(invalidated is not null||expiry<=DateTimeOffset.UtcNow)throw new BusinessRuleException("The delivery OTP has expired. Request a new OTP.");if(attempts>=settings.MaxOtpAttempts)throw new BusinessRuleException("Maximum OTP attempts have been reached.");if(!CryptographicOperations.FixedTimeEquals(hash,OtpHash(tenantId,deliveryId,input.Otp,salt))){await using var bad=new SqlCommand("UPDATE commerce.OrderDeliveryOtps SET AttemptCount=AttemptCount+1,InvalidatedAt=CASE WHEN AttemptCount+1>=@max THEN SYSUTCDATETIME() END WHERE OrderDeliveryId=@id AND TenantId=@tenant",c,tx);P(bad,"@max",settings.MaxOtpAttempts);P(bad,"@id",deliveryId);P(bad,"@tenant",tenantId);await bad.ExecuteNonQueryAsync(token);await tx.CommitAsync(token);throw new BusinessRuleException("The delivery OTP is incorrect.");}await MarkDelivered(c,tx,tenantId,deliveryId,userId,"OTP",null,token);await using(var ok=new SqlCommand("UPDATE commerce.OrderDeliveryOtps SET VerifiedAt=SYSUTCDATETIME(),InvalidatedAt=SYSUTCDATETIME() WHERE OrderDeliveryId=@id AND TenantId=@tenant",c,tx)){P(ok,"@id",deliveryId);P(ok,"@tenant",tenantId);await ok.ExecuteNonQueryAsync(token);}await tx.CommitAsync(token);await Complete(tenantId,deliveryId,access.OrderId,access.CustomerId,actor,token);return await Get(tenantId,deliveryId,null,true,token); }

    public async Task<DeliveryDto> RecordCod(Guid tenantId,Guid deliveryId,Guid userId,CodCollectionInput input,string actor,bool manage,CancellationToken token)
    { var method=input.PaymentMethod.Trim().ToUpperInvariant();if(method is not("CASH" or "UPI" or "ALREADY_PAID"))throw new BusinessRuleException("COD payment method must be Cash, UPI, or Already Paid.");await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);var row=await AssertAccess(c,tx,tenantId,deliveryId,userId,manage,[DeliveryStatuses.PickedUp,DeliveryStatuses.OutForDelivery,DeliveryStatuses.Ready],token);if(!row.CodRequired)throw new BusinessRuleException("This is not a COD delivery.");if(row.CodCollected)return await CommitAndGet(tx,tenantId,deliveryId,token);if(method=="ALREADY_PAID"&&row.Balance>0)throw new BusinessRuleException("The invoice still has an outstanding balance.");if(method!="ALREADY_PAID"&&input.Amount!=row.Balance)throw new BusinessRuleException("The collected amount must equal the current invoice balance.");if(method!="ALREADY_PAID"&&input.Amount>0){await using var pay=new SqlCommand("sales.POS_AddPayment",c,tx){CommandType=CommandType.StoredProcedure};P(pay,"@InvoiceId",row.OrderId);P(pay,"@MethodCode",method);P(pay,"@Amount",input.Amount);P(pay,"@ReferenceNumber",input.Reference);P(pay,"@CreatedBy",actor);await pay.ExecuteNonQueryAsync(token);}await using(var q=new SqlCommand("UPDATE commerce.OrderDeliveries SET CodCollected=1,CodCollectedAt=SYSUTCDATETIME(),CodPaymentMethod=@method,CodReference=@reference,UpdatedAt=SYSUTCDATETIME() WHERE TenantId=@tenant AND OrderDeliveryId=@id AND CodCollected=0",c,tx)){P(q,"@method",method);P(q,"@reference",input.Reference);P(q,"@tenant",tenantId);P(q,"@id",deliveryId);await q.ExecuteNonQueryAsync(token);}await Event(c,tx,tenantId,deliveryId,"COD_COLLECTED",null,null,null,null,userId,$"Method: {method}; Amount: {input.Amount:0.00}",token);await tx.CommitAsync(token);return await Get(tenantId,deliveryId,null,true,token); }

    public async Task<DeliveryDto> Fail(Guid t,Guid d,Guid u,FailDeliveryInput x,string actor,bool manage,CancellationToken token){if(!DeliveryFailureReasons.All.Contains(x.Reason)||x.Reason.Equals("Other",StringComparison.OrdinalIgnoreCase)&&string.IsNullOrWhiteSpace(x.Details))throw new BusinessRuleException("Select a valid failure reason; details are required for Other.");var result=await Transition(t,d,u,actor,manage,DeliveryStatuses.Failed,[DeliveryStatuses.Ready,DeliveryStatuses.PickedUp,DeliveryStatuses.OutForDelivery],"FAILED",x.Reason+(string.IsNullOrWhiteSpace(x.Details)?null:$": {x.Details}"),token,"FailureReason=@reason,FailureDetails=@details,FailedAt=SYSUTCDATETIME(),",x.Reason,x.Details);if((await Settings(t,token)).NotifyOnDeliveryFailed)await Notify(t,d,DeliveryTemplateKeys.Failed,null,token);return result;}
    public async Task<DeliveryDto> Reschedule(Guid t,Guid d,Guid u,RescheduleDeliveryInput x,string actor,bool manage,CancellationToken token){if(x.NewDate<DateTimeOffset.UtcNow.Date)throw new BusinessRuleException("The rescheduled date cannot be in the past.");var result=await Transition(t,d,u,actor,manage,DeliveryStatuses.Rescheduled,[DeliveryStatuses.Failed,DeliveryStatuses.Ready,DeliveryStatuses.PickedUp,DeliveryStatuses.OutForDelivery],"RESCHEDULED",x.Reason,token,"ScheduledDate=@date,TimeWindow=@window,RescheduledAt=SYSUTCDATETIME(),",x.NewDate.Date,x.TimeWindow);if(x.DeliveryAgentId is not null)result=await Assign(t,d,new(x.DeliveryAgentId,"Reassigned during reschedule"),u,actor,token);await Notify(t,d,DeliveryTemplateKeys.Rescheduled,null,token);return result;}
    public async Task<DeliveryDto> OverrideDelivered(Guid t,Guid d,OverrideDeliveryInput x,Guid u,string actor,CancellationToken token){if(string.IsNullOrWhiteSpace(x.Reason))throw new BusinessRuleException("A reason is required for delivery without OTP.");await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);var row=await AssertAccess(c,tx,t,d,u,true,[DeliveryStatuses.Ready,DeliveryStatuses.PickedUp,DeliveryStatuses.OutForDelivery],token);var settings=await Settings(t,token);if(settings.RequireCodConfirmation&&row.CodRequired&&!row.CodCollected&&row.Balance>0&&!x.CodException)throw new BusinessRuleException("COD is still outstanding; an authorized COD exception must be explicit.");await MarkDelivered(c,tx,t,d,u,"MANUAL_OVERRIDE",x.Reason,token);await tx.CommitAsync(token);await Complete(t,d,row.OrderId,row.CustomerId,actor,token);return await Get(t,d,null,true,token);}

    private async Task<DeliveryDto> Transition(Guid t,Guid d,Guid u,string actor,bool manage,string next,IReadOnlyCollection<string> allowed,string eventType,string? notes,CancellationToken token,string extra="",object? extra1=null,object? extra2=null){await using var c=await Open(token);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(token);var row=await AssertAccess(c,tx,t,d,u,manage,allowed,token);await using var q=new SqlCommand($"UPDATE commerce.OrderDeliveries SET {extra} DeliveryStatus=@next,{Timestamp(next)}UpdatedAt=SYSUTCDATETIME() WHERE TenantId=@tenant AND OrderDeliveryId=@id AND DeliveryStatus=@prior",c,tx);P(q,"@next",next);P(q,"@tenant",t);P(q,"@id",d);P(q,"@prior",row.Status);if(extra1 is not null)P(q,next==DeliveryStatuses.Rescheduled?"@date":"@reason",extra1);if(extra2 is not null)P(q,next==DeliveryStatuses.Rescheduled?"@window":"@details",extra2);if(await q.ExecuteNonQueryAsync(token)!=1)throw new BusinessRuleException("The delivery state changed; refresh and retry.");await Event(c,tx,t,d,eventType,row.Status,next,null,null,u,notes,token);await tx.CommitAsync(token);return await Get(t,d,null,true,token);}
    private static string Timestamp(string status)=>status switch{DeliveryStatuses.PickedUp=>"PickedUpAt=SYSUTCDATETIME(),",DeliveryStatuses.OutForDelivery=>"OutForDeliveryAt=SYSUTCDATETIME(),",_=>""};
    private async Task<(Guid? Agent,string? Source)> ResolveAssignment(SqlConnection c,SqlTransaction tx,Guid tenant,Guid? explicitId,CancellationToken token){if(explicitId is not null)await ValidateAgent(c,tx,tenant,explicitId.Value,true,token);await using var q=new SqlCommand("SELECT s.DeliveryEnabled,s.AutomaticAssignmentEnabled,s.DefaultDeliveryAgentId,ISNULL(a.IsActive,0),ISNULL(a.IsAvailable,0) FROM commerce.TenantDeliverySettings s LEFT JOIN commerce.DeliveryAgents a ON a.DeliveryAgentId=s.DefaultDeliveryAgentId AND a.TenantId=s.TenantId WHERE s.TenantId=@tenant",c,tx);P(q,"@tenant",tenant);await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))throw new BusinessRuleException("Delivery settings are not configured for this tenant.");if(!r.GetBoolean(0))throw new BusinessRuleException("Delivery Management is disabled for this tenant.");var decision=DeliveryAssignmentPolicy.Resolve(explicitId,r.GetBoolean(1),r.IsDBNull(2)?null:r.GetGuid(2),r.GetBoolean(3),r.GetBoolean(4));return(decision.AgentId,decision.Source);}
    private static async Task ValidateAgent(SqlConnection c,SqlTransaction tx,Guid tenant,Guid id,bool available,CancellationToken token){await using var q=new SqlCommand("SELECT COUNT(1) FROM commerce.DeliveryAgents a JOIN core.Users u ON u.Id=a.UserId AND u.TenantId=a.TenantId AND u.IsActive=1 AND u.IsDeleted=0 WHERE a.TenantId=@tenant AND a.DeliveryAgentId=@id AND a.IsActive=1 AND (@available=0 OR a.IsAvailable=1)",c,tx);P(q,"@tenant",tenant);P(q,"@id",id);P(q,"@available",available);if(Convert.ToInt32(await q.ExecuteScalarAsync(token),CultureInfo.InvariantCulture)!=1)throw new BusinessRuleException("The selected delivery agent is inactive, unavailable, or belongs to another tenant.");}
    private sealed record AccessRow(string Status,Guid OrderId,Guid? CustomerId,bool CodRequired,bool CodCollected,decimal Balance);
    private static async Task<AccessRow> AssertAccess(SqlConnection c,SqlTransaction tx,Guid tenant,Guid delivery,Guid user,bool manage,IReadOnlyCollection<string> statuses,CancellationToken token){var names=statuses.Select((_,i)=>$"@s{i}").ToArray();await using var q=new SqlCommand($"SELECT d.DeliveryStatus,d.OrderId,i.CustomerId,d.CodRequired,d.CodCollected,i.BalanceAmount FROM commerce.OrderDeliveries d JOIN sales.SalesInvoices i ON i.InvoiceId=d.OrderId LEFT JOIN commerce.DeliveryAgents a ON a.DeliveryAgentId=d.DeliveryAgentId AND a.TenantId=d.TenantId WHERE d.TenantId=@tenant AND d.OrderDeliveryId=@id AND (@manage=1 OR a.UserId=@user) AND d.DeliveryStatus IN({string.Join(',',names)})",c,tx);P(q,"@tenant",tenant);P(q,"@id",delivery);P(q,"@manage",manage);P(q,"@user",user);for(var i=0;i<statuses.Count;i++)P(q,names[i],statuses.ElementAt(i));await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))throw new EntityNotFoundException("The delivery is not assigned to the current user or is not in an allowed state.");return new(r.GetString(0),r.GetGuid(1),r.IsDBNull(2)?null:r.GetGuid(2),r.GetBoolean(3),r.GetBoolean(4),r.GetDecimal(5));}
    private static async Task MarkDelivered(SqlConnection c,SqlTransaction tx,Guid tenant,Guid delivery,Guid actor,string proof,string? notes,CancellationToken token){await using var q=new SqlCommand("UPDATE commerce.OrderDeliveries SET DeliveryStatus='DELIVERED',ProofType=@proof,OtpVerified=CASE WHEN @proof='OTP' THEN 1 ELSE OtpVerified END,OtpVerifiedAt=CASE WHEN @proof='OTP' THEN SYSUTCDATETIME() ELSE OtpVerifiedAt END,DeliveredAt=SYSUTCDATETIME(),UpdatedAt=SYSUTCDATETIME() WHERE TenantId=@tenant AND OrderDeliveryId=@id AND DeliveryStatus<>'DELIVERED'",c,tx);P(q,"@proof",proof);P(q,"@tenant",tenant);P(q,"@id",delivery);if(await q.ExecuteNonQueryAsync(token)==0)throw new BusinessRuleException("Delivery is already completed.");await Event(c,tx,tenant,delivery,proof=="OTP"?"OTP_VERIFIED_AND_DELIVERED":"DELIVERED_OVERRIDE",DeliveryStatuses.OutForDelivery,DeliveryStatuses.Delivered,null,null,actor,notes,token);}
    private async Task Complete(Guid tenant,Guid delivery,Guid order,Guid? customer,string actor,CancellationToken token){await publisher.Publish(new OrderDeliveryCompletedEvent(tenant,order,delivery,customer,actor),token);if((await Settings(tenant,token)).NotifyOnDelivered)await Notify(tenant,delivery,DeliveryTemplateKeys.Delivered,null,token);}
    private byte[] OtpHash(Guid tenant,Guid delivery,string otp,byte[] salt){var secret=configuration["Delivery:OtpPepper"]??configuration["Jwt:SigningKey"]??throw new InvalidOperationException("Delivery OTP pepper is not configured.");using var h=new HMACSHA256(Encoding.UTF8.GetBytes(secret));return h.ComputeHash(Encoding.UTF8.GetBytes($"{tenant:N}:{delivery:N}:{Convert.ToHexString(salt)}:{otp}"));}

    private async Task Notify(Guid tenant,Guid delivery,string key,string? otp,CancellationToken token)
    { Guid notification=Guid.NewGuid();string? mobile,order,customer,agent,store,template,mode,api,phone,protectedToken;await using(var c=await Open(token)){await using var q=new SqlCommand(@"SELECT d.CustomerMobileSnapshot,i.InvoiceNumber,d.CustomerNameSnapshot,a.DisplayName,t.Name,CASE @key WHEN 'DELIVERY_ASSIGNED' THEN s.AssignedTemplateName WHEN 'OUT_FOR_DELIVERY' THEN s.OutForDeliveryTemplateName WHEN 'DELIVERY_OTP' THEN s.OtpTemplateName WHEN 'ORDER_DELIVERED' THEN s.DeliveredTemplateName WHEN 'DELIVERY_FAILED' THEN s.FailedTemplateName ELSE s.RescheduledTemplateName END,w.ProviderMode,w.ApiVersion,w.PhoneNumberId,w.AccessTokenProtected FROM commerce.OrderDeliveries d JOIN sales.SalesInvoices i ON i.InvoiceId=d.OrderId JOIN core.Tenants t ON t.TenantId=d.TenantId LEFT JOIN commerce.DeliveryAgents a ON a.DeliveryAgentId=d.DeliveryAgentId JOIN commerce.TenantDeliverySettings s ON s.TenantId=d.TenantId LEFT JOIN integration.WhatsAppConfigurations w ON w.TenantId=d.TenantId AND w.IsEnabled=1 WHERE d.TenantId=@tenant AND d.OrderDeliveryId=@id",c);P(q,"@key",key);P(q,"@tenant",tenant);P(q,"@id",delivery);await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))return;mobile=S(r,0);order=r.GetString(1);customer=r.GetString(2);agent=S(r,3);store=r.GetString(4);template=S(r,5);mode=S(r,6);api=S(r,7);phone=S(r,8);protectedToken=S(r,9);if(string.IsNullOrWhiteSpace(mobile)||string.IsNullOrWhiteSpace(mode))return;await r.DisposeAsync();await using var insert=new SqlCommand("INSERT commerce.OrderDeliveryNotifications(NotificationId,TenantId,OrderDeliveryId,TemplateKey,RecipientMasked,Status,ProviderMode) VALUES(@n,@tenant,@id,@key,@recipient,'PENDING',@mode)",c);P(insert,"@n",notification);P(insert,"@tenant",tenant);P(insert,"@id",delivery);P(insert,"@key",key);P(insert,"@recipient",Mask(mobile));P(insert,"@mode",mode);await insert.ExecuteNonQueryAsync(token);}
        var message=key switch{DeliveryTemplateKeys.Assigned=>$"Your order #{order} has been assigned to {agent} from {store}.",DeliveryTemplateKeys.OutForDelivery=>$"Your order is out for delivery.\nOrder: #{order}\nDelivery Agent: {agent}\nYour order from {store} will reach you soon.",DeliveryTemplateKeys.Otp=>$"Delivery OTP for order #{order}: {otp}. It expires shortly. Do not share it except with your delivery agent.",DeliveryTemplateKeys.Delivered=>$"✅ Order Delivered\nYour order #{order} has been successfully delivered.\nThank you for shopping with {store}.",DeliveryTemplateKeys.Failed=>$"Delivery attempt for order #{order} was unsuccessful. {store} will contact you.",_=>$"Delivery for order #{order} has been rescheduled by {store}."};
        WhatsAppTransactionalMessageResult result;try{var provider=providers.Resolve(mode!);var tokenValue=mode!.Equals("MOCK",StringComparison.OrdinalIgnoreCase)?string.Empty:protection.CreateProtector("WhatsBiz.WhatsApp.Secrets.v1").Unprotect(protectedToken??throw new BusinessRuleException("Stored WhatsApp credential cannot be decrypted."));result=await provider.SendTransactionalAsync(new(api??"v22.0",phone??string.Empty,tokenValue,mobile!,key,template,"en",message,key==DeliveryTemplateKeys.Otp?[order,otp??string.Empty]:[order,agent??string.Empty,store]),token);}catch(Exception ex) when(ex is not OperationCanceledException){result=new(false,null,DateTimeOffset.UtcNow,"WhatsApp delivery notification could not be sent.");}
        await using var c2=await Open(token);await using var update=new SqlCommand("UPDATE commerce.OrderDeliveryNotifications SET Status=@status,ProviderMessageId=@provider,AttemptCount=AttemptCount+1,Retryable=@retry,LastError=@error,LastAttemptAt=SYSUTCDATETIME(),SentAt=CASE WHEN @status='SENT' THEN SYSUTCDATETIME() END WHERE NotificationId=@id AND TenantId=@tenant",c2);P(update,"@status",result.Succeeded?"SENT":"FAILED");P(update,"@provider",result.ProviderMessageId);P(update,"@retry",!result.Succeeded);P(update,"@error",result.Succeeded?null:result.SafeMessage);P(update,"@id",notification);P(update,"@tenant",tenant);await update.ExecuteNonQueryAsync(token);
    }
    private static string Mask(string mobile)=>mobile.Length<=4?"****":new string('*',mobile.Length-4)+mobile[^4..];
    private static async Task Event(SqlConnection c,SqlTransaction tx,Guid tenant,Guid delivery,string type,string? prior,string? next,Guid? oldAgent,Guid? agent,Guid? actor,string? notes,CancellationToken token){await using var q=new SqlCommand("INSERT commerce.OrderDeliveryEvents(TenantId,OrderDeliveryId,EventType,PreviousStatus,NewStatus,PreviousDeliveryAgentId,DeliveryAgentId,ActorUserId,Notes) VALUES(@tenant,@delivery,@type,@prior,@next,@old,@agent,@actor,@notes)",c,tx);P(q,"@tenant",tenant);P(q,"@delivery",delivery);P(q,"@type",type);P(q,"@prior",prior);P(q,"@next",next);P(q,"@old",oldAgent);P(q,"@agent",agent);P(q,"@actor",actor);P(q,"@notes",notes);await q.ExecuteNonQueryAsync(token);}
    private static async Task<IReadOnlyCollection<DeliveryEventDto>> Events(SqlConnection c,Guid tenant,Guid delivery,CancellationToken token){var rows=new List<DeliveryEventDto>();await using var q=new SqlCommand("SELECT EventId,EventType,PreviousStatus,NewStatus,PreviousDeliveryAgentId,DeliveryAgentId,ActorUserId,Notes,Metadata,CreatedAt FROM commerce.OrderDeliveryEvents WHERE TenantId=@tenant AND OrderDeliveryId=@id ORDER BY CreatedAt DESC,EventId DESC",c);P(q,"@tenant",tenant);P(q,"@id",delivery);await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))rows.Add(new(r.GetInt64(0),r.GetString(1),S(r,2),S(r,3),G(r,4),G(r,5),G(r,6),S(r,7),S(r,8),r.GetDateTimeOffset(9)));return rows;}
    private static async Task<IReadOnlyCollection<DeliveryDto>> QueryDeliveries(SqlConnection c,Guid tenant,Guid? user,bool manage,DeliveryQuery f,CancellationToken token){var rows=new List<DeliveryDto>();await using var q=new SqlCommand(@"SELECT d.OrderDeliveryId,d.OrderId,i.InvoiceNumber,i.InvoiceDate,d.DeliveryStatus,d.DeliveryAgentId,a.DisplayName,d.AssignmentSource,d.CustomerNameSnapshot,d.CustomerMobileSnapshot,d.DeliveryAddressSnapshot,d.DeliveryNotes,i.GrandTotal,d.CodRequired,d.CodAmount,d.CodCollected,d.CodPaymentMethod,d.ScheduledDate,d.TimeWindow,d.SourceChannel,d.OtpVerified,d.UpdatedAt,d.Latitude,d.Longitude FROM commerce.OrderDeliveries d JOIN sales.SalesInvoices i ON i.InvoiceId=d.OrderId LEFT JOIN commerce.DeliveryAgents a ON a.DeliveryAgentId=d.DeliveryAgentId AND a.TenantId=d.TenantId WHERE d.TenantId=@tenant AND (@manage=1 OR a.UserId=@user) AND (@status IS NULL OR d.DeliveryStatus=@status) AND (@agent IS NULL OR d.DeliveryAgentId=@agent) AND (@payment IS NULL OR (@payment='COD' AND d.CodRequired=1) OR (@payment='PREPAID' AND d.CodRequired=0)) AND (@from IS NULL OR i.InvoiceDate>=@from) AND (@to IS NULL OR i.InvoiceDate<@to) AND (@search IS NULL OR i.InvoiceNumber LIKE '%'+@search+'%' OR d.CustomerNameSnapshot LIKE '%'+@search+'%' OR CONVERT(nvarchar(36),d.OrderDeliveryId)=@search) ORDER BY d.UpdatedAt DESC",c);P(q,"@tenant",tenant);P(q,"@manage",manage);P(q,"@user",user);P(q,"@status",f.Status);P(q,"@agent",f.AgentId);P(q,"@payment",f.PaymentType);P(q,"@from",f.From);P(q,"@to",f.To);P(q,"@search",f.Search);await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token)){var address=r.GetString(10);var nav=!r.IsDBNull(22)&&!r.IsDBNull(23)?$"https://www.google.com/maps/search/?api=1&query={r.GetDecimal(22).ToString(CultureInfo.InvariantCulture)},{r.GetDecimal(23).ToString(CultureInfo.InvariantCulture)}":$"https://www.google.com/maps/search/?api=1&query={Uri.EscapeDataString(address)}";rows.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetDateTimeOffset(3),r.GetString(4),G(r,5),S(r,6),S(r,7),r.GetString(8),S(r,9),address,S(r,11),r.GetDecimal(12),r.GetBoolean(13),r.GetDecimal(14),r.GetBoolean(15),S(r,16),r.IsDBNull(17)?null:new DateTimeOffset(r.GetDateTime(17),TimeSpan.Zero),S(r,18),r.GetString(19),r.GetBoolean(20),r.GetDateTimeOffset(21),nav));}return rows;}
    private static async Task<DeliveryDto> CommitAndGet(SqlTransaction tx,Guid tenant,Guid delivery,CancellationToken token){await tx.CommitAsync(token);throw new BusinessRuleException("The operation was already completed. Refresh the delivery.");}
    private static string? S(SqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static Guid? G(SqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetGuid(i);
}
