<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"><PrivateAssets>all</PrivateAssets></PackageReference>
    <ProjectReference Include="..\WhatsBiz.Application\WhatsBiz.Application.csproj" />
    <ProjectReference Include="..\WhatsBiz.Domain\WhatsBiz.Domain.csproj" />
  </ItemGroup>
</Project>
