#pragma warning disable CA1725
using MediatR;using WhatsBiz.Application.Common.Exceptions;using WhatsBiz.Application.Common.Interfaces;using WhatsBiz.Domain.Suppliers;
namespace WhatsBiz.Application.Features.Suppliers;
internal static class SupplierMap{public static SupplierDto Dto(Supplier s)=>new(s.SupplierId,s.SupplierCode,s.SupplierName,s.SupplierType,s.GSTIN,s.PAN,s.MSMERegistrationNumber,s.Email,s.Mobile,s.Telephone,s.Website,s.Currency,s.PaymentTermId,s.PaymentTerm?.PaymentTermName,s.CreditLimit,s.OpeningBalance,s.IsGSTRegistered,s.IsTDSApplicable,s.IsActive,s.Remarks,s.Contacts.Select(x=>new SupplierContactDto(x.ContactId,x.ContactPerson,x.Designation,x.Mobile,x.Email,x.Department,x.IsPrimary)).ToArray(),s.Addresses.Select(x=>new SupplierAddressDto(x.AddressId,x.AddressType,x.AddressLine1,x.AddressLine2,x.City,x.District,x.State,x.Country,x.PostalCode)).ToArray(),s.BankAccounts.Select(x=>new SupplierBankAccountDto(x.BankAccountId,x.BankName,x.Branch,x.AccountNumber,x.IFSCCode,x.UPIId)).ToArray(),s.Documents.Where(x=>!x.IsDeleted).Select(x=>new SupplierDocumentDto(x.DocumentId,x.DocumentType,x.FileName,x.ContentType,x.UploadedOn)).ToArray());public static void Apply(Supplier s,SupplierInput i){s.SupplierCode=i.SupplierCode.Trim();s.SupplierName=i.SupplierName.Trim();s.SupplierType=i.SupplierType.Trim();s.GSTIN=i.GSTIN?.Trim().ToUpperInvariant();s.PAN=i.PAN?.Trim().ToUpperInvariant();s.MSMERegistrationNumber=i.MSMERegistrationNumber?.Trim();s.Email=i.Email?.Trim();s.Mobile=i.Mobile?.Trim();s.Telephone=i.Telephone?.Trim();s.Website=i.Website?.Trim();s.Currency=i.Currency.Trim().ToUpperInvariant();s.PaymentTermId=i.PaymentTermId;s.CreditLimit=i.CreditLimit;s.OpeningBalance=i.OpeningBalance;s.IsGSTRegistered=i.IsGSTRegistered;s.IsTDSApplicable=i.IsTDSApplicable;s.IsActive=i.IsActive;s.Remarks=i.Remarks?.Trim();s.Contacts=i.Contacts.Select(x=>new SupplierContact{ContactPerson=x.ContactPerson,Designation=x.Designation,Mobile=x.Mobile,Email=x.Email,Department=x.Department,IsPrimary=x.IsPrimary}).ToList();s.Addresses=i.Addresses.Select(x=>new SupplierAddress{AddressType=x.AddressType,AddressLine1=x.AddressLine1,AddressLine2=x.AddressLine2,City=x.City,District=x.District,State=x.State,Country=x.Country,PostalCode=x.PostalCode}).ToList();s.BankAccounts=i.BankAccounts.Select(x=>new SupplierBankAccount{BankName=x.BankName,Branch=x.Branch,AccountNumber=x.AccountNumber,IFSCCode=x.IFSCCode,UPIId=x.UPIId}).ToList();}}
public sealed class GetSuppliersHandler(ISupplierRepository r):IRequestHandler<GetSuppliersQuery,PagedSuppliers>{public async Task<PagedSuppliers> Handle(GetSuppliersQuery q,CancellationToken t){var(x,c)=await r.SearchAsync(q.Search,q.IsActive,q.SortBy,q.Descending,q.PageNumber,q.PageSize,t);return new(x.Select(s=>new SupplierListDto(s.SupplierId,s.SupplierCode,s.SupplierName,s.SupplierType,s.GSTIN,s.Mobile,s.Email,s.Currency,s.CreditLimit,s.IsActive)).ToArray(),c,q.PageNumber,q.PageSize);}}
public sealed class GetSupplierHandler(ISupplierRepository r):IRequestHandler<GetSupplierQuery,SupplierDto>{public async Task<SupplierDto> Handle(GetSupplierQuery q,CancellationToken t)=>SupplierMap.Dto(await r.GetAsync(q.Id,false,t)??throw new EntityNotFoundException("Supplier not found."));}
public sealed class CreateSupplierHandler(ISupplierRepository r,ICurrentUserService u):IRequestHandler<CreateSupplierCommand,SupplierDto>{public async Task<SupplierDto> Handle(CreateSupplierCommand c,CancellationToken t){if(await r.DuplicateAsync(c.Input.SupplierCode,c.Input.GSTIN,c.Input.SupplierName,null,t))throw new BusinessRuleException("A supplier with the same code, GSTIN, or name already exists.");var s=new Supplier{CreatedBy=u.Username};SupplierMap.Apply(s,c.Input);r.Add(s);await r.SaveAsync(t);return SupplierMap.Dto(await r.GetAsync(s.SupplierId,false,t)??s);}}
public sealed class UpdateSupplierHandler(ISupplierRepository r,ICurrentUserService u):IRequestHandler<UpdateSupplierCommand,SupplierDto>{public async Task<SupplierDto> Handle(UpdateSupplierCommand c,CancellationToken t){var s=await r.GetAsync(c.Id,true,t)??throw new EntityNotFoundException("Supplier not found.");if(await r.DuplicateAsync(c.Input.SupplierCode,c.Input.GSTIN,c.Input.SupplierName,c.Id,t))throw new BusinessRuleException("A supplier with the same code, GSTIN, or name already exists.");r.RemoveChildren(s);SupplierMap.Apply(s,c.Input);s.ModifiedOn=DateTimeOffset.UtcNow;s.ModifiedBy=u.Username;await r.SaveAsync(t);return SupplierMap.Dto(await r.GetAsync(s.SupplierId,false,t)??s);}}
public sealed class DeleteSupplierHandler(ISupplierRepository r,ICurrentUserService u):IRequestHandler<DeleteSupplierCommand>{public async Task Handle(DeleteSupplierCommand c,CancellationToken t){var s=await r.GetAsync(c.Id,true,t)??throw new EntityNotFoundException("Supplier not found.");s.IsDeleted=true;s.IsActive=false;s.ModifiedOn=DateTimeOffset.UtcNow;s.ModifiedBy=u.Username;await r.SaveAsync(t);}}
public sealed class SupplierDropdownHandler(ISupplierRepository r):IRequestHandler<SupplierDropdownQuery,IReadOnlyCollection<SupplierDropdownDto>>{public async Task<IReadOnlyCollection<SupplierDropdownDto>> Handle(SupplierDropdownQuery q,CancellationToken t){var(x,_)=await r.SearchAsync(q.Search,true,"supplierName",false,1,100,t);return x.Select(s=>new SupplierDropdownDto(s.SupplierId,s.SupplierCode,s.SupplierName)).ToArray();}}
public sealed class PaymentTermsHandler(ISupplierRepository r):IRequestHandler<PaymentTermsQuery,IReadOnlyCollection<PaymentTermDto>>{public async Task<IReadOnlyCollection<PaymentTermDto>> Handle(PaymentTermsQuery q,CancellationToken t)=>(await r.PaymentTermsAsync(t)).Select(x=>new PaymentTermDto(x.PaymentTermId,x.PaymentTermCode,x.PaymentTermName,x.DueDays,x.IsDefault)).ToArray();}
public sealed class ExportSuppliersHandler(ISupplierRepository r,ISupplierSpreadsheetService x):IRequestHandler<ExportSuppliersQuery,byte[]>{public async Task<byte[]> Handle(ExportSuppliersQuery q,CancellationToken t){var(s,_)=await r.SearchAsync(q.Search,q.IsActive,"supplierName",false,1,10000,t);return x.Export(s);}}
public sealed class SupplierTemplateHandler(ISupplierSpreadsheetService x):IRequestHandler<SupplierTemplateQuery,byte[]>{public Task<byte[]> Handle(SupplierTemplateQuery q,CancellationToken t)=>Task.FromResult(x.Template());}
public sealed class ImportSuppliersHandler(ISupplierRepository r,ISupplierSpreadsheetService x,ICurrentUserService u):IRequestHandler<ImportSuppliersCommand,SupplierImportResult>{public async Task<SupplierImportResult> Handle(ImportSuppliersCommand c,CancellationToken t){var errors=new List<string>();var count=0;foreach(var row in x.Read(c.Data)){if(await r.DuplicateAsync(row.Code,row.GSTIN,row.Name,null,t)){errors.Add($"Row {row.Row}: duplicate supplier.");continue;}var s=new Supplier{SupplierCode=row.Code,SupplierName=row.Name,SupplierType=row.Type,GSTIN=row.GSTIN,PAN=row.PAN,Email=row.Email,Mobile=row.Mobile,Currency=row.Currency,CreditLimit=row.CreditLimit,IsActive=row.Active,CreatedBy=u.Username};r.Add(s);count++;}if(count>0)await r.SaveAsync(t);return new(count,errors);}}
public sealed class UploadSupplierDocumentHandler(ISupplierRepository r,ICurrentUserService u):IRequestHandler<UploadSupplierDocumentCommand,SupplierDocumentDto>{public async Task<SupplierDocumentDto> Handle(UploadSupplierDocumentCommand c,CancellationToken t){_ = await r.GetAsync(c.SupplierId,false,t)??throw new EntityNotFoundException("Supplier not found.");var d=new SupplierDocument{SupplierId=c.SupplierId,DocumentType=c.Type,FileName=c.FileName,ContentType=c.ContentType,DocumentData=c.Data,UploadedBy=u.Username};r.Add(d);await r.SaveAsync(t);return new(d.DocumentId,d.DocumentType,d.FileName,d.ContentType,d.UploadedOn);}}
public sealed class GetSupplierDocumentHandler(ISupplierRepository r):IRequestHandler<GetSupplierDocumentQuery,SupplierDocumentFile?>{public async Task<SupplierDocumentFile?> Handle(GetSupplierDocumentQuery q,CancellationToken t){var d=await r.DocumentAsync(q.SupplierId,q.DocumentId,false,t);return d is null?null:new(d.FileName,d.ContentType,d.DocumentData);}}
public sealed class DeleteSupplierDocumentHandler(ISupplierRepository r):IRequestHandler<DeleteSupplierDocumentCommand>{public async Task Handle(DeleteSupplierDocumentCommand c,CancellationToken t){var d=await r.DocumentAsync(c.SupplierId,c.DocumentId,true,t)??throw new EntityNotFoundException("Document not found.");d.IsDeleted=true;await r.SaveAsync(t);}}
