:r ..\SeedData\SupplierPaymentTerms.sql
:r ..\SeedData\CustomerPaymentTerms.sql
:r ..\SeedData\WarehouseTypes.sql
:r ..\SeedData\InventorySettings.sql
:r ..\SeedData\PaymentMethods.sql
:r ..\SeedData\InvoiceSeries.sql
:r ..\SeedData\PurchaseSeries.sql
:r .\RCDEV008-RuntimeObjects.sql
:r .\RCDEV009-PrintingPaperSize.sql
