SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF SCHEMA_ID(N'commerce') IS NULL EXEC(N'CREATE SCHEMA commerce AUTHORIZATION dbo');

IF OBJECT_ID(N'commerce.DeliveryAgents',N'U') IS NULL CREATE TABLE commerce.DeliveryAgents(
 DeliveryAgentId uniqueidentifier NOT NULL CONSTRAINT PK_DeliveryAgents PRIMARY KEY CONSTRAINT DF_DeliveryAgents_Id DEFAULT NEWSEQUENTIALID(),TenantId uniqueidentifier NOT NULL,UserId uniqueidentifier NOT NULL,DisplayName nvarchar(200) NOT NULL,Mobile nvarchar(20) NOT NULL,
 IsActive bit NOT NULL CONSTRAINT DF_DeliveryAgents_Active DEFAULT(1),IsAvailable bit NOT NULL CONSTRAINT DF_DeliveryAgents_Available DEFAULT(1),CreatedAt datetimeoffset NOT NULL CONSTRAINT DF_DeliveryAgents_Created DEFAULT SYSUTCDATETIME(),CreatedBy nvarchar(256) NULL,UpdatedAt datetimeoffset NULL,UpdatedBy nvarchar(256) NULL,
 CONSTRAINT FK_DeliveryAgents_Tenant FOREIGN KEY(TenantId) REFERENCES core.Tenants(TenantId),CONSTRAINT FK_DeliveryAgents_User FOREIGN KEY(UserId) REFERENCES core.Users(Id),CONSTRAINT UQ_DeliveryAgents_TenantUser UNIQUE(TenantId,UserId));

IF OBJECT_ID(N'commerce.TenantDeliverySettings',N'U') IS NULL CREATE TABLE commerce.TenantDeliverySettings(
 TenantId uniqueidentifier NOT NULL CONSTRAINT PK_TenantDeliverySettings PRIMARY KEY,DeliveryEnabled bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_Enabled DEFAULT(1),AutomaticAssignmentEnabled bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_Auto DEFAULT(1),DefaultDeliveryAgentId uniqueidentifier NULL,
 RequireDeliveryOtp bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_Otp DEFAULT(1),DeliveryOtpExpiryMinutes int NOT NULL CONSTRAINT DF_TenantDeliverySettings_Expiry DEFAULT(10),MaxOtpAttempts int NOT NULL CONSTRAINT DF_TenantDeliverySettings_Attempts DEFAULT(5),OtpResendCooldownSeconds int NOT NULL CONSTRAINT DF_TenantDeliverySettings_Cooldown DEFAULT(60),MaxOtpResends int NOT NULL CONSTRAINT DF_TenantDeliverySettings_Resends DEFAULT(5),
 NotifyOnAssigned bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_NAssigned DEFAULT(0),NotifyOnOutForDelivery bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_NOut DEFAULT(1),NotifyOnDelivered bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_NDelivered DEFAULT(1),NotifyOnDeliveryFailed bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_NFailed DEFAULT(1),RequireCodConfirmation bit NOT NULL CONSTRAINT DF_TenantDeliverySettings_Cod DEFAULT(1),
 AssignedTemplateName nvarchar(200) NULL,OutForDeliveryTemplateName nvarchar(200) NULL,OtpTemplateName nvarchar(200) NULL,DeliveredTemplateName nvarchar(200) NULL,FailedTemplateName nvarchar(200) NULL,RescheduledTemplateName nvarchar(200) NULL,UpdatedAt datetimeoffset NOT NULL CONSTRAINT DF_TenantDeliverySettings_Updated DEFAULT SYSUTCDATETIME(),UpdatedBy nvarchar(256) NULL,
 CONSTRAINT FK_TenantDeliverySettings_Tenant FOREIGN KEY(TenantId) REFERENCES core.Tenants(TenantId),CONSTRAINT FK_TenantDeliverySettings_DefaultAgent FOREIGN KEY(DefaultDeliveryAgentId) REFERENCES commerce.DeliveryAgents(DeliveryAgentId),CONSTRAINT CK_TenantDeliverySettings_Expiry CHECK(DeliveryOtpExpiryMinutes BETWEEN 1 AND 60),CONSTRAINT CK_TenantDeliverySettings_Attempts CHECK(MaxOtpAttempts BETWEEN 1 AND 10),CONSTRAINT CK_TenantDeliverySettings_Cooldown CHECK(OtpResendCooldownSeconds BETWEEN 30 AND 600),CONSTRAINT CK_TenantDeliverySettings_Resends CHECK(MaxOtpResends BETWEEN 1 AND 10));

IF OBJECT_ID(N'commerce.OrderDeliveries',N'U') IS NULL CREATE TABLE commerce.OrderDeliveries(
 OrderDeliveryId uniqueidentifier NOT NULL CONSTRAINT PK_OrderDeliveries PRIMARY KEY CONSTRAINT DF_OrderDeliveries_Id DEFAULT NEWSEQUENTIALID(),TenantId uniqueidentifier NOT NULL,OrderId uniqueidentifier NOT NULL,DeliveryAgentId uniqueidentifier NULL,DeliveryStatus nvarchar(30) NOT NULL CONSTRAINT DF_OrderDeliveries_Status DEFAULT(N'UNASSIGNED'),AssignmentSource nvarchar(20) NULL,AssignedAt datetimeoffset NULL,AssignedBy uniqueidentifier NULL,
 ReadyAt datetimeoffset NULL,PickedUpAt datetimeoffset NULL,OutForDeliveryAt datetimeoffset NULL,DeliveredAt datetimeoffset NULL,FailedAt datetimeoffset NULL,RescheduledAt datetimeoffset NULL,ScheduledDate date NULL,TimeWindow nvarchar(100) NULL,
 CustomerNameSnapshot nvarchar(250) NOT NULL,CustomerMobileSnapshot nvarchar(20) NULL,DeliveryAddressSnapshot nvarchar(1000) NOT NULL,Latitude decimal(10,7) NULL,Longitude decimal(10,7) NULL,DeliveryNotes nvarchar(1000) NULL,FailureReason nvarchar(100) NULL,FailureDetails nvarchar(500) NULL,
 ProofType nvarchar(20) NULL,OtpVerified bit NOT NULL CONSTRAINT DF_OrderDeliveries_OtpVerified DEFAULT(0),OtpVerifiedAt datetimeoffset NULL,CodRequired bit NOT NULL CONSTRAINT DF_OrderDeliveries_CodRequired DEFAULT(0),CodAmount decimal(18,2) NOT NULL CONSTRAINT DF_OrderDeliveries_CodAmount DEFAULT(0),CodCollected bit NOT NULL CONSTRAINT DF_OrderDeliveries_CodCollected DEFAULT(0),CodCollectedAt datetimeoffset NULL,CodPaymentMethod nvarchar(30) NULL,CodReference nvarchar(100) NULL,
 SourceChannel nvarchar(30) NOT NULL CONSTRAINT DF_OrderDeliveries_Source DEFAULT(N'ERP'),CreatedAt datetimeoffset NOT NULL CONSTRAINT DF_OrderDeliveries_Created DEFAULT SYSUTCDATETIME(),UpdatedAt datetimeoffset NOT NULL CONSTRAINT DF_OrderDeliveries_Updated DEFAULT SYSUTCDATETIME(),RowVersion rowversion NOT NULL,
 CONSTRAINT FK_OrderDeliveries_Tenant FOREIGN KEY(TenantId) REFERENCES core.Tenants(TenantId),CONSTRAINT FK_OrderDeliveries_Order FOREIGN KEY(OrderId) REFERENCES sales.SalesInvoices(InvoiceId),CONSTRAINT FK_OrderDeliveries_Agent FOREIGN KEY(DeliveryAgentId) REFERENCES commerce.DeliveryAgents(DeliveryAgentId),CONSTRAINT FK_OrderDeliveries_AssignedBy FOREIGN KEY(AssignedBy) REFERENCES core.Users(Id),CONSTRAINT UQ_OrderDeliveries_TenantOrder UNIQUE(TenantId,OrderId),
 CONSTRAINT CK_OrderDeliveries_Status CHECK(DeliveryStatus IN(N'UNASSIGNED',N'ASSIGNED',N'READY_FOR_PICKUP',N'PICKED_UP',N'OUT_FOR_DELIVERY',N'DELIVERED',N'DELIVERY_FAILED',N'RESCHEDULED',N'CANCELLED',N'RETURN_REQUESTED',N'RETURNED')),CONSTRAINT CK_OrderDeliveries_Assignment CHECK(AssignmentSource IS NULL OR AssignmentSource IN(N'MANUAL',N'DEFAULT',N'ZONE',N'AUTO',N'API')),CONSTRAINT CK_OrderDeliveries_Cod CHECK(CodAmount>=0));

IF OBJECT_ID(N'commerce.OrderDeliveryEvents',N'U') IS NULL CREATE TABLE commerce.OrderDeliveryEvents(EventId bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_OrderDeliveryEvents PRIMARY KEY,TenantId uniqueidentifier NOT NULL,OrderDeliveryId uniqueidentifier NOT NULL,EventType nvarchar(50) NOT NULL,PreviousStatus nvarchar(30) NULL,NewStatus nvarchar(30) NULL,PreviousDeliveryAgentId uniqueidentifier NULL,DeliveryAgentId uniqueidentifier NULL,ActorUserId uniqueidentifier NULL,Notes nvarchar(1000) NULL,Metadata nvarchar(max) NULL,CreatedAt datetimeoffset NOT NULL CONSTRAINT DF_OrderDeliveryEvents_Created DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_OrderDeliveryEvents_Tenant FOREIGN KEY(TenantId) REFERENCES core.Tenants(TenantId),CONSTRAINT FK_OrderDeliveryEvents_Delivery FOREIGN KEY(OrderDeliveryId) REFERENCES commerce.OrderDeliveries(OrderDeliveryId));

IF OBJECT_ID(N'commerce.OrderDeliveryOtps',N'U') IS NULL CREATE TABLE commerce.OrderDeliveryOtps(OrderDeliveryId uniqueidentifier NOT NULL CONSTRAINT PK_OrderDeliveryOtps PRIMARY KEY,TenantId uniqueidentifier NOT NULL,OtpHash varbinary(32) NOT NULL,OtpSalt varbinary(32) NOT NULL,ExpiresAt datetimeoffset NOT NULL,AttemptCount int NOT NULL CONSTRAINT DF_OrderDeliveryOtps_Attempts DEFAULT(0),ResendCount int NOT NULL CONSTRAINT DF_OrderDeliveryOtps_Resends DEFAULT(0),LastSentAt datetimeoffset NOT NULL,VerifiedAt datetimeoffset NULL,InvalidatedAt datetimeoffset NULL,CONSTRAINT FK_OrderDeliveryOtps_Tenant FOREIGN KEY(TenantId) REFERENCES core.Tenants(TenantId),CONSTRAINT FK_OrderDeliveryOtps_Delivery FOREIGN KEY(OrderDeliveryId) REFERENCES commerce.OrderDeliveries(OrderDeliveryId) ON DELETE CASCADE);

IF OBJECT_ID(N'commerce.OrderDeliveryNotifications',N'U') IS NULL CREATE TABLE commerce.OrderDeliveryNotifications(NotificationId uniqueidentifier NOT NULL CONSTRAINT PK_OrderDeliveryNotifications PRIMARY KEY CONSTRAINT DF_OrderDeliveryNotifications_Id DEFAULT NEWSEQUENTIALID(),TenantId uniqueidentifier NOT NULL,OrderDeliveryId uniqueidentifier NOT NULL,TemplateKey nvarchar(50) NOT NULL,RecipientMasked nvarchar(30) NULL,Status nvarchar(20) NOT NULL CONSTRAINT DF_OrderDeliveryNotifications_Status DEFAULT(N'PENDING'),ProviderMode nvarchar(20) NULL,ProviderMessageId nvarchar(200) NULL,AttemptCount int NOT NULL CONSTRAINT DF_OrderDeliveryNotifications_Attempts DEFAULT(0),Retryable bit NOT NULL CONSTRAINT DF_OrderDeliveryNotifications_Retry DEFAULT(1),LastError nvarchar(500) NULL,CreatedAt datetimeoffset NOT NULL CONSTRAINT DF_OrderDeliveryNotifications_Created DEFAULT SYSUTCDATETIME(),LastAttemptAt datetimeoffset NULL,SentAt datetimeoffset NULL,CONSTRAINT FK_OrderDeliveryNotifications_Tenant FOREIGN KEY(TenantId) REFERENCES core.Tenants(TenantId),CONSTRAINT FK_OrderDeliveryNotifications_Delivery FOREIGN KEY(OrderDeliveryId) REFERENCES commerce.OrderDeliveries(OrderDeliveryId),CONSTRAINT CK_OrderDeliveryNotifications_Status CHECK(Status IN(N'PENDING',N'SENT',N'FAILED')));

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'commerce.DeliveryAgents') AND name=N'IX_DeliveryAgents_TenantActive') CREATE INDEX IX_DeliveryAgents_TenantActive ON commerce.DeliveryAgents(TenantId,IsActive,IsAvailable) INCLUDE(DisplayName,Mobile,UserId);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'commerce.OrderDeliveries') AND name=N'IX_OrderDeliveries_TenantStatus') CREATE INDEX IX_OrderDeliveries_TenantStatus ON commerce.OrderDeliveries(TenantId,DeliveryStatus,UpdatedAt DESC) INCLUDE(OrderId,DeliveryAgentId,CodRequired,CodCollected);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'commerce.OrderDeliveries') AND name=N'IX_OrderDeliveries_AgentStatus') CREATE INDEX IX_OrderDeliveries_AgentStatus ON commerce.OrderDeliveries(TenantId,DeliveryAgentId,DeliveryStatus) INCLUDE(OrderId,CustomerNameSnapshot,CustomerMobileSnapshot,ScheduledDate);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'commerce.OrderDeliveryEvents') AND name=N'IX_OrderDeliveryEvents_Delivery') CREATE INDEX IX_OrderDeliveryEvents_Delivery ON commerce.OrderDeliveryEvents(TenantId,OrderDeliveryId,CreatedAt DESC);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'commerce.OrderDeliveryNotifications') AND name=N'IX_OrderDeliveryNotifications_Retry') CREATE INDEX IX_OrderDeliveryNotifications_Retry ON commerce.OrderDeliveryNotifications(Status,Retryable,LastAttemptAt) INCLUDE(TenantId,OrderDeliveryId,TemplateKey);

DECLARE @feature uniqueidentifier=(SELECT FeatureId FROM core.Features WHERE FeatureKey=N'DELIVERY_MANAGEMENT');
IF @feature IS NULL BEGIN SET @feature=NEWID();INSERT core.Features(FeatureId,FeatureKey,Name,Description,ModuleKey,ReleaseState,IsActive,FeatureType,ParentFeatureId,Version,SortOrder,CreatedBy) VALUES(@feature,N'DELIVERY_MANAGEMENT',N'Delivery Management',N'Unified delivery management for ERP, POS and WhatsApp Commerce orders.',N'DELIVERY',N'ACTIVE',1,N'MODULE',(SELECT FeatureId FROM core.Features WHERE FeatureKey=N'POS'),N'V1',45,N'V17 delivery management');END
ELSE UPDATE core.Features SET Name=N'Delivery Management',Description=N'Unified delivery management for ERP, POS and WhatsApp Commerce orders.',ParentFeatureId=(SELECT FeatureId FROM core.Features WHERE FeatureKey=N'POS'),Version=N'V1',SortOrder=45,ModuleKey=N'DELIVERY',IsActive=1 WHERE FeatureId=@feature;
INSERT core.PlanFeatures(PlanFeatureId,PlanId,FeatureId,IsEnabled,CreatedBy) SELECT NEWID(),p.PlanId,@feature,1,N'V17 delivery management' FROM core.Plans p WHERE p.IsActive=1 AND NOT EXISTS(SELECT 1 FROM core.PlanFeatures x WHERE x.PlanId=p.PlanId AND x.FeatureId=@feature);
INSERT core.TenantFeatures(TenantFeatureId,TenantId,FeatureId,IsEnabled,Reason,IsActive,CreatedBy) SELECT NEWID(),t.TenantId,@feature,1,N'Initialized as core delivery capability',1,N'V17 delivery management' FROM core.Tenants t WHERE t.IsActive=1 AND NOT EXISTS(SELECT 1 FROM core.TenantFeatures x WHERE x.TenantId=t.TenantId AND x.FeatureId=@feature);
INSERT commerce.TenantDeliverySettings(TenantId) SELECT t.TenantId FROM core.Tenants t WHERE t.IsActive=1 AND NOT EXISTS(SELECT 1 FROM commerce.TenantDeliverySettings s WHERE s.TenantId=t.TenantId);
COMMIT TRANSACTION;
