<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>WhatsBizERP-Api-Development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <ProjectReference Include="..\WhatsBiz.Application\WhatsBiz.Application.csproj" />
    <ProjectReference Include="..\WhatsBiz.Contracts\WhatsBiz.Contracts.csproj" />
    <ProjectReference Include="..\WhatsBiz.Infrastructure\WhatsBiz.Infrastructure.csproj" />
  </ItemGroup>
</Project>
