import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { permissionGuard } from './core/guards/permission.guard';
const productView={permission:'product.view'},productCreate={permission:'product.create'},productEdit={permission:'product.edit'};
const supplierView={permission:'supplier.view'},supplierCreate={permission:'supplier.create'},supplierEdit={permission:'supplier.edit'};
const customerView={permission:'customer.view'},customerCreate={permission:'customer.create'},customerEdit={permission:'customer.edit'};
const warehouseView={permission:'warehouse.view'},warehouseCreate={permission:'warehouse.create'},warehouseEdit={permission:'warehouse.edit'};
const inventoryView={permission:'inventory.view'},inventoryAdjust={permission:'inventory.adjust'},inventoryTransfer={permission:'inventory.transfer'},inventoryReserve={permission:'inventory.reserve'},inventoryVerify={permission:'inventory.verify'},inventoryReorder={permission:'inventory.reorder'},inventoryAlerts={permission:'inventory.alerts'};
const posView={permission:'pos.view'},posCreate={permission:'pos.create'},posEdit={permission:'pos.edit'},posReturn={permission:'pos.return'};
const purchaseView={permission:'purchase.view'},purchaseCreate={permission:'purchase.create'},purchaseEdit={permission:'purchase.edit'},purchaseReturn={permission:'purchase.return'},purchasePayment={permission:'purchase.payment'};
const ledgerView={permission:'ledger.view'},receiptView={permission:'receipt.view'},receiptCreate={permission:'receipt.create'},paymentView={permission:'payment.view'},paymentCreate={permission:'payment.create'},customerOutstanding={permission:'customer.outstanding.view'},supplierOutstanding={permission:'supplier.outstanding.view'},cashbookView={permission:'cashbook.view'},bankbookView={permission:'bankbook.view'};
const dashboardView={permission:'dashboard.view'},analyticsView={permission:'analytics.view'};
export const routes:Routes=[
 {path:'login',loadComponent:()=>import('./features/authentication/login/login.component').then(m=>m.LoginComponent)},
 {path:'403',loadComponent:()=>import('./features/forbidden/forbidden.component').then(m=>m.ForbiddenComponent)},
 {path:'unauthorized',loadComponent:()=>import('./features/unauthorized/unauthorized.component').then(m=>m.UnauthorizedComponent)},
 {path:'404',loadComponent:()=>import('./features/not-found/not-found.component').then(m=>m.NotFoundComponent)},
 {path:'',canActivate:[authGuard],loadComponent:()=>import('./layout/main-layout/main-layout.component').then(m=>m.MainLayoutComponent),children:[
  {path:'dashboard',canActivate:[permissionGuard],data:dashboardView,loadComponent:()=>import('./features/dashboard/dashboard.component').then(m=>m.DashboardComponent)},
  {path:'analytics/sales',canActivate:[permissionGuard],data:{...analyticsView,mode:'sales',title:'Sales Analytics'},loadComponent:()=>import('./features/dashboard/analytics-page.component').then(m=>m.AnalyticsPageComponent)},
  {path:'analytics/purchase',canActivate:[permissionGuard],data:{...analyticsView,mode:'purchase',title:'Purchase Analytics'},loadComponent:()=>import('./features/dashboard/analytics-page.component').then(m=>m.AnalyticsPageComponent)},
  {path:'analytics/inventory',canActivate:[permissionGuard],data:{...analyticsView,mode:'inventory',title:'Inventory Analytics'},loadComponent:()=>import('./features/dashboard/analytics-page.component').then(m=>m.AnalyticsPageComponent)},
  {path:'analytics/finance',canActivate:[permissionGuard],data:{...analyticsView,mode:'finance',title:'Finance Analytics'},loadComponent:()=>import('./features/dashboard/analytics-page.component').then(m=>m.AnalyticsPageComponent)},
  {path:'products',canActivate:[permissionGuard],data:productView,loadComponent:()=>import('./features/products/product-list.component').then(m=>m.ProductListComponent)},
  {path:'products/new',canActivate:[permissionGuard],data:productCreate,loadComponent:()=>import('./features/products/product-form.component').then(m=>m.ProductFormComponent)},
  {path:'products/:id/edit',canActivate:[permissionGuard],data:productEdit,loadComponent:()=>import('./features/products/product-form.component').then(m=>m.ProductFormComponent)},
  {path:'products/:id',canActivate:[permissionGuard],data:productView,loadComponent:()=>import('./features/products/product-view.component').then(m=>m.ProductViewComponent)},
  {path:'product-categories',canActivate:[permissionGuard],data:productView,loadComponent:()=>import('./features/products/category-management.component').then(m=>m.CategoryManagementComponent)},
  {path:'brands',canActivate:[permissionGuard],data:productView,loadComponent:()=>import('./features/products/brand-management.component').then(m=>m.BrandManagementComponent)},
  {path:'units',canActivate:[permissionGuard],data:productView,loadComponent:()=>import('./features/products/unit-management.component').then(m=>m.UnitManagementComponent)},
  {path:'suppliers',canActivate:[permissionGuard],data:supplierView,loadComponent:()=>import('./features/suppliers/supplier-list.component').then(m=>m.SupplierListComponent)},
  {path:'suppliers/new',canActivate:[permissionGuard],data:supplierCreate,loadComponent:()=>import('./features/suppliers/supplier-form.component').then(m=>m.SupplierFormComponent)},
  {path:'suppliers/:id/edit',canActivate:[permissionGuard],data:supplierEdit,loadComponent:()=>import('./features/suppliers/supplier-form.component').then(m=>m.SupplierFormComponent)},
  {path:'suppliers/:id',canActivate:[permissionGuard],data:supplierView,loadComponent:()=>import('./features/suppliers/supplier-view.component').then(m=>m.SupplierViewComponent)},
  {path:'customers',canActivate:[permissionGuard],data:customerView,loadComponent:()=>import('./features/customers/customer-list.component').then(m=>m.CustomerListComponent)},
  {path:'customers/new',canActivate:[permissionGuard],data:customerCreate,loadComponent:()=>import('./features/customers/customer-form.component').then(m=>m.CustomerFormComponent)},
  {path:'customers/:id/edit',canActivate:[permissionGuard],data:customerEdit,loadComponent:()=>import('./features/customers/customer-form.component').then(m=>m.CustomerFormComponent)},
  {path:'customers/:id',canActivate:[permissionGuard],data:customerView,loadComponent:()=>import('./features/customers/customer-view.component').then(m=>m.CustomerViewComponent)},
  {path:'warehouses',canActivate:[permissionGuard],data:warehouseView,loadComponent:()=>import('./features/warehouses/warehouse-list.component').then(m=>m.WarehouseListComponent)},
  {path:'warehouses/new',canActivate:[permissionGuard],data:warehouseCreate,loadComponent:()=>import('./features/warehouses/warehouse-form.component').then(m=>m.WarehouseFormComponent)},
  {path:'warehouses/:id/edit',canActivate:[permissionGuard],data:warehouseEdit,loadComponent:()=>import('./features/warehouses/warehouse-form.component').then(m=>m.WarehouseFormComponent)},
  {path:'warehouses/:id',canActivate:[permissionGuard],data:warehouseView,loadComponent:()=>import('./features/warehouses/warehouse-view.component').then(m=>m.WarehouseViewComponent)},
  {path:'warehouse-types',canActivate:[permissionGuard],data:warehouseView,loadComponent:()=>import('./features/warehouses/warehouse-type-management.component').then(m=>m.WarehouseTypeManagementComponent)},
  {path:'inventory',canActivate:[permissionGuard],data:inventoryView,loadComponent:()=>import('./features/inventory/inventory-dashboard.component').then(m=>m.InventoryDashboardComponent)},
  {path:'inventory/balance',canActivate:[permissionGuard],data:inventoryView,loadComponent:()=>import('./features/inventory/stock-balance.component').then(m=>m.StockBalanceComponent)},
  {path:'inventory/transactions',canActivate:[permissionGuard],data:inventoryView,loadComponent:()=>import('./features/inventory/inventory-transactions.component').then(m=>m.InventoryTransactionsComponent)},
  {path:'inventory/adjustment',canActivate:[permissionGuard],data:inventoryAdjust,loadComponent:()=>import('./features/inventory/stock-adjustment.component').then(m=>m.StockAdjustmentComponent)},
  {path:'inventory/transfer',canActivate:[permissionGuard],data:inventoryTransfer,loadComponent:()=>import('./features/inventory/stock-transfer.component').then(m=>m.StockTransferComponent)},
  {path:'inventory/reservation',canActivate:[permissionGuard],data:inventoryReserve,loadComponent:()=>import('./features/inventory/stock-reservation.component').then(m=>m.StockReservationComponent)},
  {path:'inventory/verification',canActivate:[permissionGuard],data:inventoryVerify,loadComponent:()=>import('./features/inventory/physical-stock-verification.component').then(m=>m.PhysicalStockVerificationComponent)},
  {path:'inventory/reorder',canActivate:[permissionGuard],data:{...inventoryReorder,mode:'reorder',title:'Reorder Suggestions'},loadComponent:()=>import('./features/inventory/stock-control-list.component').then(m=>m.StockControlListComponent)},
  {path:'inventory/alerts',canActivate:[permissionGuard],data:{...inventoryAlerts,mode:'alerts',title:'Inventory Alerts'},loadComponent:()=>import('./features/inventory/stock-control-list.component').then(m=>m.StockControlListComponent)},
  {path:'inventory/movement-history',canActivate:[permissionGuard],data:{...inventoryView,mode:'movement',title:'Stock Movement History'},loadComponent:()=>import('./features/inventory/stock-control-list.component').then(m=>m.StockControlListComponent)},
  {path:'pos',canActivate:[permissionGuard],data:posCreate,loadComponent:()=>import('./features/pos/pos-screen.component').then(m=>m.POSScreenComponent)},
  {path:'pos/today',canActivate:[permissionGuard],data:posView,loadComponent:()=>import('./features/pos/today-sales.component').then(m=>m.TodaySalesComponent)},
  {path:'pos/holds',canActivate:[permissionGuard],data:posEdit,loadComponent:()=>import('./features/pos/hold-bills.component').then(m=>m.HoldBillsComponent)},
  {path:'pos/resume',canActivate:[permissionGuard],data:posEdit,loadComponent:()=>import('./features/pos/hold-bills.component').then(m=>m.HoldBillsComponent)},
  {path:'pos/history',canActivate:[permissionGuard],data:posView,loadComponent:()=>import('./features/pos/invoice-history.component').then(m=>m.InvoiceHistoryComponent)},
  {path:'pos/returns',canActivate:[permissionGuard],data:posReturn,loadComponent:()=>import('./features/pos/return-screen.component').then(m=>m.ReturnScreenComponent)},
  {path:'purchases/dashboard',canActivate:[permissionGuard],data:purchaseView,loadComponent:()=>import('./features/purchases/purchase-dashboard.component').then(m=>m.PurchaseDashboardComponent)},
  {path:'purchases',canActivate:[permissionGuard],data:purchaseView,loadComponent:()=>import('./features/purchases/purchase-list.component').then(m=>m.PurchaseListComponent)},
  {path:'purchases/create',canActivate:[permissionGuard],data:purchaseCreate,loadComponent:()=>import('./features/purchases/purchase-form.component').then(m=>m.PurchaseFormComponent)},
  {path:'purchases/:id/edit',canActivate:[permissionGuard],data:purchaseEdit,loadComponent:()=>import('./features/purchases/purchase-form.component').then(m=>m.PurchaseFormComponent)},
  {path:'purchases/:id/payment',canActivate:[permissionGuard],data:purchasePayment,loadComponent:()=>import('./features/purchases/purchase-payment.component').then(m=>m.PurchasePaymentComponent)},
  {path:'purchases/:id/return',canActivate:[permissionGuard],data:purchaseReturn,loadComponent:()=>import('./features/purchases/purchase-return.component').then(m=>m.PurchaseReturnComponent)},
  {path:'purchases/:id',canActivate:[permissionGuard],data:purchaseView,loadComponent:()=>import('./features/purchases/purchase-details.component').then(m=>m.PurchaseDetailsComponent)},
  {path:'finance/customer-ledger',canActivate:[permissionGuard],data:{...ledgerView,party:'customer'},loadComponent:()=>import('./features/finance/party-ledger.component').then(m=>m.PartyLedgerComponent)},
  {path:'finance/supplier-ledger',canActivate:[permissionGuard],data:{...ledgerView,party:'supplier'},loadComponent:()=>import('./features/finance/party-ledger.component').then(m=>m.PartyLedgerComponent)},
  {path:'finance/cashbook',canActivate:[permissionGuard],data:{...cashbookView,kind:'cash'},loadComponent:()=>import('./features/finance/book.component').then(m=>m.FinanceBookComponent)},
  {path:'finance/bankbook',canActivate:[permissionGuard],data:{...bankbookView,kind:'bank'},loadComponent:()=>import('./features/finance/book.component').then(m=>m.FinanceBookComponent)},
  {path:'finance/daybook',canActivate:[permissionGuard],data:{...ledgerView,kind:'day'},loadComponent:()=>import('./features/finance/book.component').then(m=>m.FinanceBookComponent)},
  {path:'finance/receipt',canActivate:[permissionGuard],data:{...receiptCreate,kind:'receipt'},loadComponent:()=>import('./features/receivables/receivable-payable-entry.component').then(m=>m.ReceivablePayableEntryComponent)},
  {path:'finance/payment',canActivate:[permissionGuard],data:{...paymentCreate,kind:'payment'},loadComponent:()=>import('./features/receivables/receivable-payable-entry.component').then(m=>m.ReceivablePayableEntryComponent)},
  {path:'finance/customer-outstanding',canActivate:[permissionGuard],data:{...customerOutstanding,party:'customer'},loadComponent:()=>import('./features/receivables/outstanding-ageing.component').then(m=>m.OutstandingAgeingComponent)},
  {path:'finance/supplier-outstanding',canActivate:[permissionGuard],data:{...supplierOutstanding,party:'supplier'},loadComponent:()=>import('./features/receivables/outstanding-ageing.component').then(m=>m.OutstandingAgeingComponent)},
  {path:'finance/customer-ageing',canActivate:[permissionGuard],data:{...customerOutstanding,party:'customer',ageing:true},loadComponent:()=>import('./features/receivables/outstanding-ageing.component').then(m=>m.OutstandingAgeingComponent)},
  {path:'finance/supplier-ageing',canActivate:[permissionGuard],data:{...supplierOutstanding,party:'supplier',ageing:true},loadComponent:()=>import('./features/receivables/outstanding-ageing.component').then(m=>m.OutstandingAgeingComponent)},
  {path:'finance/collection-followup',canActivate:[permissionGuard],data:customerOutstanding,loadComponent:()=>import('./features/receivables/collection-followup.component').then(m=>m.CollectionFollowUpComponent)},
  {path:'',pathMatch:'full',redirectTo:'dashboard'}]},
 {path:'**',loadComponent:()=>import('./features/not-found/not-found.component').then(m=>m.NotFoundComponent)}];
